!自锚耦合1 
ksel,s,kp,,139 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,592 $ nslk,s $ *get,Node2,node,,num,min
ksel,s,kp,,615 $ nslk,s $ *get,Node3,node,,num,min
allsel 
cp,Next,Ux,Node1,Node2,Node3
cp,Next,Uy,Node1,Node2,Node3
cp,Next,Uz,Node1,Node2,Node3
Node1 = $ Node2 = $ Node3 =

!自锚耦合2 
ksel,s,kp,,142 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,660 $ nslk,s $ *get,Node2,node,,num,min
ksel,s,kp,,683 $ nslk,s $ *get,Node3,node,,num,min
allsel 
cp,Next,Ux,Node1,Node2,Node3
cp,Next,Uy,Node1,Node2,Node3
cp,Next,Uz,Node1,Node2,Node3
Node1 = $ Node2 = $ Node3 =

!塔梁耦合1 
ksel,s,kp,,160 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,1 $ nslk,s $ *get,Node2,node,,num,min
allsel 
cp,Next,Uy,Node1,Node2
cp,Next,Uz,Node1,Node2
cp,Next,Rotx,Node1,Node2
Node1 = $ Node2 =

!塔梁耦合2 
ksel,s,kp,,185 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,93 $ nslk,s $ *get,Node2,node,,num,min
allsel 
cp,Next,Uy,Node1,Node2
cp,Next,Uz,Node1,Node2
cp,Next,Rotx,Node1,Node2
Node1 = $ Node2 =

!主缆、塔耦合1 
ksel,s,kp,,158 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,406 $ nslk,s $ *get,Node2,node,,num,min
ksel,s,kp,,499 $ nslk,s $ *get,Node3,node,,num,min
allsel 
cp,Next,Ux,Node1,Node2,Node3
cp,Next,Uy,Node1,Node2,Node3
cp,Next,Uz,Node1,Node2,Node3
Node1 = $ Node2 = $ Node3 =

!主缆、梁耦合2 
ksel,s,kp,,183 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,498 $ nslk,s $ *get,Node2,node,,num,min
ksel,s,kp,,591 $ nslk,s $ *get,Node3,node,,num,min
allsel 
cp,Next,Ux,Node1,Node2,Node3
cp,Next,Uy,Node1,Node2,Node3
cp,Next,Uz,Node1,Node2,Node3
Node1 = $ Node2 = $ Node3 =

