lsel,none
cm,l_selected,line
numstr,line,1

! Girder_1 
l,1,2 ! Matlab中Line对象编号: 1; Ansys中line编号1 
l,2,3 ! Matlab中Line对象编号: 2; Ansys中line编号2 
l,3,4 ! Matlab中Line对象编号: 3; Ansys中line编号3 
l,4,5 ! Matlab中Line对象编号: 4; Ansys中line编号4 
l,5,6 ! Matlab中Line对象编号: 5; Ansys中line编号5 
l,6,7 ! Matlab中Line对象编号: 6; Ansys中line编号6 
l,7,8 ! Matlab中Line对象编号: 7; Ansys中line编号7 
l,8,9 ! Matlab中Line对象编号: 8; Ansys中line编号8 
l,9,10 ! Matlab中Line对象编号: 9; Ansys中line编号9 
l,10,11 ! Matlab中Line对象编号: 10; Ansys中line编号10 
l,11,12 ! Matlab中Line对象编号: 11; Ansys中line编号11 
l,12,13 ! Matlab中Line对象编号: 12; Ansys中line编号12 
l,13,14 ! Matlab中Line对象编号: 13; Ansys中line编号13 
l,14,15 ! Matlab中Line对象编号: 14; Ansys中line编号14 
l,15,16 ! Matlab中Line对象编号: 15; Ansys中line编号15 
l,16,17 ! Matlab中Line对象编号: 16; Ansys中line编号16 
l,17,18 ! Matlab中Line对象编号: 17; Ansys中line编号17 
l,18,19 ! Matlab中Line对象编号: 18; Ansys中line编号18 
l,19,20 ! Matlab中Line对象编号: 19; Ansys中line编号19 
l,20,21 ! Matlab中Line对象编号: 20; Ansys中line编号20 
l,21,22 ! Matlab中Line对象编号: 21; Ansys中line编号21 
l,22,23 ! Matlab中Line对象编号: 22; Ansys中line编号22 
l,23,24 ! Matlab中Line对象编号: 23; Ansys中line编号23 
l,24,25 ! Matlab中Line对象编号: 24; Ansys中line编号24 
l,25,26 ! Matlab中Line对象编号: 25; Ansys中line编号25 
l,26,27 ! Matlab中Line对象编号: 26; Ansys中line编号26 
l,27,28 ! Matlab中Line对象编号: 27; Ansys中line编号27 
l,28,29 ! Matlab中Line对象编号: 28; Ansys中line编号28 
l,29,30 ! Matlab中Line对象编号: 29; Ansys中line编号29 
l,30,31 ! Matlab中Line对象编号: 30; Ansys中line编号30 
l,31,32 ! Matlab中Line对象编号: 31; Ansys中line编号31 
l,32,33 ! Matlab中Line对象编号: 32; Ansys中line编号32 
l,33,34 ! Matlab中Line对象编号: 33; Ansys中line编号33 
l,34,35 ! Matlab中Line对象编号: 34; Ansys中line编号34 
l,35,36 ! Matlab中Line对象编号: 35; Ansys中line编号35 
l,36,37 ! Matlab中Line对象编号: 36; Ansys中line编号36 
l,37,38 ! Matlab中Line对象编号: 37; Ansys中line编号37 
l,38,39 ! Matlab中Line对象编号: 38; Ansys中line编号38 
l,39,40 ! Matlab中Line对象编号: 39; Ansys中line编号39 
l,40,41 ! Matlab中Line对象编号: 40; Ansys中line编号40 
l,41,42 ! Matlab中Line对象编号: 41; Ansys中line编号41 
l,42,43 ! Matlab中Line对象编号: 42; Ansys中line编号42 
l,43,44 ! Matlab中Line对象编号: 43; Ansys中line编号43 
l,44,45 ! Matlab中Line对象编号: 44; Ansys中line编号44 
l,45,46 ! Matlab中Line对象编号: 45; Ansys中line编号45 
l,46,47 ! Matlab中Line对象编号: 46; Ansys中line编号46 
l,47,48 ! Matlab中Line对象编号: 47; Ansys中line编号47 
l,48,49 ! Matlab中Line对象编号: 48; Ansys中line编号48 
l,49,50 ! Matlab中Line对象编号: 49; Ansys中line编号49 
l,50,51 ! Matlab中Line对象编号: 50; Ansys中line编号50 
l,51,52 ! Matlab中Line对象编号: 51; Ansys中line编号51 
l,52,53 ! Matlab中Line对象编号: 52; Ansys中line编号52 
l,53,54 ! Matlab中Line对象编号: 53; Ansys中line编号53 
l,54,55 ! Matlab中Line对象编号: 54; Ansys中line编号54 
l,55,56 ! Matlab中Line对象编号: 55; Ansys中line编号55 
l,56,57 ! Matlab中Line对象编号: 56; Ansys中line编号56 
l,57,58 ! Matlab中Line对象编号: 57; Ansys中line编号57 
l,58,59 ! Matlab中Line对象编号: 58; Ansys中line编号58 
l,59,60 ! Matlab中Line对象编号: 59; Ansys中line编号59 
l,60,61 ! Matlab中Line对象编号: 60; Ansys中line编号60 
l,61,62 ! Matlab中Line对象编号: 61; Ansys中line编号61 
l,62,63 ! Matlab中Line对象编号: 62; Ansys中line编号62 
l,63,64 ! Matlab中Line对象编号: 63; Ansys中line编号63 
l,64,65 ! Matlab中Line对象编号: 64; Ansys中line编号64 
l,65,66 ! Matlab中Line对象编号: 65; Ansys中line编号65 
l,66,67 ! Matlab中Line对象编号: 66; Ansys中line编号66 
l,67,68 ! Matlab中Line对象编号: 67; Ansys中line编号67 
l,68,69 ! Matlab中Line对象编号: 68; Ansys中line编号68 
l,69,70 ! Matlab中Line对象编号: 69; Ansys中line编号69 
l,70,71 ! Matlab中Line对象编号: 70; Ansys中line编号70 
l,71,72 ! Matlab中Line对象编号: 71; Ansys中line编号71 
l,72,73 ! Matlab中Line对象编号: 72; Ansys中line编号72 
l,73,74 ! Matlab中Line对象编号: 73; Ansys中line编号73 
l,74,75 ! Matlab中Line对象编号: 74; Ansys中line编号74 
l,75,76 ! Matlab中Line对象编号: 75; Ansys中line编号75 
l,76,77 ! Matlab中Line对象编号: 76; Ansys中line编号76 
l,77,78 ! Matlab中Line对象编号: 77; Ansys中line编号77 
l,78,79 ! Matlab中Line对象编号: 78; Ansys中line编号78 
l,79,80 ! Matlab中Line对象编号: 79; Ansys中line编号79 
l,80,81 ! Matlab中Line对象编号: 80; Ansys中line编号80 
l,81,82 ! Matlab中Line对象编号: 81; Ansys中line编号81 
l,82,83 ! Matlab中Line对象编号: 82; Ansys中line编号82 
l,83,84 ! Matlab中Line对象编号: 83; Ansys中line编号83 
l,84,85 ! Matlab中Line对象编号: 84; Ansys中line编号84 
l,85,86 ! Matlab中Line对象编号: 85; Ansys中line编号85 
l,86,87 ! Matlab中Line对象编号: 86; Ansys中line编号86 
l,87,88 ! Matlab中Line对象编号: 87; Ansys中line编号87 
l,88,89 ! Matlab中Line对象编号: 88; Ansys中line编号88 
l,89,90 ! Matlab中Line对象编号: 89; Ansys中line编号89 
l,90,91 ! Matlab中Line对象编号: 90; Ansys中line编号90 
l,91,92 ! Matlab中Line对象编号: 91; Ansys中line编号91 
l,92,93 ! Matlab中Line对象编号: 92; Ansys中line编号92 
lsel,all 
cmsel,u,l_selected 
cm,Line_Girder_1,line 
lsel,all 
cm,l_selected,line 
allsel 

! Girder_2 
l,94,95 ! Matlab中Line对象编号: 93; Ansys中line编号93 
l,95,96 ! Matlab中Line对象编号: 94; Ansys中line编号94 
l,96,97 ! Matlab中Line对象编号: 95; Ansys中line编号95 
l,97,98 ! Matlab中Line对象编号: 96; Ansys中line编号96 
l,98,99 ! Matlab中Line对象编号: 97; Ansys中line编号97 
l,99,100 ! Matlab中Line对象编号: 98; Ansys中line编号98 
l,100,101 ! Matlab中Line对象编号: 99; Ansys中line编号99 
l,101,102 ! Matlab中Line对象编号: 100; Ansys中line编号100 
l,102,103 ! Matlab中Line对象编号: 101; Ansys中line编号101 
l,103,104 ! Matlab中Line对象编号: 102; Ansys中line编号102 
l,104,105 ! Matlab中Line对象编号: 103; Ansys中line编号103 
l,105,106 ! Matlab中Line对象编号: 104; Ansys中line编号104 
l,106,107 ! Matlab中Line对象编号: 105; Ansys中line编号105 
l,107,108 ! Matlab中Line对象编号: 106; Ansys中line编号106 
l,108,109 ! Matlab中Line对象编号: 107; Ansys中line编号107 
l,109,110 ! Matlab中Line对象编号: 108; Ansys中line编号108 
l,110,111 ! Matlab中Line对象编号: 109; Ansys中line编号109 
l,111,112 ! Matlab中Line对象编号: 110; Ansys中line编号110 
l,112,113 ! Matlab中Line对象编号: 111; Ansys中line编号111 
l,113,114 ! Matlab中Line对象编号: 112; Ansys中line编号112 
l,114,1 ! Matlab中Line对象编号: 113; Ansys中line编号113 
lsel,all 
cmsel,u,l_selected 
cm,Line_Girder_2,line 
lsel,all 
cm,l_selected,line 
allsel 

! Girder_3 
l,93,117 ! Matlab中Line对象编号: 114; Ansys中line编号114 
l,117,118 ! Matlab中Line对象编号: 115; Ansys中line编号115 
l,118,119 ! Matlab中Line对象编号: 116; Ansys中line编号116 
l,119,120 ! Matlab中Line对象编号: 117; Ansys中line编号117 
l,120,121 ! Matlab中Line对象编号: 118; Ansys中line编号118 
l,121,122 ! Matlab中Line对象编号: 119; Ansys中line编号119 
l,122,123 ! Matlab中Line对象编号: 120; Ansys中line编号120 
l,123,124 ! Matlab中Line对象编号: 121; Ansys中line编号121 
l,124,125 ! Matlab中Line对象编号: 122; Ansys中line编号122 
l,125,126 ! Matlab中Line对象编号: 123; Ansys中line编号123 
l,126,127 ! Matlab中Line对象编号: 124; Ansys中line编号124 
l,127,128 ! Matlab中Line对象编号: 125; Ansys中line编号125 
l,128,129 ! Matlab中Line对象编号: 126; Ansys中line编号126 
l,129,130 ! Matlab中Line对象编号: 127; Ansys中line编号127 
l,130,131 ! Matlab中Line对象编号: 128; Ansys中line编号128 
l,131,132 ! Matlab中Line对象编号: 129; Ansys中line编号129 
l,132,133 ! Matlab中Line对象编号: 130; Ansys中line编号130 
l,133,134 ! Matlab中Line对象编号: 131; Ansys中line编号131 
l,134,135 ! Matlab中Line对象编号: 132; Ansys中line编号132 
l,135,136 ! Matlab中Line对象编号: 133; Ansys中line编号133 
l,136,137 ! Matlab中Line对象编号: 134; Ansys中line编号134 
lsel,all 
cmsel,u,l_selected 
cm,Line_Girder_3,line 
lsel,all 
cm,l_selected,line 
allsel 

! Girder_4 
l,138,139 ! Matlab中Line对象编号: 135; Ansys中line编号135 
l,139,94 ! Matlab中Line对象编号: 136; Ansys中line编号136 
lsel,all 
cmsel,u,l_selected 
cm,Line_Girder_4,line 
lsel,all 
cm,l_selected,line 
allsel 

! Girder_5 
l,137,142 ! Matlab中Line对象编号: 137; Ansys中line编号137 
l,142,143 ! Matlab中Line对象编号: 138; Ansys中line编号138 
lsel,all 
cmsel,u,l_selected 
cm,Line_Girder_5,line 
lsel,all 
cm,l_selected,line 
allsel 

! Tower_1 
l,144,145 ! Matlab中Line对象编号: 139; Ansys中line编号139 
l,145,146 ! Matlab中Line对象编号: 140; Ansys中line编号140 
l,146,153 ! Matlab中Line对象编号: 141; Ansys中line编号141 
l,147,148 ! Matlab中Line对象编号: 142; Ansys中line编号142 
l,148,149 ! Matlab中Line对象编号: 143; Ansys中line编号143 
l,149,144 ! Matlab中Line对象编号: 144; Ansys中line编号144 
l,150,152 ! Matlab中Line对象编号: 145; Ansys中line编号145 
l,151,152 ! Matlab中Line对象编号: 146; Ansys中line编号146 
l,152,167 ! Matlab中Line对象编号: 147; Ansys中line编号147 
l,153,154 ! Matlab中Line对象编号: 148; Ansys中line编号148 
l,154,151 ! Matlab中Line对象编号: 149; Ansys中line编号149 
l,154,150 ! Matlab中Line对象编号: 150; Ansys中line编号150 
l,155,147 ! Matlab中Line对象编号: 151; Ansys中line编号151 
l,156,150 ! Matlab中Line对象编号: 152; Ansys中line编号152 
l,157,158 ! Matlab中Line对象编号: 153; Ansys中line编号153 
l,158,164 ! Matlab中Line对象编号: 154; Ansys中line编号154 
l,159,160 ! Matlab中Line对象编号: 155; Ansys中line编号155 
l,151,159 ! Matlab中Line对象编号: 156; Ansys中line编号156 
l,160,156 ! Matlab中Line对象编号: 157; Ansys中line编号157 
l,161,162 ! Matlab中Line对象编号: 158; Ansys中line编号158 
l,162,163 ! Matlab中Line对象编号: 159; Ansys中line编号159 
l,163,155 ! Matlab中Line对象编号: 160; Ansys中line编号160 
l,164,165 ! Matlab中Line对象编号: 161; Ansys中line编号161 
l,165,166 ! Matlab中Line对象编号: 162; Ansys中line编号162 
l,166,161 ! Matlab中Line对象编号: 163; Ansys中line编号163 
lsel,all 
cmsel,u,l_selected 
cm,Line_Tower_1,line 
lsel,all 
cm,l_selected,line 
allsel 

! Tower_2 
l,169,170 ! Matlab中Line对象编号: 164; Ansys中line编号164 
l,170,171 ! Matlab中Line对象编号: 165; Ansys中line编号165 
l,171,178 ! Matlab中Line对象编号: 166; Ansys中line编号166 
l,172,173 ! Matlab中Line对象编号: 167; Ansys中line编号167 
l,173,174 ! Matlab中Line对象编号: 168; Ansys中line编号168 
l,174,169 ! Matlab中Line对象编号: 169; Ansys中line编号169 
l,175,177 ! Matlab中Line对象编号: 170; Ansys中line编号170 
l,176,177 ! Matlab中Line对象编号: 171; Ansys中line编号171 
l,177,192 ! Matlab中Line对象编号: 172; Ansys中line编号172 
l,178,179 ! Matlab中Line对象编号: 173; Ansys中line编号173 
l,179,176 ! Matlab中Line对象编号: 174; Ansys中line编号174 
l,179,175 ! Matlab中Line对象编号: 175; Ansys中line编号175 
l,180,172 ! Matlab中Line对象编号: 176; Ansys中line编号176 
l,181,175 ! Matlab中Line对象编号: 177; Ansys中line编号177 
l,182,183 ! Matlab中Line对象编号: 178; Ansys中line编号178 
l,183,189 ! Matlab中Line对象编号: 179; Ansys中line编号179 
l,184,185 ! Matlab中Line对象编号: 180; Ansys中line编号180 
l,176,184 ! Matlab中Line对象编号: 181; Ansys中line编号181 
l,185,181 ! Matlab中Line对象编号: 182; Ansys中line编号182 
l,186,187 ! Matlab中Line对象编号: 183; Ansys中line编号183 
l,187,188 ! Matlab中Line对象编号: 184; Ansys中line编号184 
l,188,180 ! Matlab中Line对象编号: 185; Ansys中line编号185 
l,189,190 ! Matlab中Line对象编号: 186; Ansys中line编号186 
l,190,191 ! Matlab中Line对象编号: 187; Ansys中line编号187 
l,191,186 ! Matlab中Line对象编号: 188; Ansys中line编号188 
lsel,all 
cmsel,u,l_selected 
cm,Line_Tower_2,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_1 
l,26,194 ! Matlab中Line对象编号: 189; Ansys中line编号189 
l,28,195 ! Matlab中Line对象编号: 190; Ansys中line编号190 
l,30,196 ! Matlab中Line对象编号: 191; Ansys中line编号191 
l,32,197 ! Matlab中Line对象编号: 192; Ansys中line编号192 
l,34,198 ! Matlab中Line对象编号: 193; Ansys中line编号193 
l,36,199 ! Matlab中Line对象编号: 194; Ansys中line编号194 
l,38,200 ! Matlab中Line对象编号: 195; Ansys中line编号195 
l,40,201 ! Matlab中Line对象编号: 196; Ansys中line编号196 
l,42,202 ! Matlab中Line对象编号: 197; Ansys中line编号197 
l,44,203 ! Matlab中Line对象编号: 198; Ansys中line编号198 
l,46,204 ! Matlab中Line对象编号: 199; Ansys中line编号199 
l,48,205 ! Matlab中Line对象编号: 200; Ansys中line编号200 
l,50,206 ! Matlab中Line对象编号: 201; Ansys中line编号201 
l,52,207 ! Matlab中Line对象编号: 202; Ansys中line编号202 
l,54,208 ! Matlab中Line对象编号: 203; Ansys中line编号203 
l,56,209 ! Matlab中Line对象编号: 204; Ansys中line编号204 
l,58,210 ! Matlab中Line对象编号: 205; Ansys中line编号205 
l,60,211 ! Matlab中Line对象编号: 206; Ansys中line编号206 
l,62,212 ! Matlab中Line对象编号: 207; Ansys中line编号207 
l,64,213 ! Matlab中Line对象编号: 208; Ansys中line编号208 
l,66,214 ! Matlab中Line对象编号: 209; Ansys中line编号209 
l,68,215 ! Matlab中Line对象编号: 210; Ansys中line编号210 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_1,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_2 
l,26,216 ! Matlab中Line对象编号: 211; Ansys中line编号211 
l,28,217 ! Matlab中Line对象编号: 212; Ansys中line编号212 
l,30,218 ! Matlab中Line对象编号: 213; Ansys中line编号213 
l,32,219 ! Matlab中Line对象编号: 214; Ansys中line编号214 
l,34,220 ! Matlab中Line对象编号: 215; Ansys中line编号215 
l,36,221 ! Matlab中Line对象编号: 216; Ansys中line编号216 
l,38,222 ! Matlab中Line对象编号: 217; Ansys中line编号217 
l,40,223 ! Matlab中Line对象编号: 218; Ansys中line编号218 
l,42,224 ! Matlab中Line对象编号: 219; Ansys中line编号219 
l,44,225 ! Matlab中Line对象编号: 220; Ansys中line编号220 
l,46,226 ! Matlab中Line对象编号: 221; Ansys中line编号221 
l,48,227 ! Matlab中Line对象编号: 222; Ansys中line编号222 
l,50,228 ! Matlab中Line对象编号: 223; Ansys中line编号223 
l,52,229 ! Matlab中Line对象编号: 224; Ansys中line编号224 
l,54,230 ! Matlab中Line对象编号: 225; Ansys中line编号225 
l,56,231 ! Matlab中Line对象编号: 226; Ansys中line编号226 
l,58,232 ! Matlab中Line对象编号: 227; Ansys中line编号227 
l,60,233 ! Matlab中Line对象编号: 228; Ansys中line编号228 
l,62,234 ! Matlab中Line对象编号: 229; Ansys中line编号229 
l,64,235 ! Matlab中Line对象编号: 230; Ansys中line编号230 
l,66,236 ! Matlab中Line对象编号: 231; Ansys中line编号231 
l,68,237 ! Matlab中Line对象编号: 232; Ansys中line编号232 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_2,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_3 
l,5,238 ! Matlab中Line对象编号: 233; Ansys中line编号233 
l,7,239 ! Matlab中Line对象编号: 234; Ansys中line编号234 
l,9,240 ! Matlab中Line对象编号: 235; Ansys中line编号235 
l,11,241 ! Matlab中Line对象编号: 236; Ansys中line编号236 
l,13,242 ! Matlab中Line对象编号: 237; Ansys中line编号237 
l,15,243 ! Matlab中Line对象编号: 238; Ansys中line编号238 
l,17,244 ! Matlab中Line对象编号: 239; Ansys中line编号239 
l,19,245 ! Matlab中Line对象编号: 240; Ansys中line编号240 
l,21,246 ! Matlab中Line对象编号: 241; Ansys中line编号241 
l,23,247 ! Matlab中Line对象编号: 242; Ansys中line编号242 
l,25,248 ! Matlab中Line对象编号: 243; Ansys中line编号243 
l,27,249 ! Matlab中Line对象编号: 244; Ansys中line编号244 
l,29,250 ! Matlab中Line对象编号: 245; Ansys中line编号245 
l,31,251 ! Matlab中Line对象编号: 246; Ansys中line编号246 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_3,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_4 
l,5,252 ! Matlab中Line对象编号: 247; Ansys中line编号247 
l,7,253 ! Matlab中Line对象编号: 248; Ansys中line编号248 
l,9,254 ! Matlab中Line对象编号: 249; Ansys中line编号249 
l,11,255 ! Matlab中Line对象编号: 250; Ansys中line编号250 
l,13,256 ! Matlab中Line对象编号: 251; Ansys中line编号251 
l,15,257 ! Matlab中Line对象编号: 252; Ansys中line编号252 
l,17,258 ! Matlab中Line对象编号: 253; Ansys中line编号253 
l,19,259 ! Matlab中Line对象编号: 254; Ansys中line编号254 
l,21,260 ! Matlab中Line对象编号: 255; Ansys中line编号255 
l,23,261 ! Matlab中Line对象编号: 256; Ansys中line编号256 
l,25,262 ! Matlab中Line对象编号: 257; Ansys中line编号257 
l,27,263 ! Matlab中Line对象编号: 258; Ansys中line编号258 
l,29,264 ! Matlab中Line对象编号: 259; Ansys中line编号259 
l,31,265 ! Matlab中Line对象编号: 260; Ansys中line编号260 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_4,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_5 
l,63,266 ! Matlab中Line对象编号: 261; Ansys中line编号261 
l,65,267 ! Matlab中Line对象编号: 262; Ansys中line编号262 
l,67,268 ! Matlab中Line对象编号: 263; Ansys中line编号263 
l,69,269 ! Matlab中Line对象编号: 264; Ansys中line编号264 
l,71,270 ! Matlab中Line对象编号: 265; Ansys中line编号265 
l,73,271 ! Matlab中Line对象编号: 266; Ansys中line编号266 
l,75,272 ! Matlab中Line对象编号: 267; Ansys中line编号267 
l,77,273 ! Matlab中Line对象编号: 268; Ansys中line编号268 
l,79,274 ! Matlab中Line对象编号: 269; Ansys中line编号269 
l,81,275 ! Matlab中Line对象编号: 270; Ansys中line编号270 
l,83,276 ! Matlab中Line对象编号: 271; Ansys中line编号271 
l,85,277 ! Matlab中Line对象编号: 272; Ansys中line编号272 
l,87,278 ! Matlab中Line对象编号: 273; Ansys中line编号273 
l,89,279 ! Matlab中Line对象编号: 274; Ansys中line编号274 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_5,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_6 
l,63,280 ! Matlab中Line对象编号: 275; Ansys中line编号275 
l,65,281 ! Matlab中Line对象编号: 276; Ansys中line编号276 
l,67,282 ! Matlab中Line对象编号: 277; Ansys中line编号277 
l,69,283 ! Matlab中Line对象编号: 278; Ansys中line编号278 
l,71,284 ! Matlab中Line对象编号: 279; Ansys中line编号279 
l,73,285 ! Matlab中Line对象编号: 280; Ansys中line编号280 
l,75,286 ! Matlab中Line对象编号: 281; Ansys中line编号281 
l,77,287 ! Matlab中Line对象编号: 282; Ansys中line编号282 
l,79,288 ! Matlab中Line对象编号: 283; Ansys中line编号283 
l,81,289 ! Matlab中Line对象编号: 284; Ansys中line编号284 
l,83,290 ! Matlab中Line对象编号: 285; Ansys中line编号285 
l,85,291 ! Matlab中Line对象编号: 286; Ansys中line编号286 
l,87,292 ! Matlab中Line对象编号: 287; Ansys中line编号287 
l,89,293 ! Matlab中Line对象编号: 288; Ansys中line编号288 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_6,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_7 
l,94,294 ! Matlab中Line对象编号: 289; Ansys中line编号289 
l,95,295 ! Matlab中Line对象编号: 290; Ansys中line编号290 
l,96,296 ! Matlab中Line对象编号: 291; Ansys中line编号291 
l,97,297 ! Matlab中Line对象编号: 292; Ansys中line编号292 
l,98,298 ! Matlab中Line对象编号: 293; Ansys中line编号293 
l,99,299 ! Matlab中Line对象编号: 294; Ansys中line编号294 
l,100,300 ! Matlab中Line对象编号: 295; Ansys中line编号295 
l,101,301 ! Matlab中Line对象编号: 296; Ansys中line编号296 
l,102,302 ! Matlab中Line对象编号: 297; Ansys中line编号297 
l,103,303 ! Matlab中Line对象编号: 298; Ansys中line编号298 
l,105,304 ! Matlab中Line对象编号: 299; Ansys中line编号299 
l,107,305 ! Matlab中Line对象编号: 300; Ansys中line编号300 
l,109,306 ! Matlab中Line对象编号: 301; Ansys中line编号301 
l,111,307 ! Matlab中Line对象编号: 302; Ansys中line编号302 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_7,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_8 
l,94,308 ! Matlab中Line对象编号: 303; Ansys中line编号303 
l,95,309 ! Matlab中Line对象编号: 304; Ansys中line编号304 
l,96,310 ! Matlab中Line对象编号: 305; Ansys中line编号305 
l,97,311 ! Matlab中Line对象编号: 306; Ansys中line编号306 
l,98,312 ! Matlab中Line对象编号: 307; Ansys中line编号307 
l,99,313 ! Matlab中Line对象编号: 308; Ansys中line编号308 
l,100,314 ! Matlab中Line对象编号: 309; Ansys中line编号309 
l,101,315 ! Matlab中Line对象编号: 310; Ansys中line编号310 
l,102,316 ! Matlab中Line对象编号: 311; Ansys中line编号311 
l,103,317 ! Matlab中Line对象编号: 312; Ansys中line编号312 
l,105,318 ! Matlab中Line对象编号: 313; Ansys中line编号313 
l,107,319 ! Matlab中Line对象编号: 314; Ansys中line编号314 
l,109,320 ! Matlab中Line对象编号: 315; Ansys中line编号315 
l,111,321 ! Matlab中Line对象编号: 316; Ansys中line编号316 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_8,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_9 
l,120,322 ! Matlab中Line对象编号: 317; Ansys中line编号317 
l,122,323 ! Matlab中Line对象编号: 318; Ansys中line编号318 
l,124,324 ! Matlab中Line对象编号: 319; Ansys中line编号319 
l,126,325 ! Matlab中Line对象编号: 320; Ansys中line编号320 
l,128,326 ! Matlab中Line对象编号: 321; Ansys中line编号321 
l,129,327 ! Matlab中Line对象编号: 322; Ansys中line编号322 
l,130,328 ! Matlab中Line对象编号: 323; Ansys中line编号323 
l,131,329 ! Matlab中Line对象编号: 324; Ansys中line编号324 
l,132,330 ! Matlab中Line对象编号: 325; Ansys中line编号325 
l,133,331 ! Matlab中Line对象编号: 326; Ansys中line编号326 
l,134,332 ! Matlab中Line对象编号: 327; Ansys中line编号327 
l,135,333 ! Matlab中Line对象编号: 328; Ansys中line编号328 
l,136,334 ! Matlab中Line对象编号: 329; Ansys中line编号329 
l,137,335 ! Matlab中Line对象编号: 330; Ansys中line编号330 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_9,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_10 
l,120,336 ! Matlab中Line对象编号: 331; Ansys中line编号331 
l,122,337 ! Matlab中Line对象编号: 332; Ansys中line编号332 
l,124,338 ! Matlab中Line对象编号: 333; Ansys中line编号333 
l,126,339 ! Matlab中Line对象编号: 334; Ansys中line编号334 
l,128,340 ! Matlab中Line对象编号: 335; Ansys中line编号335 
l,129,341 ! Matlab中Line对象编号: 336; Ansys中line编号336 
l,130,342 ! Matlab中Line对象编号: 337; Ansys中line编号337 
l,131,343 ! Matlab中Line对象编号: 338; Ansys中line编号338 
l,132,344 ! Matlab中Line对象编号: 339; Ansys中line编号339 
l,133,345 ! Matlab中Line对象编号: 340; Ansys中line编号340 
l,134,346 ! Matlab中Line对象编号: 341; Ansys中line编号341 
l,135,347 ! Matlab中Line对象编号: 342; Ansys中line编号342 
l,136,348 ! Matlab中Line对象编号: 343; Ansys中line编号343 
l,137,349 ! Matlab中Line对象编号: 344; Ansys中line编号344 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_10,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_11 
l,153,350 ! Matlab中Line对象编号: 345; Ansys中line编号345 
l,146,351 ! Matlab中Line对象编号: 346; Ansys中line编号346 
l,145,352 ! Matlab中Line对象编号: 347; Ansys中line编号347 
l,144,353 ! Matlab中Line对象编号: 348; Ansys中line编号348 
l,149,354 ! Matlab中Line对象编号: 349; Ansys中line编号349 
l,148,355 ! Matlab中Line对象编号: 350; Ansys中line编号350 
l,147,356 ! Matlab中Line对象编号: 351; Ansys中line编号351 
l,155,357 ! Matlab中Line对象编号: 352; Ansys中line编号352 
l,163,358 ! Matlab中Line对象编号: 353; Ansys中line编号353 
l,162,359 ! Matlab中Line对象编号: 354; Ansys中line编号354 
l,161,360 ! Matlab中Line对象编号: 355; Ansys中line编号355 
l,166,361 ! Matlab中Line对象编号: 356; Ansys中line编号356 
l,165,362 ! Matlab中Line对象编号: 357; Ansys中line编号357 
l,164,363 ! Matlab中Line对象编号: 358; Ansys中line编号358 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_11,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_12 
l,153,364 ! Matlab中Line对象编号: 359; Ansys中line编号359 
l,146,365 ! Matlab中Line对象编号: 360; Ansys中line编号360 
l,145,366 ! Matlab中Line对象编号: 361; Ansys中line编号361 
l,144,367 ! Matlab中Line对象编号: 362; Ansys中line编号362 
l,149,368 ! Matlab中Line对象编号: 363; Ansys中line编号363 
l,148,369 ! Matlab中Line对象编号: 364; Ansys中line编号364 
l,147,370 ! Matlab中Line对象编号: 365; Ansys中line编号365 
l,155,371 ! Matlab中Line对象编号: 366; Ansys中line编号366 
l,163,372 ! Matlab中Line对象编号: 367; Ansys中line编号367 
l,162,373 ! Matlab中Line对象编号: 368; Ansys中line编号368 
l,161,374 ! Matlab中Line对象编号: 369; Ansys中line编号369 
l,166,375 ! Matlab中Line对象编号: 370; Ansys中line编号370 
l,165,376 ! Matlab中Line对象编号: 371; Ansys中line编号371 
l,164,377 ! Matlab中Line对象编号: 372; Ansys中line编号372 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_12,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_13 
l,178,378 ! Matlab中Line对象编号: 373; Ansys中line编号373 
l,171,379 ! Matlab中Line对象编号: 374; Ansys中line编号374 
l,170,380 ! Matlab中Line对象编号: 375; Ansys中line编号375 
l,169,381 ! Matlab中Line对象编号: 376; Ansys中line编号376 
l,174,382 ! Matlab中Line对象编号: 377; Ansys中line编号377 
l,173,383 ! Matlab中Line对象编号: 378; Ansys中line编号378 
l,172,384 ! Matlab中Line对象编号: 379; Ansys中line编号379 
l,180,385 ! Matlab中Line对象编号: 380; Ansys中line编号380 
l,188,386 ! Matlab中Line对象编号: 381; Ansys中line编号381 
l,187,387 ! Matlab中Line对象编号: 382; Ansys中line编号382 
l,186,388 ! Matlab中Line对象编号: 383; Ansys中line编号383 
l,191,389 ! Matlab中Line对象编号: 384; Ansys中line编号384 
l,190,390 ! Matlab中Line对象编号: 385; Ansys中line编号385 
l,189,391 ! Matlab中Line对象编号: 386; Ansys中line编号386 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_13,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_14 
l,178,392 ! Matlab中Line对象编号: 387; Ansys中line编号387 
l,171,393 ! Matlab中Line对象编号: 388; Ansys中line编号388 
l,170,394 ! Matlab中Line对象编号: 389; Ansys中line编号389 
l,169,395 ! Matlab中Line对象编号: 390; Ansys中line编号390 
l,174,396 ! Matlab中Line对象编号: 391; Ansys中line编号391 
l,173,397 ! Matlab中Line对象编号: 392; Ansys中line编号392 
l,172,398 ! Matlab中Line对象编号: 393; Ansys中line编号393 
l,180,399 ! Matlab中Line对象编号: 394; Ansys中line编号394 
l,188,400 ! Matlab中Line对象编号: 395; Ansys中line编号395 
l,187,401 ! Matlab中Line对象编号: 396; Ansys中line编号396 
l,186,402 ! Matlab中Line对象编号: 397; Ansys中line编号397 
l,191,403 ! Matlab中Line对象编号: 398; Ansys中line编号398 
l,190,404 ! Matlab中Line对象编号: 399; Ansys中line编号399 
l,189,405 ! Matlab中Line对象编号: 400; Ansys中line编号400 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_14,line 
lsel,all 
cm,l_selected,line 
allsel 

! StayedCable_1 
l,238,350 ! Matlab中Line对象编号: 401; Ansys中line编号401 
l,239,351 ! Matlab中Line对象编号: 402; Ansys中line编号402 
l,240,352 ! Matlab中Line对象编号: 403; Ansys中line编号403 
l,241,353 ! Matlab中Line对象编号: 404; Ansys中line编号404 
l,242,354 ! Matlab中Line对象编号: 405; Ansys中line编号405 
l,243,355 ! Matlab中Line对象编号: 406; Ansys中line编号406 
l,244,356 ! Matlab中Line对象编号: 407; Ansys中line编号407 
l,245,357 ! Matlab中Line对象编号: 408; Ansys中line编号408 
l,246,358 ! Matlab中Line对象编号: 409; Ansys中line编号409 
l,247,359 ! Matlab中Line对象编号: 410; Ansys中line编号410 
l,248,360 ! Matlab中Line对象编号: 411; Ansys中line编号411 
l,249,361 ! Matlab中Line对象编号: 412; Ansys中line编号412 
l,250,362 ! Matlab中Line对象编号: 413; Ansys中line编号413 
l,251,363 ! Matlab中Line对象编号: 414; Ansys中line编号414 
lsel,all 
cmsel,u,l_selected 
cm,Line_StayedCable_1,line 
lsel,all 
cm,l_selected,line 
allsel 

! StayedCable_2 
l,252,364 ! Matlab中Line对象编号: 415; Ansys中line编号415 
l,253,365 ! Matlab中Line对象编号: 416; Ansys中line编号416 
l,254,366 ! Matlab中Line对象编号: 417; Ansys中line编号417 
l,255,367 ! Matlab中Line对象编号: 418; Ansys中line编号418 
l,256,368 ! Matlab中Line对象编号: 419; Ansys中line编号419 
l,257,369 ! Matlab中Line对象编号: 420; Ansys中line编号420 
l,258,370 ! Matlab中Line对象编号: 421; Ansys中line编号421 
l,259,371 ! Matlab中Line对象编号: 422; Ansys中line编号422 
l,260,372 ! Matlab中Line对象编号: 423; Ansys中line编号423 
l,261,373 ! Matlab中Line对象编号: 424; Ansys中line编号424 
l,262,374 ! Matlab中Line对象编号: 425; Ansys中line编号425 
l,263,375 ! Matlab中Line对象编号: 426; Ansys中line编号426 
l,264,376 ! Matlab中Line对象编号: 427; Ansys中line编号427 
l,265,377 ! Matlab中Line对象编号: 428; Ansys中line编号428 
lsel,all 
cmsel,u,l_selected 
cm,Line_StayedCable_2,line 
lsel,all 
cm,l_selected,line 
allsel 

! StayedCable_3 
l,266,391 ! Matlab中Line对象编号: 429; Ansys中line编号429 
l,267,390 ! Matlab中Line对象编号: 430; Ansys中line编号430 
l,268,389 ! Matlab中Line对象编号: 431; Ansys中line编号431 
l,269,388 ! Matlab中Line对象编号: 432; Ansys中line编号432 
l,270,387 ! Matlab中Line对象编号: 433; Ansys中line编号433 
l,271,386 ! Matlab中Line对象编号: 434; Ansys中line编号434 
l,272,385 ! Matlab中Line对象编号: 435; Ansys中line编号435 
l,273,384 ! Matlab中Line对象编号: 436; Ansys中line编号436 
l,274,383 ! Matlab中Line对象编号: 437; Ansys中line编号437 
l,275,382 ! Matlab中Line对象编号: 438; Ansys中line编号438 
l,276,381 ! Matlab中Line对象编号: 439; Ansys中line编号439 
l,277,380 ! Matlab中Line对象编号: 440; Ansys中line编号440 
l,278,379 ! Matlab中Line对象编号: 441; Ansys中line编号441 
l,279,378 ! Matlab中Line对象编号: 442; Ansys中line编号442 
lsel,all 
cmsel,u,l_selected 
cm,Line_StayedCable_3,line 
lsel,all 
cm,l_selected,line 
allsel 

! StayedCable_4 
l,280,405 ! Matlab中Line对象编号: 443; Ansys中line编号443 
l,281,404 ! Matlab中Line对象编号: 444; Ansys中line编号444 
l,282,403 ! Matlab中Line对象编号: 445; Ansys中line编号445 
l,283,402 ! Matlab中Line对象编号: 446; Ansys中line编号446 
l,284,401 ! Matlab中Line对象编号: 447; Ansys中line编号447 
l,285,400 ! Matlab中Line对象编号: 448; Ansys中line编号448 
l,286,399 ! Matlab中Line对象编号: 449; Ansys中line编号449 
l,287,398 ! Matlab中Line对象编号: 450; Ansys中line编号450 
l,288,397 ! Matlab中Line对象编号: 451; Ansys中line编号451 
l,289,396 ! Matlab中Line对象编号: 452; Ansys中line编号452 
l,290,395 ! Matlab中Line对象编号: 453; Ansys中line编号453 
l,291,394 ! Matlab中Line对象编号: 454; Ansys中line编号454 
l,292,393 ! Matlab中Line对象编号: 455; Ansys中line编号455 
l,293,392 ! Matlab中Line对象编号: 456; Ansys中line编号456 
lsel,all 
cmsel,u,l_selected 
cm,Line_StayedCable_4,line 
lsel,all 
cm,l_selected,line 
allsel 

! StayedCable_5 
l,294,363 ! Matlab中Line对象编号: 457; Ansys中line编号457 
l,295,362 ! Matlab中Line对象编号: 458; Ansys中line编号458 
l,296,361 ! Matlab中Line对象编号: 459; Ansys中line编号459 
l,297,360 ! Matlab中Line对象编号: 460; Ansys中line编号460 
l,298,359 ! Matlab中Line对象编号: 461; Ansys中line编号461 
l,299,358 ! Matlab中Line对象编号: 462; Ansys中line编号462 
l,300,357 ! Matlab中Line对象编号: 463; Ansys中line编号463 
l,301,356 ! Matlab中Line对象编号: 464; Ansys中line编号464 
l,302,355 ! Matlab中Line对象编号: 465; Ansys中line编号465 
l,303,354 ! Matlab中Line对象编号: 466; Ansys中line编号466 
l,304,353 ! Matlab中Line对象编号: 467; Ansys中line编号467 
l,305,352 ! Matlab中Line对象编号: 468; Ansys中line编号468 
l,306,351 ! Matlab中Line对象编号: 469; Ansys中line编号469 
l,307,350 ! Matlab中Line对象编号: 470; Ansys中line编号470 
lsel,all 
cmsel,u,l_selected 
cm,Line_StayedCable_5,line 
lsel,all 
cm,l_selected,line 
allsel 

! StayedCable_6 
l,308,377 ! Matlab中Line对象编号: 471; Ansys中line编号471 
l,309,376 ! Matlab中Line对象编号: 472; Ansys中line编号472 
l,310,375 ! Matlab中Line对象编号: 473; Ansys中line编号473 
l,311,374 ! Matlab中Line对象编号: 474; Ansys中line编号474 
l,312,373 ! Matlab中Line对象编号: 475; Ansys中line编号475 
l,313,372 ! Matlab中Line对象编号: 476; Ansys中line编号476 
l,314,371 ! Matlab中Line对象编号: 477; Ansys中line编号477 
l,315,370 ! Matlab中Line对象编号: 478; Ansys中line编号478 
l,316,369 ! Matlab中Line对象编号: 479; Ansys中line编号479 
l,317,368 ! Matlab中Line对象编号: 480; Ansys中line编号480 
l,318,367 ! Matlab中Line对象编号: 481; Ansys中line编号481 
l,319,366 ! Matlab中Line对象编号: 482; Ansys中line编号482 
l,320,365 ! Matlab中Line对象编号: 483; Ansys中line编号483 
l,321,364 ! Matlab中Line对象编号: 484; Ansys中line编号484 
lsel,all 
cmsel,u,l_selected 
cm,Line_StayedCable_6,line 
lsel,all 
cm,l_selected,line 
allsel 

! StayedCable_7 
l,322,378 ! Matlab中Line对象编号: 485; Ansys中line编号485 
l,323,379 ! Matlab中Line对象编号: 486; Ansys中line编号486 
l,324,380 ! Matlab中Line对象编号: 487; Ansys中line编号487 
l,325,381 ! Matlab中Line对象编号: 488; Ansys中line编号488 
l,326,382 ! Matlab中Line对象编号: 489; Ansys中line编号489 
l,327,383 ! Matlab中Line对象编号: 490; Ansys中line编号490 
l,328,384 ! Matlab中Line对象编号: 491; Ansys中line编号491 
l,329,385 ! Matlab中Line对象编号: 492; Ansys中line编号492 
l,330,386 ! Matlab中Line对象编号: 493; Ansys中line编号493 
l,331,387 ! Matlab中Line对象编号: 494; Ansys中line编号494 
l,332,388 ! Matlab中Line对象编号: 495; Ansys中line编号495 
l,333,389 ! Matlab中Line对象编号: 496; Ansys中line编号496 
l,334,390 ! Matlab中Line对象编号: 497; Ansys中line编号497 
l,335,391 ! Matlab中Line对象编号: 498; Ansys中line编号498 
lsel,all 
cmsel,u,l_selected 
cm,Line_StayedCable_7,line 
lsel,all 
cm,l_selected,line 
allsel 

! StayedCable_8 
l,336,392 ! Matlab中Line对象编号: 499; Ansys中line编号499 
l,337,393 ! Matlab中Line对象编号: 500; Ansys中line编号500 
l,338,394 ! Matlab中Line对象编号: 501; Ansys中line编号501 
l,339,395 ! Matlab中Line对象编号: 502; Ansys中line编号502 
l,340,396 ! Matlab中Line对象编号: 503; Ansys中line编号503 
l,341,397 ! Matlab中Line对象编号: 504; Ansys中line编号504 
l,342,398 ! Matlab中Line对象编号: 505; Ansys中line编号505 
l,343,399 ! Matlab中Line对象编号: 506; Ansys中line编号506 
l,344,400 ! Matlab中Line对象编号: 507; Ansys中line编号507 
l,345,401 ! Matlab中Line对象编号: 508; Ansys中line编号508 
l,346,402 ! Matlab中Line对象编号: 509; Ansys中line编号509 
l,347,403 ! Matlab中Line对象编号: 510; Ansys中line编号510 
l,348,404 ! Matlab中Line对象编号: 511; Ansys中line编号511 
l,349,405 ! Matlab中Line对象编号: 512; Ansys中line编号512 
lsel,all 
cmsel,u,l_selected 
cm,Line_StayedCable_8,line 
lsel,all 
cm,l_selected,line 
allsel 

! Cable_1 
l,406,407 ! Matlab中Line对象编号: 513; Ansys中line编号513 
l,407,408 ! Matlab中Line对象编号: 514; Ansys中line编号514 
l,408,409 ! Matlab中Line对象编号: 515; Ansys中line编号515 
l,409,410 ! Matlab中Line对象编号: 516; Ansys中line编号516 
l,410,411 ! Matlab中Line对象编号: 517; Ansys中line编号517 
l,411,412 ! Matlab中Line对象编号: 518; Ansys中line编号518 
l,412,413 ! Matlab中Line对象编号: 519; Ansys中line编号519 
l,413,414 ! Matlab中Line对象编号: 520; Ansys中line编号520 
l,414,415 ! Matlab中Line对象编号: 521; Ansys中line编号521 
l,415,416 ! Matlab中Line对象编号: 522; Ansys中line编号522 
l,416,417 ! Matlab中Line对象编号: 523; Ansys中line编号523 
l,417,418 ! Matlab中Line对象编号: 524; Ansys中line编号524 
l,418,419 ! Matlab中Line对象编号: 525; Ansys中line编号525 
l,419,420 ! Matlab中Line对象编号: 526; Ansys中line编号526 
l,420,421 ! Matlab中Line对象编号: 527; Ansys中line编号527 
l,421,422 ! Matlab中Line对象编号: 528; Ansys中line编号528 
l,422,423 ! Matlab中Line对象编号: 529; Ansys中line编号529 
l,423,424 ! Matlab中Line对象编号: 530; Ansys中line编号530 
l,424,425 ! Matlab中Line对象编号: 531; Ansys中line编号531 
l,425,426 ! Matlab中Line对象编号: 532; Ansys中line编号532 
l,426,427 ! Matlab中Line对象编号: 533; Ansys中line编号533 
l,427,428 ! Matlab中Line对象编号: 534; Ansys中line编号534 
l,428,429 ! Matlab中Line对象编号: 535; Ansys中line编号535 
l,429,430 ! Matlab中Line对象编号: 536; Ansys中line编号536 
l,430,431 ! Matlab中Line对象编号: 537; Ansys中line编号537 
l,431,432 ! Matlab中Line对象编号: 538; Ansys中line编号538 
l,432,433 ! Matlab中Line对象编号: 539; Ansys中line编号539 
l,433,434 ! Matlab中Line对象编号: 540; Ansys中line编号540 
l,434,435 ! Matlab中Line对象编号: 541; Ansys中line编号541 
l,435,436 ! Matlab中Line对象编号: 542; Ansys中line编号542 
l,436,437 ! Matlab中Line对象编号: 543; Ansys中line编号543 
l,437,438 ! Matlab中Line对象编号: 544; Ansys中line编号544 
l,438,439 ! Matlab中Line对象编号: 545; Ansys中line编号545 
l,439,440 ! Matlab中Line对象编号: 546; Ansys中line编号546 
l,440,441 ! Matlab中Line对象编号: 547; Ansys中line编号547 
l,441,442 ! Matlab中Line对象编号: 548; Ansys中line编号548 
l,442,443 ! Matlab中Line对象编号: 549; Ansys中line编号549 
l,443,444 ! Matlab中Line对象编号: 550; Ansys中line编号550 
l,444,445 ! Matlab中Line对象编号: 551; Ansys中line编号551 
l,445,446 ! Matlab中Line对象编号: 552; Ansys中line编号552 
l,446,447 ! Matlab中Line对象编号: 553; Ansys中line编号553 
l,447,448 ! Matlab中Line对象编号: 554; Ansys中line编号554 
l,448,449 ! Matlab中Line对象编号: 555; Ansys中line编号555 
l,449,450 ! Matlab中Line对象编号: 556; Ansys中line编号556 
l,450,451 ! Matlab中Line对象编号: 557; Ansys中line编号557 
l,451,452 ! Matlab中Line对象编号: 558; Ansys中line编号558 
l,452,453 ! Matlab中Line对象编号: 559; Ansys中line编号559 
l,453,454 ! Matlab中Line对象编号: 560; Ansys中line编号560 
l,454,455 ! Matlab中Line对象编号: 561; Ansys中line编号561 
l,455,456 ! Matlab中Line对象编号: 562; Ansys中line编号562 
l,456,457 ! Matlab中Line对象编号: 563; Ansys中line编号563 
l,457,458 ! Matlab中Line对象编号: 564; Ansys中line编号564 
l,458,459 ! Matlab中Line对象编号: 565; Ansys中line编号565 
l,459,460 ! Matlab中Line对象编号: 566; Ansys中line编号566 
l,460,461 ! Matlab中Line对象编号: 567; Ansys中line编号567 
l,461,462 ! Matlab中Line对象编号: 568; Ansys中line编号568 
l,462,463 ! Matlab中Line对象编号: 569; Ansys中line编号569 
l,463,464 ! Matlab中Line对象编号: 570; Ansys中line编号570 
l,464,465 ! Matlab中Line对象编号: 571; Ansys中line编号571 
l,465,466 ! Matlab中Line对象编号: 572; Ansys中line编号572 
l,466,467 ! Matlab中Line对象编号: 573; Ansys中line编号573 
l,467,468 ! Matlab中Line对象编号: 574; Ansys中line编号574 
l,468,469 ! Matlab中Line对象编号: 575; Ansys中line编号575 
l,469,470 ! Matlab中Line对象编号: 576; Ansys中line编号576 
l,470,471 ! Matlab中Line对象编号: 577; Ansys中line编号577 
l,471,472 ! Matlab中Line对象编号: 578; Ansys中line编号578 
l,472,473 ! Matlab中Line对象编号: 579; Ansys中line编号579 
l,473,474 ! Matlab中Line对象编号: 580; Ansys中line编号580 
l,474,475 ! Matlab中Line对象编号: 581; Ansys中line编号581 
l,475,476 ! Matlab中Line对象编号: 582; Ansys中line编号582 
l,476,477 ! Matlab中Line对象编号: 583; Ansys中line编号583 
l,477,478 ! Matlab中Line对象编号: 584; Ansys中line编号584 
l,478,479 ! Matlab中Line对象编号: 585; Ansys中line编号585 
l,479,480 ! Matlab中Line对象编号: 586; Ansys中line编号586 
l,480,481 ! Matlab中Line对象编号: 587; Ansys中line编号587 
l,481,482 ! Matlab中Line对象编号: 588; Ansys中line编号588 
l,482,483 ! Matlab中Line对象编号: 589; Ansys中line编号589 
l,483,484 ! Matlab中Line对象编号: 590; Ansys中line编号590 
l,484,485 ! Matlab中Line对象编号: 591; Ansys中line编号591 
l,485,486 ! Matlab中Line对象编号: 592; Ansys中line编号592 
l,486,487 ! Matlab中Line对象编号: 593; Ansys中line编号593 
l,487,488 ! Matlab中Line对象编号: 594; Ansys中line编号594 
l,488,489 ! Matlab中Line对象编号: 595; Ansys中line编号595 
l,489,490 ! Matlab中Line对象编号: 596; Ansys中line编号596 
l,490,491 ! Matlab中Line对象编号: 597; Ansys中line编号597 
l,491,492 ! Matlab中Line对象编号: 598; Ansys中line编号598 
l,492,493 ! Matlab中Line对象编号: 599; Ansys中line编号599 
l,493,494 ! Matlab中Line对象编号: 600; Ansys中line编号600 
l,494,495 ! Matlab中Line对象编号: 601; Ansys中line编号601 
l,495,496 ! Matlab中Line对象编号: 602; Ansys中line编号602 
l,496,497 ! Matlab中Line对象编号: 603; Ansys中line编号603 
l,497,498 ! Matlab中Line对象编号: 604; Ansys中line编号604 
lsel,all 
cmsel,u,l_selected 
cm,Line_Cable_1,line 
lsel,all 
cm,l_selected,line 
allsel 

! Cable_2 
l,499,500 ! Matlab中Line对象编号: 605; Ansys中line编号605 
l,500,501 ! Matlab中Line对象编号: 606; Ansys中line编号606 
l,501,502 ! Matlab中Line对象编号: 607; Ansys中line编号607 
l,502,503 ! Matlab中Line对象编号: 608; Ansys中line编号608 
l,503,504 ! Matlab中Line对象编号: 609; Ansys中line编号609 
l,504,505 ! Matlab中Line对象编号: 610; Ansys中line编号610 
l,505,506 ! Matlab中Line对象编号: 611; Ansys中line编号611 
l,506,507 ! Matlab中Line对象编号: 612; Ansys中line编号612 
l,507,508 ! Matlab中Line对象编号: 613; Ansys中line编号613 
l,508,509 ! Matlab中Line对象编号: 614; Ansys中line编号614 
l,509,510 ! Matlab中Line对象编号: 615; Ansys中line编号615 
l,510,511 ! Matlab中Line对象编号: 616; Ansys中line编号616 
l,511,512 ! Matlab中Line对象编号: 617; Ansys中line编号617 
l,512,513 ! Matlab中Line对象编号: 618; Ansys中line编号618 
l,513,514 ! Matlab中Line对象编号: 619; Ansys中line编号619 
l,514,515 ! Matlab中Line对象编号: 620; Ansys中line编号620 
l,515,516 ! Matlab中Line对象编号: 621; Ansys中line编号621 
l,516,517 ! Matlab中Line对象编号: 622; Ansys中line编号622 
l,517,518 ! Matlab中Line对象编号: 623; Ansys中line编号623 
l,518,519 ! Matlab中Line对象编号: 624; Ansys中line编号624 
l,519,520 ! Matlab中Line对象编号: 625; Ansys中line编号625 
l,520,521 ! Matlab中Line对象编号: 626; Ansys中line编号626 
l,521,522 ! Matlab中Line对象编号: 627; Ansys中line编号627 
l,522,523 ! Matlab中Line对象编号: 628; Ansys中line编号628 
l,523,524 ! Matlab中Line对象编号: 629; Ansys中line编号629 
l,524,525 ! Matlab中Line对象编号: 630; Ansys中line编号630 
l,525,526 ! Matlab中Line对象编号: 631; Ansys中line编号631 
l,526,527 ! Matlab中Line对象编号: 632; Ansys中line编号632 
l,527,528 ! Matlab中Line对象编号: 633; Ansys中line编号633 
l,528,529 ! Matlab中Line对象编号: 634; Ansys中line编号634 
l,529,530 ! Matlab中Line对象编号: 635; Ansys中line编号635 
l,530,531 ! Matlab中Line对象编号: 636; Ansys中line编号636 
l,531,532 ! Matlab中Line对象编号: 637; Ansys中line编号637 
l,532,533 ! Matlab中Line对象编号: 638; Ansys中line编号638 
l,533,534 ! Matlab中Line对象编号: 639; Ansys中line编号639 
l,534,535 ! Matlab中Line对象编号: 640; Ansys中line编号640 
l,535,536 ! Matlab中Line对象编号: 641; Ansys中line编号641 
l,536,537 ! Matlab中Line对象编号: 642; Ansys中line编号642 
l,537,538 ! Matlab中Line对象编号: 643; Ansys中line编号643 
l,538,539 ! Matlab中Line对象编号: 644; Ansys中line编号644 
l,539,540 ! Matlab中Line对象编号: 645; Ansys中line编号645 
l,540,541 ! Matlab中Line对象编号: 646; Ansys中line编号646 
l,541,542 ! Matlab中Line对象编号: 647; Ansys中line编号647 
l,542,543 ! Matlab中Line对象编号: 648; Ansys中line编号648 
l,543,544 ! Matlab中Line对象编号: 649; Ansys中line编号649 
l,544,545 ! Matlab中Line对象编号: 650; Ansys中line编号650 
l,545,546 ! Matlab中Line对象编号: 651; Ansys中line编号651 
l,546,547 ! Matlab中Line对象编号: 652; Ansys中line编号652 
l,547,548 ! Matlab中Line对象编号: 653; Ansys中line编号653 
l,548,549 ! Matlab中Line对象编号: 654; Ansys中line编号654 
l,549,550 ! Matlab中Line对象编号: 655; Ansys中line编号655 
l,550,551 ! Matlab中Line对象编号: 656; Ansys中line编号656 
l,551,552 ! Matlab中Line对象编号: 657; Ansys中line编号657 
l,552,553 ! Matlab中Line对象编号: 658; Ansys中line编号658 
l,553,554 ! Matlab中Line对象编号: 659; Ansys中line编号659 
l,554,555 ! Matlab中Line对象编号: 660; Ansys中line编号660 
l,555,556 ! Matlab中Line对象编号: 661; Ansys中line编号661 
l,556,557 ! Matlab中Line对象编号: 662; Ansys中line编号662 
l,557,558 ! Matlab中Line对象编号: 663; Ansys中line编号663 
l,558,559 ! Matlab中Line对象编号: 664; Ansys中line编号664 
l,559,560 ! Matlab中Line对象编号: 665; Ansys中line编号665 
l,560,561 ! Matlab中Line对象编号: 666; Ansys中line编号666 
l,561,562 ! Matlab中Line对象编号: 667; Ansys中line编号667 
l,562,563 ! Matlab中Line对象编号: 668; Ansys中line编号668 
l,563,564 ! Matlab中Line对象编号: 669; Ansys中line编号669 
l,564,565 ! Matlab中Line对象编号: 670; Ansys中line编号670 
l,565,566 ! Matlab中Line对象编号: 671; Ansys中line编号671 
l,566,567 ! Matlab中Line对象编号: 672; Ansys中line编号672 
l,567,568 ! Matlab中Line对象编号: 673; Ansys中line编号673 
l,568,569 ! Matlab中Line对象编号: 674; Ansys中line编号674 
l,569,570 ! Matlab中Line对象编号: 675; Ansys中line编号675 
l,570,571 ! Matlab中Line对象编号: 676; Ansys中line编号676 
l,571,572 ! Matlab中Line对象编号: 677; Ansys中line编号677 
l,572,573 ! Matlab中Line对象编号: 678; Ansys中line编号678 
l,573,574 ! Matlab中Line对象编号: 679; Ansys中line编号679 
l,574,575 ! Matlab中Line对象编号: 680; Ansys中line编号680 
l,575,576 ! Matlab中Line对象编号: 681; Ansys中line编号681 
l,576,577 ! Matlab中Line对象编号: 682; Ansys中line编号682 
l,577,578 ! Matlab中Line对象编号: 683; Ansys中line编号683 
l,578,579 ! Matlab中Line对象编号: 684; Ansys中line编号684 
l,579,580 ! Matlab中Line对象编号: 685; Ansys中line编号685 
l,580,581 ! Matlab中Line对象编号: 686; Ansys中line编号686 
l,581,582 ! Matlab中Line对象编号: 687; Ansys中line编号687 
l,582,583 ! Matlab中Line对象编号: 688; Ansys中line编号688 
l,583,584 ! Matlab中Line对象编号: 689; Ansys中line编号689 
l,584,585 ! Matlab中Line对象编号: 690; Ansys中line编号690 
l,585,586 ! Matlab中Line对象编号: 691; Ansys中line编号691 
l,586,587 ! Matlab中Line对象编号: 692; Ansys中line编号692 
l,587,588 ! Matlab中Line对象编号: 693; Ansys中line编号693 
l,588,589 ! Matlab中Line对象编号: 694; Ansys中line编号694 
l,589,590 ! Matlab中Line对象编号: 695; Ansys中line编号695 
l,590,591 ! Matlab中Line对象编号: 696; Ansys中line编号696 
lsel,all 
cmsel,u,l_selected 
cm,Line_Cable_2,line 
lsel,all 
cm,l_selected,line 
allsel 

! Cable_3 
l,592,593 ! Matlab中Line对象编号: 697; Ansys中line编号697 
l,593,594 ! Matlab中Line对象编号: 698; Ansys中line编号698 
l,594,595 ! Matlab中Line对象编号: 699; Ansys中line编号699 
l,595,596 ! Matlab中Line对象编号: 700; Ansys中line编号700 
l,596,597 ! Matlab中Line对象编号: 701; Ansys中line编号701 
l,597,598 ! Matlab中Line对象编号: 702; Ansys中line编号702 
l,598,599 ! Matlab中Line对象编号: 703; Ansys中line编号703 
l,599,600 ! Matlab中Line对象编号: 704; Ansys中line编号704 
l,600,601 ! Matlab中Line对象编号: 705; Ansys中line编号705 
l,601,602 ! Matlab中Line对象编号: 706; Ansys中line编号706 
l,602,603 ! Matlab中Line对象编号: 707; Ansys中line编号707 
l,603,604 ! Matlab中Line对象编号: 708; Ansys中line编号708 
l,604,605 ! Matlab中Line对象编号: 709; Ansys中line编号709 
l,605,606 ! Matlab中Line对象编号: 710; Ansys中line编号710 
l,606,607 ! Matlab中Line对象编号: 711; Ansys中line编号711 
l,607,608 ! Matlab中Line对象编号: 712; Ansys中line编号712 
l,608,609 ! Matlab中Line对象编号: 713; Ansys中line编号713 
l,609,610 ! Matlab中Line对象编号: 714; Ansys中line编号714 
l,610,611 ! Matlab中Line对象编号: 715; Ansys中line编号715 
l,611,612 ! Matlab中Line对象编号: 716; Ansys中line编号716 
l,612,613 ! Matlab中Line对象编号: 717; Ansys中line编号717 
l,613,406 ! Matlab中Line对象编号: 718; Ansys中line编号718 
lsel,all 
cmsel,u,l_selected 
cm,Line_Cable_3,line 
lsel,all 
cm,l_selected,line 
allsel 

! Cable_4 
l,615,616 ! Matlab中Line对象编号: 719; Ansys中line编号719 
l,616,617 ! Matlab中Line对象编号: 720; Ansys中line编号720 
l,617,618 ! Matlab中Line对象编号: 721; Ansys中line编号721 
l,618,619 ! Matlab中Line对象编号: 722; Ansys中line编号722 
l,619,620 ! Matlab中Line对象编号: 723; Ansys中line编号723 
l,620,621 ! Matlab中Line对象编号: 724; Ansys中line编号724 
l,621,622 ! Matlab中Line对象编号: 725; Ansys中line编号725 
l,622,623 ! Matlab中Line对象编号: 726; Ansys中line编号726 
l,623,624 ! Matlab中Line对象编号: 727; Ansys中line编号727 
l,624,625 ! Matlab中Line对象编号: 728; Ansys中line编号728 
l,625,626 ! Matlab中Line对象编号: 729; Ansys中line编号729 
l,626,627 ! Matlab中Line对象编号: 730; Ansys中line编号730 
l,627,628 ! Matlab中Line对象编号: 731; Ansys中line编号731 
l,628,629 ! Matlab中Line对象编号: 732; Ansys中line编号732 
l,629,630 ! Matlab中Line对象编号: 733; Ansys中line编号733 
l,630,631 ! Matlab中Line对象编号: 734; Ansys中line编号734 
l,631,632 ! Matlab中Line对象编号: 735; Ansys中line编号735 
l,632,633 ! Matlab中Line对象编号: 736; Ansys中line编号736 
l,633,634 ! Matlab中Line对象编号: 737; Ansys中line编号737 
l,634,635 ! Matlab中Line对象编号: 738; Ansys中line编号738 
l,635,636 ! Matlab中Line对象编号: 739; Ansys中line编号739 
l,636,499 ! Matlab中Line对象编号: 740; Ansys中line编号740 
lsel,all 
cmsel,u,l_selected 
cm,Line_Cable_4,line 
lsel,all 
cm,l_selected,line 
allsel 

! Cable_5 
l,498,639 ! Matlab中Line对象编号: 741; Ansys中line编号741 
l,639,640 ! Matlab中Line对象编号: 742; Ansys中line编号742 
l,640,641 ! Matlab中Line对象编号: 743; Ansys中line编号743 
l,641,642 ! Matlab中Line对象编号: 744; Ansys中line编号744 
l,642,643 ! Matlab中Line对象编号: 745; Ansys中line编号745 
l,643,644 ! Matlab中Line对象编号: 746; Ansys中line编号746 
l,644,645 ! Matlab中Line对象编号: 747; Ansys中line编号747 
l,645,646 ! Matlab中Line对象编号: 748; Ansys中line编号748 
l,646,647 ! Matlab中Line对象编号: 749; Ansys中line编号749 
l,647,648 ! Matlab中Line对象编号: 750; Ansys中line编号750 
l,648,649 ! Matlab中Line对象编号: 751; Ansys中line编号751 
l,649,650 ! Matlab中Line对象编号: 752; Ansys中line编号752 
l,650,651 ! Matlab中Line对象编号: 753; Ansys中line编号753 
l,651,652 ! Matlab中Line对象编号: 754; Ansys中line编号754 
l,652,653 ! Matlab中Line对象编号: 755; Ansys中line编号755 
l,653,654 ! Matlab中Line对象编号: 756; Ansys中line编号756 
l,654,655 ! Matlab中Line对象编号: 757; Ansys中line编号757 
l,655,656 ! Matlab中Line对象编号: 758; Ansys中line编号758 
l,656,657 ! Matlab中Line对象编号: 759; Ansys中line编号759 
l,657,658 ! Matlab中Line对象编号: 760; Ansys中line编号760 
l,658,659 ! Matlab中Line对象编号: 761; Ansys中line编号761 
l,659,660 ! Matlab中Line对象编号: 762; Ansys中line编号762 
lsel,all 
cmsel,u,l_selected 
cm,Line_Cable_5,line 
lsel,all 
cm,l_selected,line 
allsel 

! Cable_6 
l,591,662 ! Matlab中Line对象编号: 763; Ansys中line编号763 
l,662,663 ! Matlab中Line对象编号: 764; Ansys中line编号764 
l,663,664 ! Matlab中Line对象编号: 765; Ansys中line编号765 
l,664,665 ! Matlab中Line对象编号: 766; Ansys中line编号766 
l,665,666 ! Matlab中Line对象编号: 767; Ansys中line编号767 
l,666,667 ! Matlab中Line对象编号: 768; Ansys中line编号768 
l,667,668 ! Matlab中Line对象编号: 769; Ansys中line编号769 
l,668,669 ! Matlab中Line对象编号: 770; Ansys中line编号770 
l,669,670 ! Matlab中Line对象编号: 771; Ansys中line编号771 
l,670,671 ! Matlab中Line对象编号: 772; Ansys中line编号772 
l,671,672 ! Matlab中Line对象编号: 773; Ansys中line编号773 
l,672,673 ! Matlab中Line对象编号: 774; Ansys中line编号774 
l,673,674 ! Matlab中Line对象编号: 775; Ansys中line编号775 
l,674,675 ! Matlab中Line对象编号: 776; Ansys中line编号776 
l,675,676 ! Matlab中Line对象编号: 777; Ansys中line编号777 
l,676,677 ! Matlab中Line对象编号: 778; Ansys中line编号778 
l,677,678 ! Matlab中Line对象编号: 779; Ansys中line编号779 
l,678,679 ! Matlab中Line对象编号: 780; Ansys中line编号780 
l,679,680 ! Matlab中Line对象编号: 781; Ansys中line编号781 
l,680,681 ! Matlab中Line对象编号: 782; Ansys中line编号782 
l,681,682 ! Matlab中Line对象编号: 783; Ansys中line编号783 
l,682,683 ! Matlab中Line对象编号: 784; Ansys中line编号784 
lsel,all 
cmsel,u,l_selected 
cm,Line_Cable_6,line 
lsel,all 
cm,l_selected,line 
allsel 

! Hanger_1 
l,194,431 ! Matlab中Line对象编号: 785; Ansys中line编号785 
l,195,433 ! Matlab中Line对象编号: 786; Ansys中line编号786 
l,196,435 ! Matlab中Line对象编号: 787; Ansys中line编号787 
l,197,437 ! Matlab中Line对象编号: 788; Ansys中line编号788 
l,198,439 ! Matlab中Line对象编号: 789; Ansys中line编号789 
l,199,441 ! Matlab中Line对象编号: 790; Ansys中line编号790 
l,200,443 ! Matlab中Line对象编号: 791; Ansys中line编号791 
l,201,445 ! Matlab中Line对象编号: 792; Ansys中line编号792 
l,202,447 ! Matlab中Line对象编号: 793; Ansys中line编号793 
l,203,449 ! Matlab中Line对象编号: 794; Ansys中line编号794 
l,204,451 ! Matlab中Line对象编号: 795; Ansys中line编号795 
l,205,453 ! Matlab中Line对象编号: 796; Ansys中line编号796 
l,206,455 ! Matlab中Line对象编号: 797; Ansys中line编号797 
l,207,457 ! Matlab中Line对象编号: 798; Ansys中line编号798 
l,208,459 ! Matlab中Line对象编号: 799; Ansys中line编号799 
l,209,461 ! Matlab中Line对象编号: 800; Ansys中line编号800 
l,210,463 ! Matlab中Line对象编号: 801; Ansys中line编号801 
l,211,465 ! Matlab中Line对象编号: 802; Ansys中line编号802 
l,212,467 ! Matlab中Line对象编号: 803; Ansys中line编号803 
l,213,469 ! Matlab中Line对象编号: 804; Ansys中line编号804 
l,214,471 ! Matlab中Line对象编号: 805; Ansys中line编号805 
l,215,473 ! Matlab中Line对象编号: 806; Ansys中line编号806 
lsel,all 
cmsel,u,l_selected 
cm,Line_Hanger_1,line 
lsel,all 
cm,l_selected,line 
allsel 

! Hanger_2 
l,216,524 ! Matlab中Line对象编号: 807; Ansys中line编号807 
l,217,526 ! Matlab中Line对象编号: 808; Ansys中line编号808 
l,218,528 ! Matlab中Line对象编号: 809; Ansys中line编号809 
l,219,530 ! Matlab中Line对象编号: 810; Ansys中line编号810 
l,220,532 ! Matlab中Line对象编号: 811; Ansys中line编号811 
l,221,534 ! Matlab中Line对象编号: 812; Ansys中line编号812 
l,222,536 ! Matlab中Line对象编号: 813; Ansys中line编号813 
l,223,538 ! Matlab中Line对象编号: 814; Ansys中line编号814 
l,224,540 ! Matlab中Line对象编号: 815; Ansys中line编号815 
l,225,542 ! Matlab中Line对象编号: 816; Ansys中line编号816 
l,226,544 ! Matlab中Line对象编号: 817; Ansys中line编号817 
l,227,546 ! Matlab中Line对象编号: 818; Ansys中line编号818 
l,228,548 ! Matlab中Line对象编号: 819; Ansys中line编号819 
l,229,550 ! Matlab中Line对象编号: 820; Ansys中line编号820 
l,230,552 ! Matlab中Line对象编号: 821; Ansys中line编号821 
l,231,554 ! Matlab中Line对象编号: 822; Ansys中line编号822 
l,232,556 ! Matlab中Line对象编号: 823; Ansys中line编号823 
l,233,558 ! Matlab中Line对象编号: 824; Ansys中line编号824 
l,234,560 ! Matlab中Line对象编号: 825; Ansys中line编号825 
l,235,562 ! Matlab中Line对象编号: 826; Ansys中line编号826 
l,236,564 ! Matlab中Line对象编号: 827; Ansys中line编号827 
l,237,566 ! Matlab中Line对象编号: 828; Ansys中line编号828 
lsel,all 
cmsel,u,l_selected 
cm,Line_Hanger_2,line 
lsel,all 
cm,l_selected,line 
allsel 

