function output_str = OutputToAnsys(obj,sec_num)
    output_str = sprintf(['\n' ...
                         'sectype,%d,Beam,CSolid \n' ...
                         'secoffset,cent \n' ...
                         'secdata,%E \n'],sec_num,obj.Radius);
end