function data = getDisplacement(obj,num_MonitoredNodes)
    arguments
        obj
        num_MonitoredNodes
    end
    OutputMethod_clone = obj.clone();
    % 让ANSYS导出数据的宏文件
    count_points = length(num_MonitoredNodes);
    str_num_nodes = OutputMethod_clone.outputArray(num_MonitoredNodes,'num_nodes');
    output_str = ['/post1',newline,...
                sprintf('resume,%s,db',strcat(obj.JobName,'Result')),newline,...
                'set,1,last',newline,newline,...
                sprintf('count_nodes = %d',count_points),newline,...
                str_num_nodes,newline,...
                '*dim,Displacement_x,array,count_nodes',newline,...
                '*dim,Displacement_y,array,count_nodes',newline,...
                '*dim,Displacement_z,array,count_nodes',newline,newline,...
                '! 提取node上的位移值',newline,...
                'allsel',newline,...
                '*do,i,1,count_nodes,1',newline,...
                '    *get,Displacement_x(i),Node,num_nodes(i),U,x',newline,...
                '    *get,Displacement_y(i),Node,num_nodes(i),U,y',newline,...
                '    *get,Displacement_z(i),Node,num_nodes(i),U,z',newline,...
                '*enddo',newline,...
                'allsel',newline,newline,...
                '! 导出数据',newline,...
                '*cfopen,Displacement,txt',newline,...
                '*vwrite,Displacement_x(1),Displacement_y(1),Displacement_z(1)',newline,...
                '(3E20.8)',newline,...
                '*cfclos',newline];
    OutputMethod_clone.outputAPDL(output_str,'getDisplacement.mac','w')

    % 修改OutputMethod属性值，并运行宏文件
    OutputMethod_clone.MacFilePath = fullfile(OutputMethod_clone.WorkPath,'getDisplacement.mac');
    OutputMethod_clone.ResultFilePath = fullfile(OutputMethod_clone.WorkPath,'getDisplacement.out');
    OutputMethod_clone.runMac("ComputingMode","Distributed")

    % 数据导入MATLAB
    dataFilePath = fullfile(OutputMethod_clone.WorkPath,'Displacement.txt');
    fileID = fopen(dataFilePath, 'r');
    data = readmatrix(dataFilePath);
    fclose(fileID);

    % 分解数据
    Ux = data(:,1)';
    Uy = data(:,2)';
    Uz = data(:,3)';

    % 将生成的结果文件更换文件夹
    dir_Result = fullfile(OutputMethod_clone.WorkPath,filesep,'Result_Displacement');
    if ~exist(dir_Result,'dir')
        mkdir(dir_Result)
    end
    movefile(fullfile(OutputMethod_clone.WorkPath,'Displacement.txt'),dir_Result)

    % 存储结果变量
    data = struct;
    data.num_nodes = num_MonitoredNodes;
    data.Ux = Ux;
    data.Uy = Uy;
    data.Uz = Uz;
    save(fullfile(dir_Result,'ResultData.mat'),"data")
end