function data = getDisplacementFromAnsys(obj,num_MonitoredNodes)
    arguments
        obj
        num_MonitoredNodes
    end
    OutputMethod_clone = obj.clone();
    % 让ANSYS导出数据的宏文件
    count_points = length(num_MonitoredNodes);
    str_num_nodes = OutputMethod_clone.outputArray(num_MonitoredNodes,'num_nodes');
    output_str = ['/post1',newline,...
                sprintf('resume,%s,db',strcat(obj.JobName,'Result')),newline,...
                'set,1,last',newline,newline,...
                sprintf('count_nodes = %d',count_points),newline,...
                str_num_nodes,newline,...
                '*dim,Displacement_Ux,array,count_nodes',newline,...
                '*dim,Displacement_Uy,array,count_nodes',newline,...
                '*dim,Displacement_Uz,array,count_nodes',newline,...
                '*dim,Displacement_Rotx,array,count_nodes',newline,...
                '*dim,Displacement_Roty,array,count_nodes',newline,...
                '*dim,Displacement_Rotz,array,count_nodes',newline,...
                newline,...
                '! 提取node上的位移值',newline,...
                'allsel',newline,...
                '*do,i,1,count_nodes,1',newline,...
                '    *get,Displacement_Ux(i),Node,num_nodes(i),U,x',newline,...
                '    *get,Displacement_Uy(i),Node,num_nodes(i),U,y',newline,...
                '    *get,Displacement_Uz(i),Node,num_nodes(i),U,z',newline,...
                '    *get,Displacement_Rotx(i),Node,num_nodes(i),Rot,x',newline,...
                '    *get,Displacement_Roty(i),Node,num_nodes(i),Rot,y',newline,...
                '    *get,Displacement_Rotz(i),Node,num_nodes(i),Rot,z',newline,...
                '*enddo',newline,...
                'allsel',newline,newline,...
                '! 导出数据',newline,...
                '*cfopen,Displacement,txt',newline,...
                '*vwrite,Displacement_Ux(1),Displacement_Uy(1),Displacement_Uz(1),Displacement_Rotx(1),Displacement_Roty(1),Displacement_Rotz(1)',newline,...
                '(6E20.8)',newline,...
                '*cfclos',newline];
    OutputMethod_clone.outputAPDL(output_str,'getDisplacement.mac','w')

    % 修改OutputMethod属性值，并运行宏文件
    OutputMethod_clone.MacFilePath = fullfile(OutputMethod_clone.WorkPath,'getDisplacement.mac');
    OutputMethod_clone.ResultFilePath = fullfile(OutputMethod_clone.WorkPath,'getDisplacement.out');
    OutputMethod_clone.runMac("ComputingMode","Distributed")

    % 数据导入MATLAB
    dataFilePath = fullfile(OutputMethod_clone.WorkPath,'Displacement.txt');
    fileID = fopen(dataFilePath, 'r');
    data = readmatrix(dataFilePath);
    fclose(fileID);

    % 分解数据
    Ux = data(:,1)';
    Uy = data(:,2)';
    Uz = data(:,3)';
    Rotx = data(:,4)';
    Roty = data(:,5)';
    Rotz = data(:,6)';

    % 将生成的结果文件更换文件夹
    dir_Result = fullfile(OutputMethod_clone.WorkPath,filesep,'Result_Displacement');
    if ~exist(dir_Result,'dir')
        mkdir(dir_Result)
    end
    movefile(fullfile(OutputMethod_clone.WorkPath,'Displacement.txt'),dir_Result)

    % 存储结果变量
    data = struct;
    data.num_nodes = num_MonitoredNodes;
    data.Ux = Ux;
    data.Uy = Uy;
    data.Uz = Uz;
    data.Rotx = Rotx;
    data.Roty = Roty;
    data.Rotz = Rotz;
    save(fullfile(dir_Result,'ResultData.mat'),"data")
end