!塔梁耦合1 
ksel,s,kp,,353 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,194 $ nslk,s $ *get,Node2,node,,num,min
allsel 
cp,Next,Uy,Node1,Node2
cp,Next,Uz,Node1,Node2
cp,Next,Rotx,Node1,Node2
Node1 = $ Node2 =

!塔梁耦合2 
ksel,s,kp,,378 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,286 $ nslk,s $ *get,Node2,node,,num,min
allsel 
cp,Next,Uy,Node1,Node2
cp,Next,Uz,Node1,Node2
cp,Next,Rotx,Node1,Node2
Node1 = $ Node2 =

