! 单元名称：Beam188 
! 作用于以下Structure: Girder_1
et,9,Beam188


! 单元名称：Beam188 
! 作用于以下Structure: Girder_2, Girder_3
et,10,Beam188


! 单元名称：Beam188 
! 作用于以下Structure: Girder_4, Girder_5
et,11,Beam188


! 单元名称：Beam188 
! 作用于以下Structure: Tower_1, Tower_2
et,12,Beam188


! 单元名称：Beam188 
! 作用于以下Structure: RigidBeam_1, RigidBeam_2, RigidBeam_3, RigidBeam_4, RigidBeam_5, RigidBeam_6, RigidBeam_7, RigidBeam_8, RigidBeam_9, RigidBeam_10, RigidBeam_11, RigidBeam_12, RigidBeam_13, RigidBeam_14
et,13,Beam188


