lsel,none
cm,l_selected,line
numstr,line,1

! Girder_1 
l,194,195 ! Matlab中Line对象编号: 1; Ansys中line编号1 
l,195,196 ! Matlab中Line对象编号: 2; Ansys中line编号2 
l,196,197 ! Matlab中Line对象编号: 3; Ansys中line编号3 
l,197,198 ! Matlab中Line对象编号: 4; Ansys中line编号4 
l,198,199 ! Matlab中Line对象编号: 5; Ansys中line编号5 
l,199,200 ! Matlab中Line对象编号: 6; Ansys中line编号6 
l,200,201 ! Matlab中Line对象编号: 7; Ansys中line编号7 
l,201,202 ! Matlab中Line对象编号: 8; Ansys中line编号8 
l,202,203 ! Matlab中Line对象编号: 9; Ansys中line编号9 
l,203,204 ! Matlab中Line对象编号: 10; Ansys中line编号10 
l,204,205 ! Matlab中Line对象编号: 11; Ansys中line编号11 
l,205,206 ! Matlab中Line对象编号: 12; Ansys中line编号12 
l,206,207 ! Matlab中Line对象编号: 13; Ansys中line编号13 
l,207,208 ! Matlab中Line对象编号: 14; Ansys中line编号14 
l,208,209 ! Matlab中Line对象编号: 15; Ansys中line编号15 
l,209,210 ! Matlab中Line对象编号: 16; Ansys中line编号16 
l,210,211 ! Matlab中Line对象编号: 17; Ansys中line编号17 
l,211,212 ! Matlab中Line对象编号: 18; Ansys中line编号18 
l,212,213 ! Matlab中Line对象编号: 19; Ansys中line编号19 
l,213,214 ! Matlab中Line对象编号: 20; Ansys中line编号20 
l,214,215 ! Matlab中Line对象编号: 21; Ansys中line编号21 
l,215,216 ! Matlab中Line对象编号: 22; Ansys中line编号22 
l,216,217 ! Matlab中Line对象编号: 23; Ansys中line编号23 
l,217,218 ! Matlab中Line对象编号: 24; Ansys中line编号24 
l,218,219 ! Matlab中Line对象编号: 25; Ansys中line编号25 
l,219,220 ! Matlab中Line对象编号: 26; Ansys中line编号26 
l,220,221 ! Matlab中Line对象编号: 27; Ansys中line编号27 
l,221,222 ! Matlab中Line对象编号: 28; Ansys中line编号28 
l,222,223 ! Matlab中Line对象编号: 29; Ansys中line编号29 
l,223,224 ! Matlab中Line对象编号: 30; Ansys中line编号30 
l,224,225 ! Matlab中Line对象编号: 31; Ansys中line编号31 
l,225,226 ! Matlab中Line对象编号: 32; Ansys中line编号32 
l,226,227 ! Matlab中Line对象编号: 33; Ansys中line编号33 
l,227,228 ! Matlab中Line对象编号: 34; Ansys中line编号34 
l,228,229 ! Matlab中Line对象编号: 35; Ansys中line编号35 
l,229,230 ! Matlab中Line对象编号: 36; Ansys中line编号36 
l,230,231 ! Matlab中Line对象编号: 37; Ansys中line编号37 
l,231,232 ! Matlab中Line对象编号: 38; Ansys中line编号38 
l,232,233 ! Matlab中Line对象编号: 39; Ansys中line编号39 
l,233,234 ! Matlab中Line对象编号: 40; Ansys中line编号40 
l,234,235 ! Matlab中Line对象编号: 41; Ansys中line编号41 
l,235,236 ! Matlab中Line对象编号: 42; Ansys中line编号42 
l,236,237 ! Matlab中Line对象编号: 43; Ansys中line编号43 
l,237,238 ! Matlab中Line对象编号: 44; Ansys中line编号44 
l,238,239 ! Matlab中Line对象编号: 45; Ansys中line编号45 
l,239,240 ! Matlab中Line对象编号: 46; Ansys中line编号46 
l,240,241 ! Matlab中Line对象编号: 47; Ansys中line编号47 
l,241,242 ! Matlab中Line对象编号: 48; Ansys中line编号48 
l,242,243 ! Matlab中Line对象编号: 49; Ansys中line编号49 
l,243,244 ! Matlab中Line对象编号: 50; Ansys中line编号50 
l,244,245 ! Matlab中Line对象编号: 51; Ansys中line编号51 
l,245,246 ! Matlab中Line对象编号: 52; Ansys中line编号52 
l,246,247 ! Matlab中Line对象编号: 53; Ansys中line编号53 
l,247,248 ! Matlab中Line对象编号: 54; Ansys中line编号54 
l,248,249 ! Matlab中Line对象编号: 55; Ansys中line编号55 
l,249,250 ! Matlab中Line对象编号: 56; Ansys中line编号56 
l,250,251 ! Matlab中Line对象编号: 57; Ansys中line编号57 
l,251,252 ! Matlab中Line对象编号: 58; Ansys中line编号58 
l,252,253 ! Matlab中Line对象编号: 59; Ansys中line编号59 
l,253,254 ! Matlab中Line对象编号: 60; Ansys中line编号60 
l,254,255 ! Matlab中Line对象编号: 61; Ansys中line编号61 
l,255,256 ! Matlab中Line对象编号: 62; Ansys中line编号62 
l,256,257 ! Matlab中Line对象编号: 63; Ansys中line编号63 
l,257,258 ! Matlab中Line对象编号: 64; Ansys中line编号64 
l,258,259 ! Matlab中Line对象编号: 65; Ansys中line编号65 
l,259,260 ! Matlab中Line对象编号: 66; Ansys中line编号66 
l,260,261 ! Matlab中Line对象编号: 67; Ansys中line编号67 
l,261,262 ! Matlab中Line对象编号: 68; Ansys中line编号68 
l,262,263 ! Matlab中Line对象编号: 69; Ansys中line编号69 
l,263,264 ! Matlab中Line对象编号: 70; Ansys中line编号70 
l,264,265 ! Matlab中Line对象编号: 71; Ansys中line编号71 
l,265,266 ! Matlab中Line对象编号: 72; Ansys中line编号72 
l,266,267 ! Matlab中Line对象编号: 73; Ansys中line编号73 
l,267,268 ! Matlab中Line对象编号: 74; Ansys中line编号74 
l,268,269 ! Matlab中Line对象编号: 75; Ansys中line编号75 
l,269,270 ! Matlab中Line对象编号: 76; Ansys中line编号76 
l,270,271 ! Matlab中Line对象编号: 77; Ansys中line编号77 
l,271,272 ! Matlab中Line对象编号: 78; Ansys中line编号78 
l,272,273 ! Matlab中Line对象编号: 79; Ansys中line编号79 
l,273,274 ! Matlab中Line对象编号: 80; Ansys中line编号80 
l,274,275 ! Matlab中Line对象编号: 81; Ansys中line编号81 
l,275,276 ! Matlab中Line对象编号: 82; Ansys中line编号82 
l,276,277 ! Matlab中Line对象编号: 83; Ansys中line编号83 
l,277,278 ! Matlab中Line对象编号: 84; Ansys中line编号84 
l,278,279 ! Matlab中Line对象编号: 85; Ansys中line编号85 
l,279,280 ! Matlab中Line对象编号: 86; Ansys中line编号86 
l,280,281 ! Matlab中Line对象编号: 87; Ansys中line编号87 
l,281,282 ! Matlab中Line对象编号: 88; Ansys中line编号88 
l,282,283 ! Matlab中Line对象编号: 89; Ansys中line编号89 
l,283,284 ! Matlab中Line对象编号: 90; Ansys中line编号90 
l,284,285 ! Matlab中Line对象编号: 91; Ansys中line编号91 
l,285,286 ! Matlab中Line对象编号: 92; Ansys中line编号92 
lsel,all 
cmsel,u,l_selected 
cm,Line_Girder_1,line 
lsel,all 
cm,l_selected,line 
allsel 

! Girder_2 
l,287,288 ! Matlab中Line对象编号: 93; Ansys中line编号93 
l,288,289 ! Matlab中Line对象编号: 94; Ansys中line编号94 
l,289,290 ! Matlab中Line对象编号: 95; Ansys中line编号95 
l,290,291 ! Matlab中Line对象编号: 96; Ansys中line编号96 
l,291,292 ! Matlab中Line对象编号: 97; Ansys中line编号97 
l,292,293 ! Matlab中Line对象编号: 98; Ansys中line编号98 
l,293,294 ! Matlab中Line对象编号: 99; Ansys中line编号99 
l,294,295 ! Matlab中Line对象编号: 100; Ansys中line编号100 
l,295,296 ! Matlab中Line对象编号: 101; Ansys中line编号101 
l,296,297 ! Matlab中Line对象编号: 102; Ansys中line编号102 
l,297,298 ! Matlab中Line对象编号: 103; Ansys中line编号103 
l,298,299 ! Matlab中Line对象编号: 104; Ansys中line编号104 
l,299,300 ! Matlab中Line对象编号: 105; Ansys中line编号105 
l,300,301 ! Matlab中Line对象编号: 106; Ansys中line编号106 
l,301,302 ! Matlab中Line对象编号: 107; Ansys中line编号107 
l,302,303 ! Matlab中Line对象编号: 108; Ansys中line编号108 
l,303,304 ! Matlab中Line对象编号: 109; Ansys中line编号109 
l,304,305 ! Matlab中Line对象编号: 110; Ansys中line编号110 
l,305,306 ! Matlab中Line对象编号: 111; Ansys中line编号111 
l,306,307 ! Matlab中Line对象编号: 112; Ansys中line编号112 
l,307,194 ! Matlab中Line对象编号: 113; Ansys中line编号113 
lsel,all 
cmsel,u,l_selected 
cm,Line_Girder_2,line 
lsel,all 
cm,l_selected,line 
allsel 

! Girder_3 
l,286,310 ! Matlab中Line对象编号: 114; Ansys中line编号114 
l,310,311 ! Matlab中Line对象编号: 115; Ansys中line编号115 
l,311,312 ! Matlab中Line对象编号: 116; Ansys中line编号116 
l,312,313 ! Matlab中Line对象编号: 117; Ansys中line编号117 
l,313,314 ! Matlab中Line对象编号: 118; Ansys中line编号118 
l,314,315 ! Matlab中Line对象编号: 119; Ansys中line编号119 
l,315,316 ! Matlab中Line对象编号: 120; Ansys中line编号120 
l,316,317 ! Matlab中Line对象编号: 121; Ansys中line编号121 
l,317,318 ! Matlab中Line对象编号: 122; Ansys中line编号122 
l,318,319 ! Matlab中Line对象编号: 123; Ansys中line编号123 
l,319,320 ! Matlab中Line对象编号: 124; Ansys中line编号124 
l,320,321 ! Matlab中Line对象编号: 125; Ansys中line编号125 
l,321,322 ! Matlab中Line对象编号: 126; Ansys中line编号126 
l,322,323 ! Matlab中Line对象编号: 127; Ansys中line编号127 
l,323,324 ! Matlab中Line对象编号: 128; Ansys中line编号128 
l,324,325 ! Matlab中Line对象编号: 129; Ansys中line编号129 
l,325,326 ! Matlab中Line对象编号: 130; Ansys中line编号130 
l,326,327 ! Matlab中Line对象编号: 131; Ansys中line编号131 
l,327,328 ! Matlab中Line对象编号: 132; Ansys中line编号132 
l,328,329 ! Matlab中Line对象编号: 133; Ansys中line编号133 
l,329,330 ! Matlab中Line对象编号: 134; Ansys中line编号134 
lsel,all 
cmsel,u,l_selected 
cm,Line_Girder_3,line 
lsel,all 
cm,l_selected,line 
allsel 

! Girder_4 
l,331,332 ! Matlab中Line对象编号: 135; Ansys中line编号135 
l,332,287 ! Matlab中Line对象编号: 136; Ansys中line编号136 
lsel,all 
cmsel,u,l_selected 
cm,Line_Girder_4,line 
lsel,all 
cm,l_selected,line 
allsel 

! Girder_5 
l,330,335 ! Matlab中Line对象编号: 137; Ansys中line编号137 
l,335,336 ! Matlab中Line对象编号: 138; Ansys中line编号138 
lsel,all 
cmsel,u,l_selected 
cm,Line_Girder_5,line 
lsel,all 
cm,l_selected,line 
allsel 

! Tower_1 
l,337,338 ! Matlab中Line对象编号: 139; Ansys中line编号139 
l,338,339 ! Matlab中Line对象编号: 140; Ansys中line编号140 
l,339,346 ! Matlab中Line对象编号: 141; Ansys中line编号141 
l,340,341 ! Matlab中Line对象编号: 142; Ansys中line编号142 
l,341,342 ! Matlab中Line对象编号: 143; Ansys中line编号143 
l,342,337 ! Matlab中Line对象编号: 144; Ansys中line编号144 
l,343,345 ! Matlab中Line对象编号: 145; Ansys中line编号145 
l,344,345 ! Matlab中Line对象编号: 146; Ansys中line编号146 
l,345,360 ! Matlab中Line对象编号: 147; Ansys中line编号147 
l,346,347 ! Matlab中Line对象编号: 148; Ansys中line编号148 
l,347,344 ! Matlab中Line对象编号: 149; Ansys中line编号149 
l,347,343 ! Matlab中Line对象编号: 150; Ansys中line编号150 
l,348,340 ! Matlab中Line对象编号: 151; Ansys中line编号151 
l,349,343 ! Matlab中Line对象编号: 152; Ansys中line编号152 
l,350,351 ! Matlab中Line对象编号: 153; Ansys中line编号153 
l,351,357 ! Matlab中Line对象编号: 154; Ansys中line编号154 
l,352,353 ! Matlab中Line对象编号: 155; Ansys中line编号155 
l,344,352 ! Matlab中Line对象编号: 156; Ansys中line编号156 
l,353,349 ! Matlab中Line对象编号: 157; Ansys中line编号157 
l,354,355 ! Matlab中Line对象编号: 158; Ansys中line编号158 
l,355,356 ! Matlab中Line对象编号: 159; Ansys中line编号159 
l,356,348 ! Matlab中Line对象编号: 160; Ansys中line编号160 
l,357,358 ! Matlab中Line对象编号: 161; Ansys中line编号161 
l,358,359 ! Matlab中Line对象编号: 162; Ansys中line编号162 
l,359,354 ! Matlab中Line对象编号: 163; Ansys中line编号163 
lsel,all 
cmsel,u,l_selected 
cm,Line_Tower_1,line 
lsel,all 
cm,l_selected,line 
allsel 

! Tower_2 
l,362,363 ! Matlab中Line对象编号: 164; Ansys中line编号164 
l,363,364 ! Matlab中Line对象编号: 165; Ansys中line编号165 
l,364,371 ! Matlab中Line对象编号: 166; Ansys中line编号166 
l,365,366 ! Matlab中Line对象编号: 167; Ansys中line编号167 
l,366,367 ! Matlab中Line对象编号: 168; Ansys中line编号168 
l,367,362 ! Matlab中Line对象编号: 169; Ansys中line编号169 
l,368,370 ! Matlab中Line对象编号: 170; Ansys中line编号170 
l,369,370 ! Matlab中Line对象编号: 171; Ansys中line编号171 
l,370,385 ! Matlab中Line对象编号: 172; Ansys中line编号172 
l,371,372 ! Matlab中Line对象编号: 173; Ansys中line编号173 
l,372,369 ! Matlab中Line对象编号: 174; Ansys中line编号174 
l,372,368 ! Matlab中Line对象编号: 175; Ansys中line编号175 
l,373,365 ! Matlab中Line对象编号: 176; Ansys中line编号176 
l,374,368 ! Matlab中Line对象编号: 177; Ansys中line编号177 
l,375,376 ! Matlab中Line对象编号: 178; Ansys中line编号178 
l,376,382 ! Matlab中Line对象编号: 179; Ansys中line编号179 
l,377,378 ! Matlab中Line对象编号: 180; Ansys中line编号180 
l,369,377 ! Matlab中Line对象编号: 181; Ansys中line编号181 
l,378,374 ! Matlab中Line对象编号: 182; Ansys中line编号182 
l,379,380 ! Matlab中Line对象编号: 183; Ansys中line编号183 
l,380,381 ! Matlab中Line对象编号: 184; Ansys中line编号184 
l,381,373 ! Matlab中Line对象编号: 185; Ansys中line编号185 
l,382,383 ! Matlab中Line对象编号: 186; Ansys中line编号186 
l,383,384 ! Matlab中Line对象编号: 187; Ansys中line编号187 
l,384,379 ! Matlab中Line对象编号: 188; Ansys中line编号188 
lsel,all 
cmsel,u,l_selected 
cm,Line_Tower_2,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_1 
l,219,387 ! Matlab中Line对象编号: 189; Ansys中line编号189 
l,221,388 ! Matlab中Line对象编号: 190; Ansys中line编号190 
l,223,389 ! Matlab中Line对象编号: 191; Ansys中line编号191 
l,225,390 ! Matlab中Line对象编号: 192; Ansys中line编号192 
l,227,391 ! Matlab中Line对象编号: 193; Ansys中line编号193 
l,229,392 ! Matlab中Line对象编号: 194; Ansys中line编号194 
l,231,393 ! Matlab中Line对象编号: 195; Ansys中line编号195 
l,233,394 ! Matlab中Line对象编号: 196; Ansys中line编号196 
l,235,395 ! Matlab中Line对象编号: 197; Ansys中line编号197 
l,237,396 ! Matlab中Line对象编号: 198; Ansys中line编号198 
l,239,397 ! Matlab中Line对象编号: 199; Ansys中line编号199 
l,241,398 ! Matlab中Line对象编号: 200; Ansys中line编号200 
l,243,399 ! Matlab中Line对象编号: 201; Ansys中line编号201 
l,245,400 ! Matlab中Line对象编号: 202; Ansys中line编号202 
l,247,401 ! Matlab中Line对象编号: 203; Ansys中line编号203 
l,249,402 ! Matlab中Line对象编号: 204; Ansys中line编号204 
l,251,403 ! Matlab中Line对象编号: 205; Ansys中line编号205 
l,253,404 ! Matlab中Line对象编号: 206; Ansys中line编号206 
l,255,405 ! Matlab中Line对象编号: 207; Ansys中line编号207 
l,257,406 ! Matlab中Line对象编号: 208; Ansys中line编号208 
l,259,407 ! Matlab中Line对象编号: 209; Ansys中line编号209 
l,261,408 ! Matlab中Line对象编号: 210; Ansys中line编号210 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_1,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_2 
l,219,409 ! Matlab中Line对象编号: 211; Ansys中line编号211 
l,221,410 ! Matlab中Line对象编号: 212; Ansys中line编号212 
l,223,411 ! Matlab中Line对象编号: 213; Ansys中line编号213 
l,225,412 ! Matlab中Line对象编号: 214; Ansys中line编号214 
l,227,413 ! Matlab中Line对象编号: 215; Ansys中line编号215 
l,229,414 ! Matlab中Line对象编号: 216; Ansys中line编号216 
l,231,415 ! Matlab中Line对象编号: 217; Ansys中line编号217 
l,233,416 ! Matlab中Line对象编号: 218; Ansys中line编号218 
l,235,417 ! Matlab中Line对象编号: 219; Ansys中line编号219 
l,237,418 ! Matlab中Line对象编号: 220; Ansys中line编号220 
l,239,419 ! Matlab中Line对象编号: 221; Ansys中line编号221 
l,241,420 ! Matlab中Line对象编号: 222; Ansys中line编号222 
l,243,421 ! Matlab中Line对象编号: 223; Ansys中line编号223 
l,245,422 ! Matlab中Line对象编号: 224; Ansys中line编号224 
l,247,423 ! Matlab中Line对象编号: 225; Ansys中line编号225 
l,249,424 ! Matlab中Line对象编号: 226; Ansys中line编号226 
l,251,425 ! Matlab中Line对象编号: 227; Ansys中line编号227 
l,253,426 ! Matlab中Line对象编号: 228; Ansys中line编号228 
l,255,427 ! Matlab中Line对象编号: 229; Ansys中line编号229 
l,257,428 ! Matlab中Line对象编号: 230; Ansys中line编号230 
l,259,429 ! Matlab中Line对象编号: 231; Ansys中line编号231 
l,261,430 ! Matlab中Line对象编号: 232; Ansys中line编号232 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_2,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_3 
l,198,431 ! Matlab中Line对象编号: 233; Ansys中line编号233 
l,200,432 ! Matlab中Line对象编号: 234; Ansys中line编号234 
l,202,433 ! Matlab中Line对象编号: 235; Ansys中line编号235 
l,204,434 ! Matlab中Line对象编号: 236; Ansys中line编号236 
l,206,435 ! Matlab中Line对象编号: 237; Ansys中line编号237 
l,208,436 ! Matlab中Line对象编号: 238; Ansys中line编号238 
l,210,437 ! Matlab中Line对象编号: 239; Ansys中line编号239 
l,212,438 ! Matlab中Line对象编号: 240; Ansys中line编号240 
l,214,439 ! Matlab中Line对象编号: 241; Ansys中line编号241 
l,216,440 ! Matlab中Line对象编号: 242; Ansys中line编号242 
l,218,441 ! Matlab中Line对象编号: 243; Ansys中line编号243 
l,220,442 ! Matlab中Line对象编号: 244; Ansys中line编号244 
l,222,443 ! Matlab中Line对象编号: 245; Ansys中line编号245 
l,224,444 ! Matlab中Line对象编号: 246; Ansys中line编号246 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_3,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_4 
l,198,445 ! Matlab中Line对象编号: 247; Ansys中line编号247 
l,200,446 ! Matlab中Line对象编号: 248; Ansys中line编号248 
l,202,447 ! Matlab中Line对象编号: 249; Ansys中line编号249 
l,204,448 ! Matlab中Line对象编号: 250; Ansys中line编号250 
l,206,449 ! Matlab中Line对象编号: 251; Ansys中line编号251 
l,208,450 ! Matlab中Line对象编号: 252; Ansys中line编号252 
l,210,451 ! Matlab中Line对象编号: 253; Ansys中line编号253 
l,212,452 ! Matlab中Line对象编号: 254; Ansys中line编号254 
l,214,453 ! Matlab中Line对象编号: 255; Ansys中line编号255 
l,216,454 ! Matlab中Line对象编号: 256; Ansys中line编号256 
l,218,455 ! Matlab中Line对象编号: 257; Ansys中line编号257 
l,220,456 ! Matlab中Line对象编号: 258; Ansys中line编号258 
l,222,457 ! Matlab中Line对象编号: 259; Ansys中line编号259 
l,224,458 ! Matlab中Line对象编号: 260; Ansys中line编号260 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_4,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_5 
l,256,459 ! Matlab中Line对象编号: 261; Ansys中line编号261 
l,258,460 ! Matlab中Line对象编号: 262; Ansys中line编号262 
l,260,461 ! Matlab中Line对象编号: 263; Ansys中line编号263 
l,262,462 ! Matlab中Line对象编号: 264; Ansys中line编号264 
l,264,463 ! Matlab中Line对象编号: 265; Ansys中line编号265 
l,266,464 ! Matlab中Line对象编号: 266; Ansys中line编号266 
l,268,465 ! Matlab中Line对象编号: 267; Ansys中line编号267 
l,270,466 ! Matlab中Line对象编号: 268; Ansys中line编号268 
l,272,467 ! Matlab中Line对象编号: 269; Ansys中line编号269 
l,274,468 ! Matlab中Line对象编号: 270; Ansys中line编号270 
l,276,469 ! Matlab中Line对象编号: 271; Ansys中line编号271 
l,278,470 ! Matlab中Line对象编号: 272; Ansys中line编号272 
l,280,471 ! Matlab中Line对象编号: 273; Ansys中line编号273 
l,282,472 ! Matlab中Line对象编号: 274; Ansys中line编号274 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_5,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_6 
l,256,473 ! Matlab中Line对象编号: 275; Ansys中line编号275 
l,258,474 ! Matlab中Line对象编号: 276; Ansys中line编号276 
l,260,475 ! Matlab中Line对象编号: 277; Ansys中line编号277 
l,262,476 ! Matlab中Line对象编号: 278; Ansys中line编号278 
l,264,477 ! Matlab中Line对象编号: 279; Ansys中line编号279 
l,266,478 ! Matlab中Line对象编号: 280; Ansys中line编号280 
l,268,479 ! Matlab中Line对象编号: 281; Ansys中line编号281 
l,270,480 ! Matlab中Line对象编号: 282; Ansys中line编号282 
l,272,481 ! Matlab中Line对象编号: 283; Ansys中line编号283 
l,274,482 ! Matlab中Line对象编号: 284; Ansys中line编号284 
l,276,483 ! Matlab中Line对象编号: 285; Ansys中line编号285 
l,278,484 ! Matlab中Line对象编号: 286; Ansys中line编号286 
l,280,485 ! Matlab中Line对象编号: 287; Ansys中line编号287 
l,282,486 ! Matlab中Line对象编号: 288; Ansys中line编号288 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_6,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_7 
l,287,487 ! Matlab中Line对象编号: 289; Ansys中line编号289 
l,288,488 ! Matlab中Line对象编号: 290; Ansys中line编号290 
l,289,489 ! Matlab中Line对象编号: 291; Ansys中line编号291 
l,290,490 ! Matlab中Line对象编号: 292; Ansys中line编号292 
l,291,491 ! Matlab中Line对象编号: 293; Ansys中line编号293 
l,292,492 ! Matlab中Line对象编号: 294; Ansys中line编号294 
l,293,493 ! Matlab中Line对象编号: 295; Ansys中line编号295 
l,294,494 ! Matlab中Line对象编号: 296; Ansys中line编号296 
l,295,495 ! Matlab中Line对象编号: 297; Ansys中line编号297 
l,296,496 ! Matlab中Line对象编号: 298; Ansys中line编号298 
l,298,497 ! Matlab中Line对象编号: 299; Ansys中line编号299 
l,300,498 ! Matlab中Line对象编号: 300; Ansys中line编号300 
l,302,499 ! Matlab中Line对象编号: 301; Ansys中line编号301 
l,304,500 ! Matlab中Line对象编号: 302; Ansys中line编号302 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_7,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_8 
l,287,501 ! Matlab中Line对象编号: 303; Ansys中line编号303 
l,288,502 ! Matlab中Line对象编号: 304; Ansys中line编号304 
l,289,503 ! Matlab中Line对象编号: 305; Ansys中line编号305 
l,290,504 ! Matlab中Line对象编号: 306; Ansys中line编号306 
l,291,505 ! Matlab中Line对象编号: 307; Ansys中line编号307 
l,292,506 ! Matlab中Line对象编号: 308; Ansys中line编号308 
l,293,507 ! Matlab中Line对象编号: 309; Ansys中line编号309 
l,294,508 ! Matlab中Line对象编号: 310; Ansys中line编号310 
l,295,509 ! Matlab中Line对象编号: 311; Ansys中line编号311 
l,296,510 ! Matlab中Line对象编号: 312; Ansys中line编号312 
l,298,511 ! Matlab中Line对象编号: 313; Ansys中line编号313 
l,300,512 ! Matlab中Line对象编号: 314; Ansys中line编号314 
l,302,513 ! Matlab中Line对象编号: 315; Ansys中line编号315 
l,304,514 ! Matlab中Line对象编号: 316; Ansys中line编号316 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_8,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_9 
l,313,515 ! Matlab中Line对象编号: 317; Ansys中line编号317 
l,315,516 ! Matlab中Line对象编号: 318; Ansys中line编号318 
l,317,517 ! Matlab中Line对象编号: 319; Ansys中line编号319 
l,319,518 ! Matlab中Line对象编号: 320; Ansys中line编号320 
l,321,519 ! Matlab中Line对象编号: 321; Ansys中line编号321 
l,322,520 ! Matlab中Line对象编号: 322; Ansys中line编号322 
l,323,521 ! Matlab中Line对象编号: 323; Ansys中line编号323 
l,324,522 ! Matlab中Line对象编号: 324; Ansys中line编号324 
l,325,523 ! Matlab中Line对象编号: 325; Ansys中line编号325 
l,326,524 ! Matlab中Line对象编号: 326; Ansys中line编号326 
l,327,525 ! Matlab中Line对象编号: 327; Ansys中line编号327 
l,328,526 ! Matlab中Line对象编号: 328; Ansys中line编号328 
l,329,527 ! Matlab中Line对象编号: 329; Ansys中line编号329 
l,330,528 ! Matlab中Line对象编号: 330; Ansys中line编号330 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_9,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_10 
l,313,529 ! Matlab中Line对象编号: 331; Ansys中line编号331 
l,315,530 ! Matlab中Line对象编号: 332; Ansys中line编号332 
l,317,531 ! Matlab中Line对象编号: 333; Ansys中line编号333 
l,319,532 ! Matlab中Line对象编号: 334; Ansys中line编号334 
l,321,533 ! Matlab中Line对象编号: 335; Ansys中line编号335 
l,322,534 ! Matlab中Line对象编号: 336; Ansys中line编号336 
l,323,535 ! Matlab中Line对象编号: 337; Ansys中line编号337 
l,324,536 ! Matlab中Line对象编号: 338; Ansys中line编号338 
l,325,537 ! Matlab中Line对象编号: 339; Ansys中line编号339 
l,326,538 ! Matlab中Line对象编号: 340; Ansys中line编号340 
l,327,539 ! Matlab中Line对象编号: 341; Ansys中line编号341 
l,328,540 ! Matlab中Line对象编号: 342; Ansys中line编号342 
l,329,541 ! Matlab中Line对象编号: 343; Ansys中line编号343 
l,330,542 ! Matlab中Line对象编号: 344; Ansys中line编号344 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_10,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_11 
l,346,543 ! Matlab中Line对象编号: 345; Ansys中line编号345 
l,339,544 ! Matlab中Line对象编号: 346; Ansys中line编号346 
l,338,545 ! Matlab中Line对象编号: 347; Ansys中line编号347 
l,337,546 ! Matlab中Line对象编号: 348; Ansys中line编号348 
l,342,547 ! Matlab中Line对象编号: 349; Ansys中line编号349 
l,341,548 ! Matlab中Line对象编号: 350; Ansys中line编号350 
l,340,549 ! Matlab中Line对象编号: 351; Ansys中line编号351 
l,348,550 ! Matlab中Line对象编号: 352; Ansys中line编号352 
l,356,551 ! Matlab中Line对象编号: 353; Ansys中line编号353 
l,355,552 ! Matlab中Line对象编号: 354; Ansys中line编号354 
l,354,553 ! Matlab中Line对象编号: 355; Ansys中line编号355 
l,359,554 ! Matlab中Line对象编号: 356; Ansys中line编号356 
l,358,555 ! Matlab中Line对象编号: 357; Ansys中line编号357 
l,357,556 ! Matlab中Line对象编号: 358; Ansys中line编号358 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_11,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_12 
l,346,557 ! Matlab中Line对象编号: 359; Ansys中line编号359 
l,339,558 ! Matlab中Line对象编号: 360; Ansys中line编号360 
l,338,559 ! Matlab中Line对象编号: 361; Ansys中line编号361 
l,337,560 ! Matlab中Line对象编号: 362; Ansys中line编号362 
l,342,561 ! Matlab中Line对象编号: 363; Ansys中line编号363 
l,341,562 ! Matlab中Line对象编号: 364; Ansys中line编号364 
l,340,563 ! Matlab中Line对象编号: 365; Ansys中line编号365 
l,348,564 ! Matlab中Line对象编号: 366; Ansys中line编号366 
l,356,565 ! Matlab中Line对象编号: 367; Ansys中line编号367 
l,355,566 ! Matlab中Line对象编号: 368; Ansys中line编号368 
l,354,567 ! Matlab中Line对象编号: 369; Ansys中line编号369 
l,359,568 ! Matlab中Line对象编号: 370; Ansys中line编号370 
l,358,569 ! Matlab中Line对象编号: 371; Ansys中line编号371 
l,357,570 ! Matlab中Line对象编号: 372; Ansys中line编号372 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_12,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_13 
l,371,571 ! Matlab中Line对象编号: 373; Ansys中line编号373 
l,364,572 ! Matlab中Line对象编号: 374; Ansys中line编号374 
l,363,573 ! Matlab中Line对象编号: 375; Ansys中line编号375 
l,362,574 ! Matlab中Line对象编号: 376; Ansys中line编号376 
l,367,575 ! Matlab中Line对象编号: 377; Ansys中line编号377 
l,366,576 ! Matlab中Line对象编号: 378; Ansys中line编号378 
l,365,577 ! Matlab中Line对象编号: 379; Ansys中line编号379 
l,373,578 ! Matlab中Line对象编号: 380; Ansys中line编号380 
l,381,579 ! Matlab中Line对象编号: 381; Ansys中line编号381 
l,380,580 ! Matlab中Line对象编号: 382; Ansys中line编号382 
l,379,581 ! Matlab中Line对象编号: 383; Ansys中line编号383 
l,384,582 ! Matlab中Line对象编号: 384; Ansys中line编号384 
l,383,583 ! Matlab中Line对象编号: 385; Ansys中line编号385 
l,382,584 ! Matlab中Line对象编号: 386; Ansys中line编号386 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_13,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_14 
l,371,585 ! Matlab中Line对象编号: 387; Ansys中line编号387 
l,364,586 ! Matlab中Line对象编号: 388; Ansys中line编号388 
l,363,587 ! Matlab中Line对象编号: 389; Ansys中line编号389 
l,362,588 ! Matlab中Line对象编号: 390; Ansys中line编号390 
l,367,589 ! Matlab中Line对象编号: 391; Ansys中line编号391 
l,366,590 ! Matlab中Line对象编号: 392; Ansys中line编号392 
l,365,591 ! Matlab中Line对象编号: 393; Ansys中line编号393 
l,373,592 ! Matlab中Line对象编号: 394; Ansys中line编号394 
l,381,593 ! Matlab中Line对象编号: 395; Ansys中line编号395 
l,380,594 ! Matlab中Line对象编号: 396; Ansys中line编号396 
l,379,595 ! Matlab中Line对象编号: 397; Ansys中line编号397 
l,384,596 ! Matlab中Line对象编号: 398; Ansys中line编号398 
l,383,597 ! Matlab中Line对象编号: 399; Ansys中line编号399 
l,382,598 ! Matlab中Line对象编号: 400; Ansys中line编号400 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_14,line 
lsel,all 
cm,l_selected,line 
allsel 

