! 单元名称：Beam188 
! 作用于以下Structure: Girder_1, Girder_2, Girder_3
et,1,beam188 
keyopt,1,3,2

! 单元名称：Beam188 
! 作用于以下Structure: Girder_4, Girder_5
et,2,beam188 
keyopt,2,3,2

! 单元名称：Beam188 
! 作用于以下Structure: Tower_1, Tower_2
et,3,beam188 
keyopt,3,3,2

! 单元名称：Beam188 
! 作用于以下Structure: RigidBeam_1, RigidBeam_2, RigidBeam_3, RigidBeam_4, RigidBeam_5, RigidBeam_6, RigidBeam_7, RigidBeam_8, RigidBeam_9, RigidBeam_10, RigidBeam_11, RigidBeam_12, RigidBeam_13, RigidBeam_14
et,5,beam188 
keyopt,5,3,2

