!塔梁耦合1 
ksel,s,kp,,160 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,1 $ nslk,s $ *get,Node2,node,,num,min
allsel 
cp,Next,Uy,Node1,Node2
cp,Next,Uz,Node1,Node2
cp,Next,Rotx,Node1,Node2
Node1 = $ Node2 =

!塔梁耦合2 
ksel,s,kp,,185 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,93 $ nslk,s $ *get,Node2,node,,num,min
allsel 
cp,Next,Uy,Node1,Node2
cp,Next,Uz,Node1,Node2
cp,Next,Rotx,Node1,Node2
Node1 = $ Node2 =

