function output_str = OutputToAnsys(obj,sec_num)
    output_str = sprintf(['\n' ...
                         'sectype,%d,Beam,HRec \n' ...
                         'secoffset,cent \n' ...
                         'secdata,%E,%E,%E,%E,%E,%E \n'],sec_num, ...
                         obj.Width_Outer,obj.Height_Outer,obj.Thickness_Web1,obj.Thickness_Web2,obj.Thickness_BottomBoard,obj.Thickness_TopBoard);
end