!自锚耦合1 
ksel,s,kp,,139 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,590 $ nslk,s $ *get,Node2,node,,num,min
ksel,s,kp,,613 $ nslk,s $ *get,Node3,node,,num,min
allsel 
cp,Next,Ux,Node1,Node2,Node3
cp,Next,Uy,Node1,Node2,Node3
cp,Next,Uz,Node1,Node2,Node3
Node1 = $ Node2 = $ Node3 =

!自锚耦合2 
ksel,s,kp,,142 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,658 $ nslk,s $ *get,Node2,node,,num,min
ksel,s,kp,,681 $ nslk,s $ *get,Node3,node,,num,min
allsel 
cp,Next,Ux,Node1,Node2,Node3
cp,Next,Uy,Node1,Node2,Node3
cp,Next,Uz,Node1,Node2,Node3
Node1 = $ Node2 = $ Node3 =

!塔梁耦合1 
ksel,s,kp,,160 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,1 $ nslk,s $ *get,Node2,node,,num,min
allsel 
cp,Next,Uy,Node1,Node2
cp,Next,Uz,Node1,Node2
cp,Next,Rotx,Node1,Node2
Node1 = $ Node2 =

!塔梁耦合2 
ksel,s,kp,,184 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,93 $ nslk,s $ *get,Node2,node,,num,min
allsel 
cp,Next,Uy,Node1,Node2
cp,Next,Uz,Node1,Node2
cp,Next,Rotx,Node1,Node2
Node1 = $ Node2 =

!主缆、塔耦合1 
ksel,s,kp,,158 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,404 $ nslk,s $ *get,Node2,node,,num,min
ksel,s,kp,,497 $ nslk,s $ *get,Node3,node,,num,min
allsel 
cp,Next,Ux,Node1,Node2,Node3
cp,Next,Uy,Node1,Node2,Node3
cp,Next,Uz,Node1,Node2,Node3
Node1 = $ Node2 = $ Node3 =

!主缆、梁耦合2 
ksel,s,kp,,182 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,496 $ nslk,s $ *get,Node2,node,,num,min
ksel,s,kp,,589 $ nslk,s $ *get,Node3,node,,num,min
allsel 
cp,Next,Ux,Node1,Node2,Node3
cp,Next,Uy,Node1,Node2,Node3
cp,Next,Uz,Node1,Node2,Node3
Node1 = $ Node2 = $ Node3 =

