!自锚耦合1 
ksel,s,kp,,332 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,785 $ nslk,s $ *get,Node2,node,,num,min
ksel,s,kp,,808 $ nslk,s $ *get,Node3,node,,num,min
allsel 
cp,Next,Ux,Node1,Node2,Node3
cp,Next,Uy,Node1,Node2,Node3
cp,Next,Uz,Node1,Node2,Node3
Node1 = $ Node2 = $ Node3 =

!自锚耦合2 
ksel,s,kp,,335 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,853 $ nslk,s $ *get,Node2,node,,num,min
ksel,s,kp,,876 $ nslk,s $ *get,Node3,node,,num,min
allsel 
cp,Next,Ux,Node1,Node2,Node3
cp,Next,Uy,Node1,Node2,Node3
cp,Next,Uz,Node1,Node2,Node3
Node1 = $ Node2 = $ Node3 =

!塔梁耦合1 
ksel,s,kp,,353 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,194 $ nslk,s $ *get,Node2,node,,num,min
allsel 
cp,Next,Uy,Node1,Node2
cp,Next,Uz,Node1,Node2
cp,Next,Rotx,Node1,Node2
Node1 = $ Node2 =

!塔梁耦合2 
ksel,s,kp,,378 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,286 $ nslk,s $ *get,Node2,node,,num,min
allsel 
cp,Next,Uy,Node1,Node2
cp,Next,Uz,Node1,Node2
cp,Next,Rotx,Node1,Node2
Node1 = $ Node2 =

!主缆、塔耦合1 
ksel,s,kp,,351 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,599 $ nslk,s $ *get,Node2,node,,num,min
ksel,s,kp,,692 $ nslk,s $ *get,Node3,node,,num,min
allsel 
cp,Next,Ux,Node1,Node2,Node3
cp,Next,Uy,Node1,Node2,Node3
cp,Next,Uz,Node1,Node2,Node3
Node1 = $ Node2 = $ Node3 =

!主缆、梁耦合2 
ksel,s,kp,,376 $ nslk,s $ *get,Node1,node,,num,min
ksel,s,kp,,691 $ nslk,s $ *get,Node2,node,,num,min
ksel,s,kp,,784 $ nslk,s $ *get,Node3,node,,num,min
allsel 
cp,Next,Ux,Node1,Node2,Node3
cp,Next,Uy,Node1,Node2,Node3
cp,Next,Uz,Node1,Node2,Node3
Node1 = $ Node2 = $ Node3 =

