lsel,none
cm,l_selected,line
numstr,line,1

! Girder_1 
l,194,195 ! Matlab中Line对象编号: 1; Ansys中line编号1 
l,195,196 ! Matlab中Line对象编号: 2; Ansys中line编号2 
l,196,197 ! Matlab中Line对象编号: 3; Ansys中line编号3 
l,197,198 ! Matlab中Line对象编号: 4; Ansys中line编号4 
l,198,199 ! Matlab中Line对象编号: 5; Ansys中line编号5 
l,199,200 ! Matlab中Line对象编号: 6; Ansys中line编号6 
l,200,201 ! Matlab中Line对象编号: 7; Ansys中line编号7 
l,201,202 ! Matlab中Line对象编号: 8; Ansys中line编号8 
l,202,203 ! Matlab中Line对象编号: 9; Ansys中line编号9 
l,203,204 ! Matlab中Line对象编号: 10; Ansys中line编号10 
l,204,205 ! Matlab中Line对象编号: 11; Ansys中line编号11 
l,205,206 ! Matlab中Line对象编号: 12; Ansys中line编号12 
l,206,207 ! Matlab中Line对象编号: 13; Ansys中line编号13 
l,207,208 ! Matlab中Line对象编号: 14; Ansys中line编号14 
l,208,209 ! Matlab中Line对象编号: 15; Ansys中line编号15 
l,209,210 ! Matlab中Line对象编号: 16; Ansys中line编号16 
l,210,211 ! Matlab中Line对象编号: 17; Ansys中line编号17 
l,211,212 ! Matlab中Line对象编号: 18; Ansys中line编号18 
l,212,213 ! Matlab中Line对象编号: 19; Ansys中line编号19 
l,213,214 ! Matlab中Line对象编号: 20; Ansys中line编号20 
l,214,215 ! Matlab中Line对象编号: 21; Ansys中line编号21 
l,215,216 ! Matlab中Line对象编号: 22; Ansys中line编号22 
l,216,217 ! Matlab中Line对象编号: 23; Ansys中line编号23 
l,217,218 ! Matlab中Line对象编号: 24; Ansys中line编号24 
l,218,219 ! Matlab中Line对象编号: 25; Ansys中line编号25 
l,219,220 ! Matlab中Line对象编号: 26; Ansys中line编号26 
l,220,221 ! Matlab中Line对象编号: 27; Ansys中line编号27 
l,221,222 ! Matlab中Line对象编号: 28; Ansys中line编号28 
l,222,223 ! Matlab中Line对象编号: 29; Ansys中line编号29 
l,223,224 ! Matlab中Line对象编号: 30; Ansys中line编号30 
l,224,225 ! Matlab中Line对象编号: 31; Ansys中line编号31 
l,225,226 ! Matlab中Line对象编号: 32; Ansys中line编号32 
l,226,227 ! Matlab中Line对象编号: 33; Ansys中line编号33 
l,227,228 ! Matlab中Line对象编号: 34; Ansys中line编号34 
l,228,229 ! Matlab中Line对象编号: 35; Ansys中line编号35 
l,229,230 ! Matlab中Line对象编号: 36; Ansys中line编号36 
l,230,231 ! Matlab中Line对象编号: 37; Ansys中line编号37 
l,231,232 ! Matlab中Line对象编号: 38; Ansys中line编号38 
l,232,233 ! Matlab中Line对象编号: 39; Ansys中line编号39 
l,233,234 ! Matlab中Line对象编号: 40; Ansys中line编号40 
l,234,235 ! Matlab中Line对象编号: 41; Ansys中line编号41 
l,235,236 ! Matlab中Line对象编号: 42; Ansys中line编号42 
l,236,237 ! Matlab中Line对象编号: 43; Ansys中line编号43 
l,237,238 ! Matlab中Line对象编号: 44; Ansys中line编号44 
l,238,239 ! Matlab中Line对象编号: 45; Ansys中line编号45 
l,239,240 ! Matlab中Line对象编号: 46; Ansys中line编号46 
l,240,241 ! Matlab中Line对象编号: 47; Ansys中line编号47 
l,241,242 ! Matlab中Line对象编号: 48; Ansys中line编号48 
l,242,243 ! Matlab中Line对象编号: 49; Ansys中line编号49 
l,243,244 ! Matlab中Line对象编号: 50; Ansys中line编号50 
l,244,245 ! Matlab中Line对象编号: 51; Ansys中line编号51 
l,245,246 ! Matlab中Line对象编号: 52; Ansys中line编号52 
l,246,247 ! Matlab中Line对象编号: 53; Ansys中line编号53 
l,247,248 ! Matlab中Line对象编号: 54; Ansys中line编号54 
l,248,249 ! Matlab中Line对象编号: 55; Ansys中line编号55 
l,249,250 ! Matlab中Line对象编号: 56; Ansys中line编号56 
l,250,251 ! Matlab中Line对象编号: 57; Ansys中line编号57 
l,251,252 ! Matlab中Line对象编号: 58; Ansys中line编号58 
l,252,253 ! Matlab中Line对象编号: 59; Ansys中line编号59 
l,253,254 ! Matlab中Line对象编号: 60; Ansys中line编号60 
l,254,255 ! Matlab中Line对象编号: 61; Ansys中line编号61 
l,255,256 ! Matlab中Line对象编号: 62; Ansys中line编号62 
l,256,257 ! Matlab中Line对象编号: 63; Ansys中line编号63 
l,257,258 ! Matlab中Line对象编号: 64; Ansys中line编号64 
l,258,259 ! Matlab中Line对象编号: 65; Ansys中line编号65 
l,259,260 ! Matlab中Line对象编号: 66; Ansys中line编号66 
l,260,261 ! Matlab中Line对象编号: 67; Ansys中line编号67 
l,261,262 ! Matlab中Line对象编号: 68; Ansys中line编号68 
l,262,263 ! Matlab中Line对象编号: 69; Ansys中line编号69 
l,263,264 ! Matlab中Line对象编号: 70; Ansys中line编号70 
l,264,265 ! Matlab中Line对象编号: 71; Ansys中line编号71 
l,265,266 ! Matlab中Line对象编号: 72; Ansys中line编号72 
l,266,267 ! Matlab中Line对象编号: 73; Ansys中line编号73 
l,267,268 ! Matlab中Line对象编号: 74; Ansys中line编号74 
l,268,269 ! Matlab中Line对象编号: 75; Ansys中line编号75 
l,269,270 ! Matlab中Line对象编号: 76; Ansys中line编号76 
l,270,271 ! Matlab中Line对象编号: 77; Ansys中line编号77 
l,271,272 ! Matlab中Line对象编号: 78; Ansys中line编号78 
l,272,273 ! Matlab中Line对象编号: 79; Ansys中line编号79 
l,273,274 ! Matlab中Line对象编号: 80; Ansys中line编号80 
l,274,275 ! Matlab中Line对象编号: 81; Ansys中line编号81 
l,275,276 ! Matlab中Line对象编号: 82; Ansys中line编号82 
l,276,277 ! Matlab中Line对象编号: 83; Ansys中line编号83 
l,277,278 ! Matlab中Line对象编号: 84; Ansys中line编号84 
l,278,279 ! Matlab中Line对象编号: 85; Ansys中line编号85 
l,279,280 ! Matlab中Line对象编号: 86; Ansys中line编号86 
l,280,281 ! Matlab中Line对象编号: 87; Ansys中line编号87 
l,281,282 ! Matlab中Line对象编号: 88; Ansys中line编号88 
l,282,283 ! Matlab中Line对象编号: 89; Ansys中line编号89 
l,283,284 ! Matlab中Line对象编号: 90; Ansys中line编号90 
l,284,285 ! Matlab中Line对象编号: 91; Ansys中line编号91 
l,285,286 ! Matlab中Line对象编号: 92; Ansys中line编号92 
lsel,all 
cmsel,u,l_selected 
cm,Line_Girder_1,line 
lsel,all 
cm,l_selected,line 
allsel 

! Girder_2 
l,287,288 ! Matlab中Line对象编号: 93; Ansys中line编号93 
l,288,289 ! Matlab中Line对象编号: 94; Ansys中line编号94 
l,289,290 ! Matlab中Line对象编号: 95; Ansys中line编号95 
l,290,291 ! Matlab中Line对象编号: 96; Ansys中line编号96 
l,291,292 ! Matlab中Line对象编号: 97; Ansys中line编号97 
l,292,293 ! Matlab中Line对象编号: 98; Ansys中line编号98 
l,293,294 ! Matlab中Line对象编号: 99; Ansys中line编号99 
l,294,295 ! Matlab中Line对象编号: 100; Ansys中line编号100 
l,295,296 ! Matlab中Line对象编号: 101; Ansys中line编号101 
l,296,297 ! Matlab中Line对象编号: 102; Ansys中line编号102 
l,297,298 ! Matlab中Line对象编号: 103; Ansys中line编号103 
l,298,299 ! Matlab中Line对象编号: 104; Ansys中line编号104 
l,299,300 ! Matlab中Line对象编号: 105; Ansys中line编号105 
l,300,301 ! Matlab中Line对象编号: 106; Ansys中line编号106 
l,301,302 ! Matlab中Line对象编号: 107; Ansys中line编号107 
l,302,303 ! Matlab中Line对象编号: 108; Ansys中line编号108 
l,303,304 ! Matlab中Line对象编号: 109; Ansys中line编号109 
l,304,305 ! Matlab中Line对象编号: 110; Ansys中line编号110 
l,305,306 ! Matlab中Line对象编号: 111; Ansys中line编号111 
l,306,307 ! Matlab中Line对象编号: 112; Ansys中line编号112 
l,307,194 ! Matlab中Line对象编号: 113; Ansys中line编号113 
lsel,all 
cmsel,u,l_selected 
cm,Line_Girder_2,line 
lsel,all 
cm,l_selected,line 
allsel 

! Girder_3 
l,286,310 ! Matlab中Line对象编号: 114; Ansys中line编号114 
l,310,311 ! Matlab中Line对象编号: 115; Ansys中line编号115 
l,311,312 ! Matlab中Line对象编号: 116; Ansys中line编号116 
l,312,313 ! Matlab中Line对象编号: 117; Ansys中line编号117 
l,313,314 ! Matlab中Line对象编号: 118; Ansys中line编号118 
l,314,315 ! Matlab中Line对象编号: 119; Ansys中line编号119 
l,315,316 ! Matlab中Line对象编号: 120; Ansys中line编号120 
l,316,317 ! Matlab中Line对象编号: 121; Ansys中line编号121 
l,317,318 ! Matlab中Line对象编号: 122; Ansys中line编号122 
l,318,319 ! Matlab中Line对象编号: 123; Ansys中line编号123 
l,319,320 ! Matlab中Line对象编号: 124; Ansys中line编号124 
l,320,321 ! Matlab中Line对象编号: 125; Ansys中line编号125 
l,321,322 ! Matlab中Line对象编号: 126; Ansys中line编号126 
l,322,323 ! Matlab中Line对象编号: 127; Ansys中line编号127 
l,323,324 ! Matlab中Line对象编号: 128; Ansys中line编号128 
l,324,325 ! Matlab中Line对象编号: 129; Ansys中line编号129 
l,325,326 ! Matlab中Line对象编号: 130; Ansys中line编号130 
l,326,327 ! Matlab中Line对象编号: 131; Ansys中line编号131 
l,327,328 ! Matlab中Line对象编号: 132; Ansys中line编号132 
l,328,329 ! Matlab中Line对象编号: 133; Ansys中line编号133 
l,329,330 ! Matlab中Line对象编号: 134; Ansys中line编号134 
lsel,all 
cmsel,u,l_selected 
cm,Line_Girder_3,line 
lsel,all 
cm,l_selected,line 
allsel 

! Girder_4 
l,331,332 ! Matlab中Line对象编号: 135; Ansys中line编号135 
l,332,287 ! Matlab中Line对象编号: 136; Ansys中line编号136 
lsel,all 
cmsel,u,l_selected 
cm,Line_Girder_4,line 
lsel,all 
cm,l_selected,line 
allsel 

! Girder_5 
l,330,335 ! Matlab中Line对象编号: 137; Ansys中line编号137 
l,335,336 ! Matlab中Line对象编号: 138; Ansys中line编号138 
lsel,all 
cmsel,u,l_selected 
cm,Line_Girder_5,line 
lsel,all 
cm,l_selected,line 
allsel 

! Tower_1 
l,337,338 ! Matlab中Line对象编号: 139; Ansys中line编号139 
l,338,339 ! Matlab中Line对象编号: 140; Ansys中line编号140 
l,339,346 ! Matlab中Line对象编号: 141; Ansys中line编号141 
l,340,341 ! Matlab中Line对象编号: 142; Ansys中line编号142 
l,341,342 ! Matlab中Line对象编号: 143; Ansys中line编号143 
l,342,337 ! Matlab中Line对象编号: 144; Ansys中line编号144 
l,343,345 ! Matlab中Line对象编号: 145; Ansys中line编号145 
l,344,345 ! Matlab中Line对象编号: 146; Ansys中line编号146 
l,345,360 ! Matlab中Line对象编号: 147; Ansys中line编号147 
l,346,347 ! Matlab中Line对象编号: 148; Ansys中line编号148 
l,347,344 ! Matlab中Line对象编号: 149; Ansys中line编号149 
l,347,343 ! Matlab中Line对象编号: 150; Ansys中line编号150 
l,348,340 ! Matlab中Line对象编号: 151; Ansys中line编号151 
l,349,343 ! Matlab中Line对象编号: 152; Ansys中line编号152 
l,350,351 ! Matlab中Line对象编号: 153; Ansys中line编号153 
l,351,357 ! Matlab中Line对象编号: 154; Ansys中line编号154 
l,352,353 ! Matlab中Line对象编号: 155; Ansys中line编号155 
l,344,352 ! Matlab中Line对象编号: 156; Ansys中line编号156 
l,353,349 ! Matlab中Line对象编号: 157; Ansys中line编号157 
l,354,355 ! Matlab中Line对象编号: 158; Ansys中line编号158 
l,355,356 ! Matlab中Line对象编号: 159; Ansys中line编号159 
l,356,348 ! Matlab中Line对象编号: 160; Ansys中line编号160 
l,357,358 ! Matlab中Line对象编号: 161; Ansys中line编号161 
l,358,359 ! Matlab中Line对象编号: 162; Ansys中line编号162 
l,359,354 ! Matlab中Line对象编号: 163; Ansys中line编号163 
lsel,all 
cmsel,u,l_selected 
cm,Line_Tower_1,line 
lsel,all 
cm,l_selected,line 
allsel 

! Tower_2 
l,362,363 ! Matlab中Line对象编号: 164; Ansys中line编号164 
l,363,364 ! Matlab中Line对象编号: 165; Ansys中line编号165 
l,364,371 ! Matlab中Line对象编号: 166; Ansys中line编号166 
l,365,366 ! Matlab中Line对象编号: 167; Ansys中line编号167 
l,366,367 ! Matlab中Line对象编号: 168; Ansys中line编号168 
l,367,362 ! Matlab中Line对象编号: 169; Ansys中line编号169 
l,368,370 ! Matlab中Line对象编号: 170; Ansys中line编号170 
l,369,370 ! Matlab中Line对象编号: 171; Ansys中line编号171 
l,370,385 ! Matlab中Line对象编号: 172; Ansys中line编号172 
l,371,372 ! Matlab中Line对象编号: 173; Ansys中line编号173 
l,372,369 ! Matlab中Line对象编号: 174; Ansys中line编号174 
l,372,368 ! Matlab中Line对象编号: 175; Ansys中line编号175 
l,373,365 ! Matlab中Line对象编号: 176; Ansys中line编号176 
l,374,368 ! Matlab中Line对象编号: 177; Ansys中line编号177 
l,375,376 ! Matlab中Line对象编号: 178; Ansys中line编号178 
l,376,382 ! Matlab中Line对象编号: 179; Ansys中line编号179 
l,377,378 ! Matlab中Line对象编号: 180; Ansys中line编号180 
l,369,377 ! Matlab中Line对象编号: 181; Ansys中line编号181 
l,378,374 ! Matlab中Line对象编号: 182; Ansys中line编号182 
l,379,380 ! Matlab中Line对象编号: 183; Ansys中line编号183 
l,380,381 ! Matlab中Line对象编号: 184; Ansys中line编号184 
l,381,373 ! Matlab中Line对象编号: 185; Ansys中line编号185 
l,382,383 ! Matlab中Line对象编号: 186; Ansys中line编号186 
l,383,384 ! Matlab中Line对象编号: 187; Ansys中line编号187 
l,384,379 ! Matlab中Line对象编号: 188; Ansys中line编号188 
lsel,all 
cmsel,u,l_selected 
cm,Line_Tower_2,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_1 
l,219,387 ! Matlab中Line对象编号: 189; Ansys中line编号189 
l,221,388 ! Matlab中Line对象编号: 190; Ansys中line编号190 
l,223,389 ! Matlab中Line对象编号: 191; Ansys中line编号191 
l,225,390 ! Matlab中Line对象编号: 192; Ansys中line编号192 
l,227,391 ! Matlab中Line对象编号: 193; Ansys中line编号193 
l,229,392 ! Matlab中Line对象编号: 194; Ansys中line编号194 
l,231,393 ! Matlab中Line对象编号: 195; Ansys中line编号195 
l,233,394 ! Matlab中Line对象编号: 196; Ansys中line编号196 
l,235,395 ! Matlab中Line对象编号: 197; Ansys中line编号197 
l,237,396 ! Matlab中Line对象编号: 198; Ansys中line编号198 
l,239,397 ! Matlab中Line对象编号: 199; Ansys中line编号199 
l,241,398 ! Matlab中Line对象编号: 200; Ansys中line编号200 
l,243,399 ! Matlab中Line对象编号: 201; Ansys中line编号201 
l,245,400 ! Matlab中Line对象编号: 202; Ansys中line编号202 
l,247,401 ! Matlab中Line对象编号: 203; Ansys中line编号203 
l,249,402 ! Matlab中Line对象编号: 204; Ansys中line编号204 
l,251,403 ! Matlab中Line对象编号: 205; Ansys中line编号205 
l,253,404 ! Matlab中Line对象编号: 206; Ansys中line编号206 
l,255,405 ! Matlab中Line对象编号: 207; Ansys中line编号207 
l,257,406 ! Matlab中Line对象编号: 208; Ansys中line编号208 
l,259,407 ! Matlab中Line对象编号: 209; Ansys中line编号209 
l,261,408 ! Matlab中Line对象编号: 210; Ansys中line编号210 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_1,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_2 
l,219,409 ! Matlab中Line对象编号: 211; Ansys中line编号211 
l,221,410 ! Matlab中Line对象编号: 212; Ansys中line编号212 
l,223,411 ! Matlab中Line对象编号: 213; Ansys中line编号213 
l,225,412 ! Matlab中Line对象编号: 214; Ansys中line编号214 
l,227,413 ! Matlab中Line对象编号: 215; Ansys中line编号215 
l,229,414 ! Matlab中Line对象编号: 216; Ansys中line编号216 
l,231,415 ! Matlab中Line对象编号: 217; Ansys中line编号217 
l,233,416 ! Matlab中Line对象编号: 218; Ansys中line编号218 
l,235,417 ! Matlab中Line对象编号: 219; Ansys中line编号219 
l,237,418 ! Matlab中Line对象编号: 220; Ansys中line编号220 
l,239,419 ! Matlab中Line对象编号: 221; Ansys中line编号221 
l,241,420 ! Matlab中Line对象编号: 222; Ansys中line编号222 
l,243,421 ! Matlab中Line对象编号: 223; Ansys中line编号223 
l,245,422 ! Matlab中Line对象编号: 224; Ansys中line编号224 
l,247,423 ! Matlab中Line对象编号: 225; Ansys中line编号225 
l,249,424 ! Matlab中Line对象编号: 226; Ansys中line编号226 
l,251,425 ! Matlab中Line对象编号: 227; Ansys中line编号227 
l,253,426 ! Matlab中Line对象编号: 228; Ansys中line编号228 
l,255,427 ! Matlab中Line对象编号: 229; Ansys中line编号229 
l,257,428 ! Matlab中Line对象编号: 230; Ansys中line编号230 
l,259,429 ! Matlab中Line对象编号: 231; Ansys中line编号231 
l,261,430 ! Matlab中Line对象编号: 232; Ansys中line编号232 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_2,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_3 
l,198,431 ! Matlab中Line对象编号: 233; Ansys中line编号233 
l,200,432 ! Matlab中Line对象编号: 234; Ansys中line编号234 
l,202,433 ! Matlab中Line对象编号: 235; Ansys中line编号235 
l,204,434 ! Matlab中Line对象编号: 236; Ansys中line编号236 
l,206,435 ! Matlab中Line对象编号: 237; Ansys中line编号237 
l,208,436 ! Matlab中Line对象编号: 238; Ansys中line编号238 
l,210,437 ! Matlab中Line对象编号: 239; Ansys中line编号239 
l,212,438 ! Matlab中Line对象编号: 240; Ansys中line编号240 
l,214,439 ! Matlab中Line对象编号: 241; Ansys中line编号241 
l,216,440 ! Matlab中Line对象编号: 242; Ansys中line编号242 
l,218,441 ! Matlab中Line对象编号: 243; Ansys中line编号243 
l,220,442 ! Matlab中Line对象编号: 244; Ansys中line编号244 
l,222,443 ! Matlab中Line对象编号: 245; Ansys中line编号245 
l,224,444 ! Matlab中Line对象编号: 246; Ansys中line编号246 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_3,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_4 
l,198,445 ! Matlab中Line对象编号: 247; Ansys中line编号247 
l,200,446 ! Matlab中Line对象编号: 248; Ansys中line编号248 
l,202,447 ! Matlab中Line对象编号: 249; Ansys中line编号249 
l,204,448 ! Matlab中Line对象编号: 250; Ansys中line编号250 
l,206,449 ! Matlab中Line对象编号: 251; Ansys中line编号251 
l,208,450 ! Matlab中Line对象编号: 252; Ansys中line编号252 
l,210,451 ! Matlab中Line对象编号: 253; Ansys中line编号253 
l,212,452 ! Matlab中Line对象编号: 254; Ansys中line编号254 
l,214,453 ! Matlab中Line对象编号: 255; Ansys中line编号255 
l,216,454 ! Matlab中Line对象编号: 256; Ansys中line编号256 
l,218,455 ! Matlab中Line对象编号: 257; Ansys中line编号257 
l,220,456 ! Matlab中Line对象编号: 258; Ansys中line编号258 
l,222,457 ! Matlab中Line对象编号: 259; Ansys中line编号259 
l,224,458 ! Matlab中Line对象编号: 260; Ansys中line编号260 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_4,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_5 
l,256,459 ! Matlab中Line对象编号: 261; Ansys中line编号261 
l,258,460 ! Matlab中Line对象编号: 262; Ansys中line编号262 
l,260,461 ! Matlab中Line对象编号: 263; Ansys中line编号263 
l,262,462 ! Matlab中Line对象编号: 264; Ansys中line编号264 
l,264,463 ! Matlab中Line对象编号: 265; Ansys中line编号265 
l,266,464 ! Matlab中Line对象编号: 266; Ansys中line编号266 
l,268,465 ! Matlab中Line对象编号: 267; Ansys中line编号267 
l,270,466 ! Matlab中Line对象编号: 268; Ansys中line编号268 
l,272,467 ! Matlab中Line对象编号: 269; Ansys中line编号269 
l,274,468 ! Matlab中Line对象编号: 270; Ansys中line编号270 
l,276,469 ! Matlab中Line对象编号: 271; Ansys中line编号271 
l,278,470 ! Matlab中Line对象编号: 272; Ansys中line编号272 
l,280,471 ! Matlab中Line对象编号: 273; Ansys中line编号273 
l,282,472 ! Matlab中Line对象编号: 274; Ansys中line编号274 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_5,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_6 
l,256,473 ! Matlab中Line对象编号: 275; Ansys中line编号275 
l,258,474 ! Matlab中Line对象编号: 276; Ansys中line编号276 
l,260,475 ! Matlab中Line对象编号: 277; Ansys中line编号277 
l,262,476 ! Matlab中Line对象编号: 278; Ansys中line编号278 
l,264,477 ! Matlab中Line对象编号: 279; Ansys中line编号279 
l,266,478 ! Matlab中Line对象编号: 280; Ansys中line编号280 
l,268,479 ! Matlab中Line对象编号: 281; Ansys中line编号281 
l,270,480 ! Matlab中Line对象编号: 282; Ansys中line编号282 
l,272,481 ! Matlab中Line对象编号: 283; Ansys中line编号283 
l,274,482 ! Matlab中Line对象编号: 284; Ansys中line编号284 
l,276,483 ! Matlab中Line对象编号: 285; Ansys中line编号285 
l,278,484 ! Matlab中Line对象编号: 286; Ansys中line编号286 
l,280,485 ! Matlab中Line对象编号: 287; Ansys中line编号287 
l,282,486 ! Matlab中Line对象编号: 288; Ansys中line编号288 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_6,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_7 
l,287,487 ! Matlab中Line对象编号: 289; Ansys中line编号289 
l,288,488 ! Matlab中Line对象编号: 290; Ansys中line编号290 
l,289,489 ! Matlab中Line对象编号: 291; Ansys中line编号291 
l,290,490 ! Matlab中Line对象编号: 292; Ansys中line编号292 
l,291,491 ! Matlab中Line对象编号: 293; Ansys中line编号293 
l,292,492 ! Matlab中Line对象编号: 294; Ansys中line编号294 
l,293,493 ! Matlab中Line对象编号: 295; Ansys中line编号295 
l,294,494 ! Matlab中Line对象编号: 296; Ansys中line编号296 
l,295,495 ! Matlab中Line对象编号: 297; Ansys中line编号297 
l,296,496 ! Matlab中Line对象编号: 298; Ansys中line编号298 
l,298,497 ! Matlab中Line对象编号: 299; Ansys中line编号299 
l,300,498 ! Matlab中Line对象编号: 300; Ansys中line编号300 
l,302,499 ! Matlab中Line对象编号: 301; Ansys中line编号301 
l,304,500 ! Matlab中Line对象编号: 302; Ansys中line编号302 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_7,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_8 
l,287,501 ! Matlab中Line对象编号: 303; Ansys中line编号303 
l,288,502 ! Matlab中Line对象编号: 304; Ansys中line编号304 
l,289,503 ! Matlab中Line对象编号: 305; Ansys中line编号305 
l,290,504 ! Matlab中Line对象编号: 306; Ansys中line编号306 
l,291,505 ! Matlab中Line对象编号: 307; Ansys中line编号307 
l,292,506 ! Matlab中Line对象编号: 308; Ansys中line编号308 
l,293,507 ! Matlab中Line对象编号: 309; Ansys中line编号309 
l,294,508 ! Matlab中Line对象编号: 310; Ansys中line编号310 
l,295,509 ! Matlab中Line对象编号: 311; Ansys中line编号311 
l,296,510 ! Matlab中Line对象编号: 312; Ansys中line编号312 
l,298,511 ! Matlab中Line对象编号: 313; Ansys中line编号313 
l,300,512 ! Matlab中Line对象编号: 314; Ansys中line编号314 
l,302,513 ! Matlab中Line对象编号: 315; Ansys中line编号315 
l,304,514 ! Matlab中Line对象编号: 316; Ansys中line编号316 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_8,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_9 
l,313,515 ! Matlab中Line对象编号: 317; Ansys中line编号317 
l,315,516 ! Matlab中Line对象编号: 318; Ansys中line编号318 
l,317,517 ! Matlab中Line对象编号: 319; Ansys中line编号319 
l,319,518 ! Matlab中Line对象编号: 320; Ansys中line编号320 
l,321,519 ! Matlab中Line对象编号: 321; Ansys中line编号321 
l,322,520 ! Matlab中Line对象编号: 322; Ansys中line编号322 
l,323,521 ! Matlab中Line对象编号: 323; Ansys中line编号323 
l,324,522 ! Matlab中Line对象编号: 324; Ansys中line编号324 
l,325,523 ! Matlab中Line对象编号: 325; Ansys中line编号325 
l,326,524 ! Matlab中Line对象编号: 326; Ansys中line编号326 
l,327,525 ! Matlab中Line对象编号: 327; Ansys中line编号327 
l,328,526 ! Matlab中Line对象编号: 328; Ansys中line编号328 
l,329,527 ! Matlab中Line对象编号: 329; Ansys中line编号329 
l,330,528 ! Matlab中Line对象编号: 330; Ansys中line编号330 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_9,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_10 
l,313,529 ! Matlab中Line对象编号: 331; Ansys中line编号331 
l,315,530 ! Matlab中Line对象编号: 332; Ansys中line编号332 
l,317,531 ! Matlab中Line对象编号: 333; Ansys中line编号333 
l,319,532 ! Matlab中Line对象编号: 334; Ansys中line编号334 
l,321,533 ! Matlab中Line对象编号: 335; Ansys中line编号335 
l,322,534 ! Matlab中Line对象编号: 336; Ansys中line编号336 
l,323,535 ! Matlab中Line对象编号: 337; Ansys中line编号337 
l,324,536 ! Matlab中Line对象编号: 338; Ansys中line编号338 
l,325,537 ! Matlab中Line对象编号: 339; Ansys中line编号339 
l,326,538 ! Matlab中Line对象编号: 340; Ansys中line编号340 
l,327,539 ! Matlab中Line对象编号: 341; Ansys中line编号341 
l,328,540 ! Matlab中Line对象编号: 342; Ansys中line编号342 
l,329,541 ! Matlab中Line对象编号: 343; Ansys中line编号343 
l,330,542 ! Matlab中Line对象编号: 344; Ansys中line编号344 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_10,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_11 
l,346,543 ! Matlab中Line对象编号: 345; Ansys中line编号345 
l,339,544 ! Matlab中Line对象编号: 346; Ansys中line编号346 
l,338,545 ! Matlab中Line对象编号: 347; Ansys中line编号347 
l,337,546 ! Matlab中Line对象编号: 348; Ansys中line编号348 
l,342,547 ! Matlab中Line对象编号: 349; Ansys中line编号349 
l,341,548 ! Matlab中Line对象编号: 350; Ansys中line编号350 
l,340,549 ! Matlab中Line对象编号: 351; Ansys中line编号351 
l,348,550 ! Matlab中Line对象编号: 352; Ansys中line编号352 
l,356,551 ! Matlab中Line对象编号: 353; Ansys中line编号353 
l,355,552 ! Matlab中Line对象编号: 354; Ansys中line编号354 
l,354,553 ! Matlab中Line对象编号: 355; Ansys中line编号355 
l,359,554 ! Matlab中Line对象编号: 356; Ansys中line编号356 
l,358,555 ! Matlab中Line对象编号: 357; Ansys中line编号357 
l,357,556 ! Matlab中Line对象编号: 358; Ansys中line编号358 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_11,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_12 
l,346,557 ! Matlab中Line对象编号: 359; Ansys中line编号359 
l,339,558 ! Matlab中Line对象编号: 360; Ansys中line编号360 
l,338,559 ! Matlab中Line对象编号: 361; Ansys中line编号361 
l,337,560 ! Matlab中Line对象编号: 362; Ansys中line编号362 
l,342,561 ! Matlab中Line对象编号: 363; Ansys中line编号363 
l,341,562 ! Matlab中Line对象编号: 364; Ansys中line编号364 
l,340,563 ! Matlab中Line对象编号: 365; Ansys中line编号365 
l,348,564 ! Matlab中Line对象编号: 366; Ansys中line编号366 
l,356,565 ! Matlab中Line对象编号: 367; Ansys中line编号367 
l,355,566 ! Matlab中Line对象编号: 368; Ansys中line编号368 
l,354,567 ! Matlab中Line对象编号: 369; Ansys中line编号369 
l,359,568 ! Matlab中Line对象编号: 370; Ansys中line编号370 
l,358,569 ! Matlab中Line对象编号: 371; Ansys中line编号371 
l,357,570 ! Matlab中Line对象编号: 372; Ansys中line编号372 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_12,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_13 
l,371,571 ! Matlab中Line对象编号: 373; Ansys中line编号373 
l,364,572 ! Matlab中Line对象编号: 374; Ansys中line编号374 
l,363,573 ! Matlab中Line对象编号: 375; Ansys中line编号375 
l,362,574 ! Matlab中Line对象编号: 376; Ansys中line编号376 
l,367,575 ! Matlab中Line对象编号: 377; Ansys中line编号377 
l,366,576 ! Matlab中Line对象编号: 378; Ansys中line编号378 
l,365,577 ! Matlab中Line对象编号: 379; Ansys中line编号379 
l,373,578 ! Matlab中Line对象编号: 380; Ansys中line编号380 
l,381,579 ! Matlab中Line对象编号: 381; Ansys中line编号381 
l,380,580 ! Matlab中Line对象编号: 382; Ansys中line编号382 
l,379,581 ! Matlab中Line对象编号: 383; Ansys中line编号383 
l,384,582 ! Matlab中Line对象编号: 384; Ansys中line编号384 
l,383,583 ! Matlab中Line对象编号: 385; Ansys中line编号385 
l,382,584 ! Matlab中Line对象编号: 386; Ansys中line编号386 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_13,line 
lsel,all 
cm,l_selected,line 
allsel 

! RigidBeam_14 
l,371,585 ! Matlab中Line对象编号: 387; Ansys中line编号387 
l,364,586 ! Matlab中Line对象编号: 388; Ansys中line编号388 
l,363,587 ! Matlab中Line对象编号: 389; Ansys中line编号389 
l,362,588 ! Matlab中Line对象编号: 390; Ansys中line编号390 
l,367,589 ! Matlab中Line对象编号: 391; Ansys中line编号391 
l,366,590 ! Matlab中Line对象编号: 392; Ansys中line编号392 
l,365,591 ! Matlab中Line对象编号: 393; Ansys中line编号393 
l,373,592 ! Matlab中Line对象编号: 394; Ansys中line编号394 
l,381,593 ! Matlab中Line对象编号: 395; Ansys中line编号395 
l,380,594 ! Matlab中Line对象编号: 396; Ansys中line编号396 
l,379,595 ! Matlab中Line对象编号: 397; Ansys中line编号397 
l,384,596 ! Matlab中Line对象编号: 398; Ansys中line编号398 
l,383,597 ! Matlab中Line对象编号: 399; Ansys中line编号399 
l,382,598 ! Matlab中Line对象编号: 400; Ansys中line编号400 
lsel,all 
cmsel,u,l_selected 
cm,Line_RigidBeam_14,line 
lsel,all 
cm,l_selected,line 
allsel 

! StayedCable_1 
l,431,543 ! Matlab中Line对象编号: 401; Ansys中line编号401 
l,432,544 ! Matlab中Line对象编号: 402; Ansys中line编号402 
l,433,545 ! Matlab中Line对象编号: 403; Ansys中line编号403 
l,434,546 ! Matlab中Line对象编号: 404; Ansys中line编号404 
l,435,547 ! Matlab中Line对象编号: 405; Ansys中line编号405 
l,436,548 ! Matlab中Line对象编号: 406; Ansys中line编号406 
l,437,549 ! Matlab中Line对象编号: 407; Ansys中line编号407 
l,438,550 ! Matlab中Line对象编号: 408; Ansys中line编号408 
l,439,551 ! Matlab中Line对象编号: 409; Ansys中line编号409 
l,440,552 ! Matlab中Line对象编号: 410; Ansys中line编号410 
l,441,553 ! Matlab中Line对象编号: 411; Ansys中line编号411 
l,442,554 ! Matlab中Line对象编号: 412; Ansys中line编号412 
l,443,555 ! Matlab中Line对象编号: 413; Ansys中line编号413 
l,444,556 ! Matlab中Line对象编号: 414; Ansys中line编号414 
lsel,all 
cmsel,u,l_selected 
cm,Line_StayedCable_1,line 
lsel,all 
cm,l_selected,line 
allsel 

! StayedCable_2 
l,445,557 ! Matlab中Line对象编号: 415; Ansys中line编号415 
l,446,558 ! Matlab中Line对象编号: 416; Ansys中line编号416 
l,447,559 ! Matlab中Line对象编号: 417; Ansys中line编号417 
l,448,560 ! Matlab中Line对象编号: 418; Ansys中line编号418 
l,449,561 ! Matlab中Line对象编号: 419; Ansys中line编号419 
l,450,562 ! Matlab中Line对象编号: 420; Ansys中line编号420 
l,451,563 ! Matlab中Line对象编号: 421; Ansys中line编号421 
l,452,564 ! Matlab中Line对象编号: 422; Ansys中line编号422 
l,453,565 ! Matlab中Line对象编号: 423; Ansys中line编号423 
l,454,566 ! Matlab中Line对象编号: 424; Ansys中line编号424 
l,455,567 ! Matlab中Line对象编号: 425; Ansys中line编号425 
l,456,568 ! Matlab中Line对象编号: 426; Ansys中line编号426 
l,457,569 ! Matlab中Line对象编号: 427; Ansys中line编号427 
l,458,570 ! Matlab中Line对象编号: 428; Ansys中line编号428 
lsel,all 
cmsel,u,l_selected 
cm,Line_StayedCable_2,line 
lsel,all 
cm,l_selected,line 
allsel 

! StayedCable_3 
l,459,584 ! Matlab中Line对象编号: 429; Ansys中line编号429 
l,460,583 ! Matlab中Line对象编号: 430; Ansys中line编号430 
l,461,582 ! Matlab中Line对象编号: 431; Ansys中line编号431 
l,462,581 ! Matlab中Line对象编号: 432; Ansys中line编号432 
l,463,580 ! Matlab中Line对象编号: 433; Ansys中line编号433 
l,464,579 ! Matlab中Line对象编号: 434; Ansys中line编号434 
l,465,578 ! Matlab中Line对象编号: 435; Ansys中line编号435 
l,466,577 ! Matlab中Line对象编号: 436; Ansys中line编号436 
l,467,576 ! Matlab中Line对象编号: 437; Ansys中line编号437 
l,468,575 ! Matlab中Line对象编号: 438; Ansys中line编号438 
l,469,574 ! Matlab中Line对象编号: 439; Ansys中line编号439 
l,470,573 ! Matlab中Line对象编号: 440; Ansys中line编号440 
l,471,572 ! Matlab中Line对象编号: 441; Ansys中line编号441 
l,472,571 ! Matlab中Line对象编号: 442; Ansys中line编号442 
lsel,all 
cmsel,u,l_selected 
cm,Line_StayedCable_3,line 
lsel,all 
cm,l_selected,line 
allsel 

! StayedCable_4 
l,473,598 ! Matlab中Line对象编号: 443; Ansys中line编号443 
l,474,597 ! Matlab中Line对象编号: 444; Ansys中line编号444 
l,475,596 ! Matlab中Line对象编号: 445; Ansys中line编号445 
l,476,595 ! Matlab中Line对象编号: 446; Ansys中line编号446 
l,477,594 ! Matlab中Line对象编号: 447; Ansys中line编号447 
l,478,593 ! Matlab中Line对象编号: 448; Ansys中line编号448 
l,479,592 ! Matlab中Line对象编号: 449; Ansys中line编号449 
l,480,591 ! Matlab中Line对象编号: 450; Ansys中line编号450 
l,481,590 ! Matlab中Line对象编号: 451; Ansys中line编号451 
l,482,589 ! Matlab中Line对象编号: 452; Ansys中line编号452 
l,483,588 ! Matlab中Line对象编号: 453; Ansys中line编号453 
l,484,587 ! Matlab中Line对象编号: 454; Ansys中line编号454 
l,485,586 ! Matlab中Line对象编号: 455; Ansys中line编号455 
l,486,585 ! Matlab中Line对象编号: 456; Ansys中line编号456 
lsel,all 
cmsel,u,l_selected 
cm,Line_StayedCable_4,line 
lsel,all 
cm,l_selected,line 
allsel 

! StayedCable_5 
l,487,556 ! Matlab中Line对象编号: 457; Ansys中line编号457 
l,488,555 ! Matlab中Line对象编号: 458; Ansys中line编号458 
l,489,554 ! Matlab中Line对象编号: 459; Ansys中line编号459 
l,490,553 ! Matlab中Line对象编号: 460; Ansys中line编号460 
l,491,552 ! Matlab中Line对象编号: 461; Ansys中line编号461 
l,492,551 ! Matlab中Line对象编号: 462; Ansys中line编号462 
l,493,550 ! Matlab中Line对象编号: 463; Ansys中line编号463 
l,494,549 ! Matlab中Line对象编号: 464; Ansys中line编号464 
l,495,548 ! Matlab中Line对象编号: 465; Ansys中line编号465 
l,496,547 ! Matlab中Line对象编号: 466; Ansys中line编号466 
l,497,546 ! Matlab中Line对象编号: 467; Ansys中line编号467 
l,498,545 ! Matlab中Line对象编号: 468; Ansys中line编号468 
l,499,544 ! Matlab中Line对象编号: 469; Ansys中line编号469 
l,500,543 ! Matlab中Line对象编号: 470; Ansys中line编号470 
lsel,all 
cmsel,u,l_selected 
cm,Line_StayedCable_5,line 
lsel,all 
cm,l_selected,line 
allsel 

! StayedCable_6 
l,501,570 ! Matlab中Line对象编号: 471; Ansys中line编号471 
l,502,569 ! Matlab中Line对象编号: 472; Ansys中line编号472 
l,503,568 ! Matlab中Line对象编号: 473; Ansys中line编号473 
l,504,567 ! Matlab中Line对象编号: 474; Ansys中line编号474 
l,505,566 ! Matlab中Line对象编号: 475; Ansys中line编号475 
l,506,565 ! Matlab中Line对象编号: 476; Ansys中line编号476 
l,507,564 ! Matlab中Line对象编号: 477; Ansys中line编号477 
l,508,563 ! Matlab中Line对象编号: 478; Ansys中line编号478 
l,509,562 ! Matlab中Line对象编号: 479; Ansys中line编号479 
l,510,561 ! Matlab中Line对象编号: 480; Ansys中line编号480 
l,511,560 ! Matlab中Line对象编号: 481; Ansys中line编号481 
l,512,559 ! Matlab中Line对象编号: 482; Ansys中line编号482 
l,513,558 ! Matlab中Line对象编号: 483; Ansys中line编号483 
l,514,557 ! Matlab中Line对象编号: 484; Ansys中line编号484 
lsel,all 
cmsel,u,l_selected 
cm,Line_StayedCable_6,line 
lsel,all 
cm,l_selected,line 
allsel 

! StayedCable_7 
l,515,571 ! Matlab中Line对象编号: 485; Ansys中line编号485 
l,516,572 ! Matlab中Line对象编号: 486; Ansys中line编号486 
l,517,573 ! Matlab中Line对象编号: 487; Ansys中line编号487 
l,518,574 ! Matlab中Line对象编号: 488; Ansys中line编号488 
l,519,575 ! Matlab中Line对象编号: 489; Ansys中line编号489 
l,520,576 ! Matlab中Line对象编号: 490; Ansys中line编号490 
l,521,577 ! Matlab中Line对象编号: 491; Ansys中line编号491 
l,522,578 ! Matlab中Line对象编号: 492; Ansys中line编号492 
l,523,579 ! Matlab中Line对象编号: 493; Ansys中line编号493 
l,524,580 ! Matlab中Line对象编号: 494; Ansys中line编号494 
l,525,581 ! Matlab中Line对象编号: 495; Ansys中line编号495 
l,526,582 ! Matlab中Line对象编号: 496; Ansys中line编号496 
l,527,583 ! Matlab中Line对象编号: 497; Ansys中line编号497 
l,528,584 ! Matlab中Line对象编号: 498; Ansys中line编号498 
lsel,all 
cmsel,u,l_selected 
cm,Line_StayedCable_7,line 
lsel,all 
cm,l_selected,line 
allsel 

! StayedCable_8 
l,529,585 ! Matlab中Line对象编号: 499; Ansys中line编号499 
l,530,586 ! Matlab中Line对象编号: 500; Ansys中line编号500 
l,531,587 ! Matlab中Line对象编号: 501; Ansys中line编号501 
l,532,588 ! Matlab中Line对象编号: 502; Ansys中line编号502 
l,533,589 ! Matlab中Line对象编号: 503; Ansys中line编号503 
l,534,590 ! Matlab中Line对象编号: 504; Ansys中line编号504 
l,535,591 ! Matlab中Line对象编号: 505; Ansys中line编号505 
l,536,592 ! Matlab中Line对象编号: 506; Ansys中line编号506 
l,537,593 ! Matlab中Line对象编号: 507; Ansys中line编号507 
l,538,594 ! Matlab中Line对象编号: 508; Ansys中line编号508 
l,539,595 ! Matlab中Line对象编号: 509; Ansys中line编号509 
l,540,596 ! Matlab中Line对象编号: 510; Ansys中line编号510 
l,541,597 ! Matlab中Line对象编号: 511; Ansys中line编号511 
l,542,598 ! Matlab中Line对象编号: 512; Ansys中line编号512 
lsel,all 
cmsel,u,l_selected 
cm,Line_StayedCable_8,line 
lsel,all 
cm,l_selected,line 
allsel 

! Cable_1 
l,599,600 ! Matlab中Line对象编号: 513; Ansys中line编号513 
l,600,601 ! Matlab中Line对象编号: 514; Ansys中line编号514 
l,601,602 ! Matlab中Line对象编号: 515; Ansys中line编号515 
l,602,603 ! Matlab中Line对象编号: 516; Ansys中line编号516 
l,603,604 ! Matlab中Line对象编号: 517; Ansys中line编号517 
l,604,605 ! Matlab中Line对象编号: 518; Ansys中line编号518 
l,605,606 ! Matlab中Line对象编号: 519; Ansys中line编号519 
l,606,607 ! Matlab中Line对象编号: 520; Ansys中line编号520 
l,607,608 ! Matlab中Line对象编号: 521; Ansys中line编号521 
l,608,609 ! Matlab中Line对象编号: 522; Ansys中line编号522 
l,609,610 ! Matlab中Line对象编号: 523; Ansys中line编号523 
l,610,611 ! Matlab中Line对象编号: 524; Ansys中line编号524 
l,611,612 ! Matlab中Line对象编号: 525; Ansys中line编号525 
l,612,613 ! Matlab中Line对象编号: 526; Ansys中line编号526 
l,613,614 ! Matlab中Line对象编号: 527; Ansys中line编号527 
l,614,615 ! Matlab中Line对象编号: 528; Ansys中line编号528 
l,615,616 ! Matlab中Line对象编号: 529; Ansys中line编号529 
l,616,617 ! Matlab中Line对象编号: 530; Ansys中line编号530 
l,617,618 ! Matlab中Line对象编号: 531; Ansys中line编号531 
l,618,619 ! Matlab中Line对象编号: 532; Ansys中line编号532 
l,619,620 ! Matlab中Line对象编号: 533; Ansys中line编号533 
l,620,621 ! Matlab中Line对象编号: 534; Ansys中line编号534 
l,621,622 ! Matlab中Line对象编号: 535; Ansys中line编号535 
l,622,623 ! Matlab中Line对象编号: 536; Ansys中line编号536 
l,623,624 ! Matlab中Line对象编号: 537; Ansys中line编号537 
l,624,625 ! Matlab中Line对象编号: 538; Ansys中line编号538 
l,625,626 ! Matlab中Line对象编号: 539; Ansys中line编号539 
l,626,627 ! Matlab中Line对象编号: 540; Ansys中line编号540 
l,627,628 ! Matlab中Line对象编号: 541; Ansys中line编号541 
l,628,629 ! Matlab中Line对象编号: 542; Ansys中line编号542 
l,629,630 ! Matlab中Line对象编号: 543; Ansys中line编号543 
l,630,631 ! Matlab中Line对象编号: 544; Ansys中line编号544 
l,631,632 ! Matlab中Line对象编号: 545; Ansys中line编号545 
l,632,633 ! Matlab中Line对象编号: 546; Ansys中line编号546 
l,633,634 ! Matlab中Line对象编号: 547; Ansys中line编号547 
l,634,635 ! Matlab中Line对象编号: 548; Ansys中line编号548 
l,635,636 ! Matlab中Line对象编号: 549; Ansys中line编号549 
l,636,637 ! Matlab中Line对象编号: 550; Ansys中line编号550 
l,637,638 ! Matlab中Line对象编号: 551; Ansys中line编号551 
l,638,639 ! Matlab中Line对象编号: 552; Ansys中line编号552 
l,639,640 ! Matlab中Line对象编号: 553; Ansys中line编号553 
l,640,641 ! Matlab中Line对象编号: 554; Ansys中line编号554 
l,641,642 ! Matlab中Line对象编号: 555; Ansys中line编号555 
l,642,643 ! Matlab中Line对象编号: 556; Ansys中line编号556 
l,643,644 ! Matlab中Line对象编号: 557; Ansys中line编号557 
l,644,645 ! Matlab中Line对象编号: 558; Ansys中line编号558 
l,645,646 ! Matlab中Line对象编号: 559; Ansys中line编号559 
l,646,647 ! Matlab中Line对象编号: 560; Ansys中line编号560 
l,647,648 ! Matlab中Line对象编号: 561; Ansys中line编号561 
l,648,649 ! Matlab中Line对象编号: 562; Ansys中line编号562 
l,649,650 ! Matlab中Line对象编号: 563; Ansys中line编号563 
l,650,651 ! Matlab中Line对象编号: 564; Ansys中line编号564 
l,651,652 ! Matlab中Line对象编号: 565; Ansys中line编号565 
l,652,653 ! Matlab中Line对象编号: 566; Ansys中line编号566 
l,653,654 ! Matlab中Line对象编号: 567; Ansys中line编号567 
l,654,655 ! Matlab中Line对象编号: 568; Ansys中line编号568 
l,655,656 ! Matlab中Line对象编号: 569; Ansys中line编号569 
l,656,657 ! Matlab中Line对象编号: 570; Ansys中line编号570 
l,657,658 ! Matlab中Line对象编号: 571; Ansys中line编号571 
l,658,659 ! Matlab中Line对象编号: 572; Ansys中line编号572 
l,659,660 ! Matlab中Line对象编号: 573; Ansys中line编号573 
l,660,661 ! Matlab中Line对象编号: 574; Ansys中line编号574 
l,661,662 ! Matlab中Line对象编号: 575; Ansys中line编号575 
l,662,663 ! Matlab中Line对象编号: 576; Ansys中line编号576 
l,663,664 ! Matlab中Line对象编号: 577; Ansys中line编号577 
l,664,665 ! Matlab中Line对象编号: 578; Ansys中line编号578 
l,665,666 ! Matlab中Line对象编号: 579; Ansys中line编号579 
l,666,667 ! Matlab中Line对象编号: 580; Ansys中line编号580 
l,667,668 ! Matlab中Line对象编号: 581; Ansys中line编号581 
l,668,669 ! Matlab中Line对象编号: 582; Ansys中line编号582 
l,669,670 ! Matlab中Line对象编号: 583; Ansys中line编号583 
l,670,671 ! Matlab中Line对象编号: 584; Ansys中line编号584 
l,671,672 ! Matlab中Line对象编号: 585; Ansys中line编号585 
l,672,673 ! Matlab中Line对象编号: 586; Ansys中line编号586 
l,673,674 ! Matlab中Line对象编号: 587; Ansys中line编号587 
l,674,675 ! Matlab中Line对象编号: 588; Ansys中line编号588 
l,675,676 ! Matlab中Line对象编号: 589; Ansys中line编号589 
l,676,677 ! Matlab中Line对象编号: 590; Ansys中line编号590 
l,677,678 ! Matlab中Line对象编号: 591; Ansys中line编号591 
l,678,679 ! Matlab中Line对象编号: 592; Ansys中line编号592 
l,679,680 ! Matlab中Line对象编号: 593; Ansys中line编号593 
l,680,681 ! Matlab中Line对象编号: 594; Ansys中line编号594 
l,681,682 ! Matlab中Line对象编号: 595; Ansys中line编号595 
l,682,683 ! Matlab中Line对象编号: 596; Ansys中line编号596 
l,683,684 ! Matlab中Line对象编号: 597; Ansys中line编号597 
l,684,685 ! Matlab中Line对象编号: 598; Ansys中line编号598 
l,685,686 ! Matlab中Line对象编号: 599; Ansys中line编号599 
l,686,687 ! Matlab中Line对象编号: 600; Ansys中line编号600 
l,687,688 ! Matlab中Line对象编号: 601; Ansys中line编号601 
l,688,689 ! Matlab中Line对象编号: 602; Ansys中line编号602 
l,689,690 ! Matlab中Line对象编号: 603; Ansys中line编号603 
l,690,691 ! Matlab中Line对象编号: 604; Ansys中line编号604 
lsel,all 
cmsel,u,l_selected 
cm,Line_Cable_1,line 
lsel,all 
cm,l_selected,line 
allsel 

! Cable_2 
l,692,693 ! Matlab中Line对象编号: 605; Ansys中line编号605 
l,693,694 ! Matlab中Line对象编号: 606; Ansys中line编号606 
l,694,695 ! Matlab中Line对象编号: 607; Ansys中line编号607 
l,695,696 ! Matlab中Line对象编号: 608; Ansys中line编号608 
l,696,697 ! Matlab中Line对象编号: 609; Ansys中line编号609 
l,697,698 ! Matlab中Line对象编号: 610; Ansys中line编号610 
l,698,699 ! Matlab中Line对象编号: 611; Ansys中line编号611 
l,699,700 ! Matlab中Line对象编号: 612; Ansys中line编号612 
l,700,701 ! Matlab中Line对象编号: 613; Ansys中line编号613 
l,701,702 ! Matlab中Line对象编号: 614; Ansys中line编号614 
l,702,703 ! Matlab中Line对象编号: 615; Ansys中line编号615 
l,703,704 ! Matlab中Line对象编号: 616; Ansys中line编号616 
l,704,705 ! Matlab中Line对象编号: 617; Ansys中line编号617 
l,705,706 ! Matlab中Line对象编号: 618; Ansys中line编号618 
l,706,707 ! Matlab中Line对象编号: 619; Ansys中line编号619 
l,707,708 ! Matlab中Line对象编号: 620; Ansys中line编号620 
l,708,709 ! Matlab中Line对象编号: 621; Ansys中line编号621 
l,709,710 ! Matlab中Line对象编号: 622; Ansys中line编号622 
l,710,711 ! Matlab中Line对象编号: 623; Ansys中line编号623 
l,711,712 ! Matlab中Line对象编号: 624; Ansys中line编号624 
l,712,713 ! Matlab中Line对象编号: 625; Ansys中line编号625 
l,713,714 ! Matlab中Line对象编号: 626; Ansys中line编号626 
l,714,715 ! Matlab中Line对象编号: 627; Ansys中line编号627 
l,715,716 ! Matlab中Line对象编号: 628; Ansys中line编号628 
l,716,717 ! Matlab中Line对象编号: 629; Ansys中line编号629 
l,717,718 ! Matlab中Line对象编号: 630; Ansys中line编号630 
l,718,719 ! Matlab中Line对象编号: 631; Ansys中line编号631 
l,719,720 ! Matlab中Line对象编号: 632; Ansys中line编号632 
l,720,721 ! Matlab中Line对象编号: 633; Ansys中line编号633 
l,721,722 ! Matlab中Line对象编号: 634; Ansys中line编号634 
l,722,723 ! Matlab中Line对象编号: 635; Ansys中line编号635 
l,723,724 ! Matlab中Line对象编号: 636; Ansys中line编号636 
l,724,725 ! Matlab中Line对象编号: 637; Ansys中line编号637 
l,725,726 ! Matlab中Line对象编号: 638; Ansys中line编号638 
l,726,727 ! Matlab中Line对象编号: 639; Ansys中line编号639 
l,727,728 ! Matlab中Line对象编号: 640; Ansys中line编号640 
l,728,729 ! Matlab中Line对象编号: 641; Ansys中line编号641 
l,729,730 ! Matlab中Line对象编号: 642; Ansys中line编号642 
l,730,731 ! Matlab中Line对象编号: 643; Ansys中line编号643 
l,731,732 ! Matlab中Line对象编号: 644; Ansys中line编号644 
l,732,733 ! Matlab中Line对象编号: 645; Ansys中line编号645 
l,733,734 ! Matlab中Line对象编号: 646; Ansys中line编号646 
l,734,735 ! Matlab中Line对象编号: 647; Ansys中line编号647 
l,735,736 ! Matlab中Line对象编号: 648; Ansys中line编号648 
l,736,737 ! Matlab中Line对象编号: 649; Ansys中line编号649 
l,737,738 ! Matlab中Line对象编号: 650; Ansys中line编号650 
l,738,739 ! Matlab中Line对象编号: 651; Ansys中line编号651 
l,739,740 ! Matlab中Line对象编号: 652; Ansys中line编号652 
l,740,741 ! Matlab中Line对象编号: 653; Ansys中line编号653 
l,741,742 ! Matlab中Line对象编号: 654; Ansys中line编号654 
l,742,743 ! Matlab中Line对象编号: 655; Ansys中line编号655 
l,743,744 ! Matlab中Line对象编号: 656; Ansys中line编号656 
l,744,745 ! Matlab中Line对象编号: 657; Ansys中line编号657 
l,745,746 ! Matlab中Line对象编号: 658; Ansys中line编号658 
l,746,747 ! Matlab中Line对象编号: 659; Ansys中line编号659 
l,747,748 ! Matlab中Line对象编号: 660; Ansys中line编号660 
l,748,749 ! Matlab中Line对象编号: 661; Ansys中line编号661 
l,749,750 ! Matlab中Line对象编号: 662; Ansys中line编号662 
l,750,751 ! Matlab中Line对象编号: 663; Ansys中line编号663 
l,751,752 ! Matlab中Line对象编号: 664; Ansys中line编号664 
l,752,753 ! Matlab中Line对象编号: 665; Ansys中line编号665 
l,753,754 ! Matlab中Line对象编号: 666; Ansys中line编号666 
l,754,755 ! Matlab中Line对象编号: 667; Ansys中line编号667 
l,755,756 ! Matlab中Line对象编号: 668; Ansys中line编号668 
l,756,757 ! Matlab中Line对象编号: 669; Ansys中line编号669 
l,757,758 ! Matlab中Line对象编号: 670; Ansys中line编号670 
l,758,759 ! Matlab中Line对象编号: 671; Ansys中line编号671 
l,759,760 ! Matlab中Line对象编号: 672; Ansys中line编号672 
l,760,761 ! Matlab中Line对象编号: 673; Ansys中line编号673 
l,761,762 ! Matlab中Line对象编号: 674; Ansys中line编号674 
l,762,763 ! Matlab中Line对象编号: 675; Ansys中line编号675 
l,763,764 ! Matlab中Line对象编号: 676; Ansys中line编号676 
l,764,765 ! Matlab中Line对象编号: 677; Ansys中line编号677 
l,765,766 ! Matlab中Line对象编号: 678; Ansys中line编号678 
l,766,767 ! Matlab中Line对象编号: 679; Ansys中line编号679 
l,767,768 ! Matlab中Line对象编号: 680; Ansys中line编号680 
l,768,769 ! Matlab中Line对象编号: 681; Ansys中line编号681 
l,769,770 ! Matlab中Line对象编号: 682; Ansys中line编号682 
l,770,771 ! Matlab中Line对象编号: 683; Ansys中line编号683 
l,771,772 ! Matlab中Line对象编号: 684; Ansys中line编号684 
l,772,773 ! Matlab中Line对象编号: 685; Ansys中line编号685 
l,773,774 ! Matlab中Line对象编号: 686; Ansys中line编号686 
l,774,775 ! Matlab中Line对象编号: 687; Ansys中line编号687 
l,775,776 ! Matlab中Line对象编号: 688; Ansys中line编号688 
l,776,777 ! Matlab中Line对象编号: 689; Ansys中line编号689 
l,777,778 ! Matlab中Line对象编号: 690; Ansys中line编号690 
l,778,779 ! Matlab中Line对象编号: 691; Ansys中line编号691 
l,779,780 ! Matlab中Line对象编号: 692; Ansys中line编号692 
l,780,781 ! Matlab中Line对象编号: 693; Ansys中line编号693 
l,781,782 ! Matlab中Line对象编号: 694; Ansys中line编号694 
l,782,783 ! Matlab中Line对象编号: 695; Ansys中line编号695 
l,783,784 ! Matlab中Line对象编号: 696; Ansys中line编号696 
lsel,all 
cmsel,u,l_selected 
cm,Line_Cable_2,line 
lsel,all 
cm,l_selected,line 
allsel 

! Cable_3 
l,785,786 ! Matlab中Line对象编号: 697; Ansys中line编号697 
l,786,787 ! Matlab中Line对象编号: 698; Ansys中line编号698 
l,787,788 ! Matlab中Line对象编号: 699; Ansys中line编号699 
l,788,789 ! Matlab中Line对象编号: 700; Ansys中line编号700 
l,789,790 ! Matlab中Line对象编号: 701; Ansys中line编号701 
l,790,791 ! Matlab中Line对象编号: 702; Ansys中line编号702 
l,791,792 ! Matlab中Line对象编号: 703; Ansys中line编号703 
l,792,793 ! Matlab中Line对象编号: 704; Ansys中line编号704 
l,793,794 ! Matlab中Line对象编号: 705; Ansys中line编号705 
l,794,795 ! Matlab中Line对象编号: 706; Ansys中line编号706 
l,795,796 ! Matlab中Line对象编号: 707; Ansys中line编号707 
l,796,797 ! Matlab中Line对象编号: 708; Ansys中line编号708 
l,797,798 ! Matlab中Line对象编号: 709; Ansys中line编号709 
l,798,799 ! Matlab中Line对象编号: 710; Ansys中line编号710 
l,799,800 ! Matlab中Line对象编号: 711; Ansys中line编号711 
l,800,801 ! Matlab中Line对象编号: 712; Ansys中line编号712 
l,801,802 ! Matlab中Line对象编号: 713; Ansys中line编号713 
l,802,803 ! Matlab中Line对象编号: 714; Ansys中line编号714 
l,803,804 ! Matlab中Line对象编号: 715; Ansys中line编号715 
l,804,805 ! Matlab中Line对象编号: 716; Ansys中line编号716 
l,805,806 ! Matlab中Line对象编号: 717; Ansys中line编号717 
l,806,599 ! Matlab中Line对象编号: 718; Ansys中line编号718 
lsel,all 
cmsel,u,l_selected 
cm,Line_Cable_3,line 
lsel,all 
cm,l_selected,line 
allsel 

! Cable_4 
l,808,809 ! Matlab中Line对象编号: 719; Ansys中line编号719 
l,809,810 ! Matlab中Line对象编号: 720; Ansys中line编号720 
l,810,811 ! Matlab中Line对象编号: 721; Ansys中line编号721 
l,811,812 ! Matlab中Line对象编号: 722; Ansys中line编号722 
l,812,813 ! Matlab中Line对象编号: 723; Ansys中line编号723 
l,813,814 ! Matlab中Line对象编号: 724; Ansys中line编号724 
l,814,815 ! Matlab中Line对象编号: 725; Ansys中line编号725 
l,815,816 ! Matlab中Line对象编号: 726; Ansys中line编号726 
l,816,817 ! Matlab中Line对象编号: 727; Ansys中line编号727 
l,817,818 ! Matlab中Line对象编号: 728; Ansys中line编号728 
l,818,819 ! Matlab中Line对象编号: 729; Ansys中line编号729 
l,819,820 ! Matlab中Line对象编号: 730; Ansys中line编号730 
l,820,821 ! Matlab中Line对象编号: 731; Ansys中line编号731 
l,821,822 ! Matlab中Line对象编号: 732; Ansys中line编号732 
l,822,823 ! Matlab中Line对象编号: 733; Ansys中line编号733 
l,823,824 ! Matlab中Line对象编号: 734; Ansys中line编号734 
l,824,825 ! Matlab中Line对象编号: 735; Ansys中line编号735 
l,825,826 ! Matlab中Line对象编号: 736; Ansys中line编号736 
l,826,827 ! Matlab中Line对象编号: 737; Ansys中line编号737 
l,827,828 ! Matlab中Line对象编号: 738; Ansys中line编号738 
l,828,829 ! Matlab中Line对象编号: 739; Ansys中line编号739 
l,829,692 ! Matlab中Line对象编号: 740; Ansys中line编号740 
lsel,all 
cmsel,u,l_selected 
cm,Line_Cable_4,line 
lsel,all 
cm,l_selected,line 
allsel 

! Cable_5 
l,691,832 ! Matlab中Line对象编号: 741; Ansys中line编号741 
l,832,833 ! Matlab中Line对象编号: 742; Ansys中line编号742 
l,833,834 ! Matlab中Line对象编号: 743; Ansys中line编号743 
l,834,835 ! Matlab中Line对象编号: 744; Ansys中line编号744 
l,835,836 ! Matlab中Line对象编号: 745; Ansys中line编号745 
l,836,837 ! Matlab中Line对象编号: 746; Ansys中line编号746 
l,837,838 ! Matlab中Line对象编号: 747; Ansys中line编号747 
l,838,839 ! Matlab中Line对象编号: 748; Ansys中line编号748 
l,839,840 ! Matlab中Line对象编号: 749; Ansys中line编号749 
l,840,841 ! Matlab中Line对象编号: 750; Ansys中line编号750 
l,841,842 ! Matlab中Line对象编号: 751; Ansys中line编号751 
l,842,843 ! Matlab中Line对象编号: 752; Ansys中line编号752 
l,843,844 ! Matlab中Line对象编号: 753; Ansys中line编号753 
l,844,845 ! Matlab中Line对象编号: 754; Ansys中line编号754 
l,845,846 ! Matlab中Line对象编号: 755; Ansys中line编号755 
l,846,847 ! Matlab中Line对象编号: 756; Ansys中line编号756 
l,847,848 ! Matlab中Line对象编号: 757; Ansys中line编号757 
l,848,849 ! Matlab中Line对象编号: 758; Ansys中line编号758 
l,849,850 ! Matlab中Line对象编号: 759; Ansys中line编号759 
l,850,851 ! Matlab中Line对象编号: 760; Ansys中line编号760 
l,851,852 ! Matlab中Line对象编号: 761; Ansys中line编号761 
l,852,853 ! Matlab中Line对象编号: 762; Ansys中line编号762 
lsel,all 
cmsel,u,l_selected 
cm,Line_Cable_5,line 
lsel,all 
cm,l_selected,line 
allsel 

! Cable_6 
l,784,855 ! Matlab中Line对象编号: 763; Ansys中line编号763 
l,855,856 ! Matlab中Line对象编号: 764; Ansys中line编号764 
l,856,857 ! Matlab中Line对象编号: 765; Ansys中line编号765 
l,857,858 ! Matlab中Line对象编号: 766; Ansys中line编号766 
l,858,859 ! Matlab中Line对象编号: 767; Ansys中line编号767 
l,859,860 ! Matlab中Line对象编号: 768; Ansys中line编号768 
l,860,861 ! Matlab中Line对象编号: 769; Ansys中line编号769 
l,861,862 ! Matlab中Line对象编号: 770; Ansys中line编号770 
l,862,863 ! Matlab中Line对象编号: 771; Ansys中line编号771 
l,863,864 ! Matlab中Line对象编号: 772; Ansys中line编号772 
l,864,865 ! Matlab中Line对象编号: 773; Ansys中line编号773 
l,865,866 ! Matlab中Line对象编号: 774; Ansys中line编号774 
l,866,867 ! Matlab中Line对象编号: 775; Ansys中line编号775 
l,867,868 ! Matlab中Line对象编号: 776; Ansys中line编号776 
l,868,869 ! Matlab中Line对象编号: 777; Ansys中line编号777 
l,869,870 ! Matlab中Line对象编号: 778; Ansys中line编号778 
l,870,871 ! Matlab中Line对象编号: 779; Ansys中line编号779 
l,871,872 ! Matlab中Line对象编号: 780; Ansys中line编号780 
l,872,873 ! Matlab中Line对象编号: 781; Ansys中line编号781 
l,873,874 ! Matlab中Line对象编号: 782; Ansys中line编号782 
l,874,875 ! Matlab中Line对象编号: 783; Ansys中line编号783 
l,875,876 ! Matlab中Line对象编号: 784; Ansys中line编号784 
lsel,all 
cmsel,u,l_selected 
cm,Line_Cable_6,line 
lsel,all 
cm,l_selected,line 
allsel 

! Hanger_1 
l,387,624 ! Matlab中Line对象编号: 785; Ansys中line编号785 
l,388,626 ! Matlab中Line对象编号: 786; Ansys中line编号786 
l,389,628 ! Matlab中Line对象编号: 787; Ansys中line编号787 
l,390,630 ! Matlab中Line对象编号: 788; Ansys中line编号788 
l,391,632 ! Matlab中Line对象编号: 789; Ansys中line编号789 
l,392,634 ! Matlab中Line对象编号: 790; Ansys中line编号790 
l,393,636 ! Matlab中Line对象编号: 791; Ansys中line编号791 
l,394,638 ! Matlab中Line对象编号: 792; Ansys中line编号792 
l,395,640 ! Matlab中Line对象编号: 793; Ansys中line编号793 
l,396,642 ! Matlab中Line对象编号: 794; Ansys中line编号794 
l,397,644 ! Matlab中Line对象编号: 795; Ansys中line编号795 
l,398,646 ! Matlab中Line对象编号: 796; Ansys中line编号796 
l,399,648 ! Matlab中Line对象编号: 797; Ansys中line编号797 
l,400,650 ! Matlab中Line对象编号: 798; Ansys中line编号798 
l,401,652 ! Matlab中Line对象编号: 799; Ansys中line编号799 
l,402,654 ! Matlab中Line对象编号: 800; Ansys中line编号800 
l,403,656 ! Matlab中Line对象编号: 801; Ansys中line编号801 
l,404,658 ! Matlab中Line对象编号: 802; Ansys中line编号802 
l,405,660 ! Matlab中Line对象编号: 803; Ansys中line编号803 
l,406,662 ! Matlab中Line对象编号: 804; Ansys中line编号804 
l,407,664 ! Matlab中Line对象编号: 805; Ansys中line编号805 
l,408,666 ! Matlab中Line对象编号: 806; Ansys中line编号806 
lsel,all 
cmsel,u,l_selected 
cm,Line_Hanger_1,line 
lsel,all 
cm,l_selected,line 
allsel 

! Hanger_2 
l,409,717 ! Matlab中Line对象编号: 807; Ansys中line编号807 
l,410,719 ! Matlab中Line对象编号: 808; Ansys中line编号808 
l,411,721 ! Matlab中Line对象编号: 809; Ansys中line编号809 
l,412,723 ! Matlab中Line对象编号: 810; Ansys中line编号810 
l,413,725 ! Matlab中Line对象编号: 811; Ansys中line编号811 
l,414,727 ! Matlab中Line对象编号: 812; Ansys中line编号812 
l,415,729 ! Matlab中Line对象编号: 813; Ansys中line编号813 
l,416,731 ! Matlab中Line对象编号: 814; Ansys中line编号814 
l,417,733 ! Matlab中Line对象编号: 815; Ansys中line编号815 
l,418,735 ! Matlab中Line对象编号: 816; Ansys中line编号816 
l,419,737 ! Matlab中Line对象编号: 817; Ansys中line编号817 
l,420,739 ! Matlab中Line对象编号: 818; Ansys中line编号818 
l,421,741 ! Matlab中Line对象编号: 819; Ansys中line编号819 
l,422,743 ! Matlab中Line对象编号: 820; Ansys中line编号820 
l,423,745 ! Matlab中Line对象编号: 821; Ansys中line编号821 
l,424,747 ! Matlab中Line对象编号: 822; Ansys中line编号822 
l,425,749 ! Matlab中Line对象编号: 823; Ansys中line编号823 
l,426,751 ! Matlab中Line对象编号: 824; Ansys中line编号824 
l,427,753 ! Matlab中Line对象编号: 825; Ansys中line编号825 
l,428,755 ! Matlab中Line对象编号: 826; Ansys中line编号826 
l,429,757 ! Matlab中Line对象编号: 827; Ansys中line编号827 
l,430,759 ! Matlab中Line对象编号: 828; Ansys中line编号828 
lsel,all 
cmsel,u,l_selected 
cm,Line_Hanger_2,line 
lsel,all 
cm,l_selected,line 
allsel 

