function output_str = OutputToAnsys(obj,sec_num)
    output_str = sprintf(['\n' ...
                         'sectype,%d,Beam,ASec \n' ...
                         'secoffset,cent \n' ...
                         'secdata,%E,%E,%E,%E,%E,%E,%E,%E,%E,%E,%E,%E,%E,%E \n'],sec_num, ...
                         obj.A,obj.Iyy,obj.Iyz,obj.Izz,obj.Iw,obj.J,obj.CGy,obj.CGz,obj.SHy,obj.SHz,obj.TKz,obj.TKy,obj.TSxz,obj.TSxy);
end