allsel
esel,none 

cm,e_selected,elem
numstr,elem,1

! Girder_1
lesize,1,,,5 $ lmesh,1
lesize,2,,,5 $ lmesh,2
lesize,3,,,5 $ lmesh,3
lesize,4,,,5 $ lmesh,4
lesize,5,,,5 $ lmesh,5
lesize,6,,,5 $ lmesh,6
lesize,7,,,5 $ lmesh,7
lesize,8,,,5 $ lmesh,8
lesize,9,,,5 $ lmesh,9
lesize,10,,,5 $ lmesh,10
lesize,11,,,5 $ lmesh,11
lesize,12,,,5 $ lmesh,12
lesize,13,,,5 $ lmesh,13
lesize,14,,,5 $ lmesh,14
lesize,15,,,5 $ lmesh,15
lesize,16,,,5 $ lmesh,16
lesize,17,,,5 $ lmesh,17
lesize,18,,,5 $ lmesh,18
lesize,19,,,5 $ lmesh,19
lesize,20,,,5 $ lmesh,20
lesize,21,,,5 $ lmesh,21
lesize,22,,,5 $ lmesh,22
lesize,23,,,5 $ lmesh,23
lesize,24,,,5 $ lmesh,24
lesize,25,,,5 $ lmesh,25
lesize,26,,,5 $ lmesh,26
lesize,27,,,5 $ lmesh,27
lesize,28,,,5 $ lmesh,28
lesize,29,,,5 $ lmesh,29
lesize,30,,,5 $ lmesh,30
lesize,31,,,5 $ lmesh,31
lesize,32,,,5 $ lmesh,32
lesize,33,,,5 $ lmesh,33
lesize,34,,,5 $ lmesh,34
lesize,35,,,5 $ lmesh,35
lesize,36,,,5 $ lmesh,36
lesize,37,,,5 $ lmesh,37
lesize,38,,,5 $ lmesh,38
lesize,39,,,5 $ lmesh,39
lesize,40,,,5 $ lmesh,40
lesize,41,,,5 $ lmesh,41
lesize,42,,,5 $ lmesh,42
lesize,43,,,5 $ lmesh,43
lesize,44,,,5 $ lmesh,44
lesize,45,,,5 $ lmesh,45
lesize,46,,,5 $ lmesh,46
lesize,47,,,5 $ lmesh,47
lesize,48,,,5 $ lmesh,48
lesize,49,,,5 $ lmesh,49
lesize,50,,,5 $ lmesh,50
lesize,51,,,5 $ lmesh,51
lesize,52,,,5 $ lmesh,52
lesize,53,,,5 $ lmesh,53
lesize,54,,,5 $ lmesh,54
lesize,55,,,5 $ lmesh,55
lesize,56,,,5 $ lmesh,56
lesize,57,,,5 $ lmesh,57
lesize,58,,,5 $ lmesh,58
lesize,59,,,5 $ lmesh,59
lesize,60,,,5 $ lmesh,60
lesize,61,,,5 $ lmesh,61
lesize,62,,,5 $ lmesh,62
lesize,63,,,5 $ lmesh,63
lesize,64,,,5 $ lmesh,64
lesize,65,,,5 $ lmesh,65
lesize,66,,,5 $ lmesh,66
lesize,67,,,5 $ lmesh,67
lesize,68,,,5 $ lmesh,68
lesize,69,,,5 $ lmesh,69
lesize,70,,,5 $ lmesh,70
lesize,71,,,5 $ lmesh,71
lesize,72,,,5 $ lmesh,72
lesize,73,,,5 $ lmesh,73
lesize,74,,,5 $ lmesh,74
lesize,75,,,5 $ lmesh,75
lesize,76,,,5 $ lmesh,76
lesize,77,,,5 $ lmesh,77
lesize,78,,,5 $ lmesh,78
lesize,79,,,5 $ lmesh,79
lesize,80,,,5 $ lmesh,80
lesize,81,,,5 $ lmesh,81
lesize,82,,,5 $ lmesh,82
lesize,83,,,5 $ lmesh,83
lesize,84,,,5 $ lmesh,84
lesize,85,,,5 $ lmesh,85
lesize,86,,,5 $ lmesh,86
lesize,87,,,5 $ lmesh,87
lesize,88,,,5 $ lmesh,88
lesize,89,,,5 $ lmesh,89
lesize,90,,,5 $ lmesh,90
lesize,91,,,5 $ lmesh,91
lesize,92,,,5 $ lmesh,92
esel,all 
cmsel,u,e_selected 
cm,Elem_Girder_1,elem 
esel,all 
cm,e_selected,elem 
allsel

! Girder_2
lesize,93,,,5 $ lmesh,93
lesize,94,,,5 $ lmesh,94
lesize,95,,,5 $ lmesh,95
lesize,96,,,5 $ lmesh,96
lesize,97,,,5 $ lmesh,97
lesize,98,,,5 $ lmesh,98
lesize,99,,,5 $ lmesh,99
lesize,100,,,5 $ lmesh,100
lesize,101,,,5 $ lmesh,101
lesize,102,,,5 $ lmesh,102
lesize,103,,,5 $ lmesh,103
lesize,104,,,5 $ lmesh,104
lesize,105,,,5 $ lmesh,105
lesize,106,,,5 $ lmesh,106
lesize,107,,,5 $ lmesh,107
lesize,108,,,5 $ lmesh,108
lesize,109,,,5 $ lmesh,109
lesize,110,,,5 $ lmesh,110
lesize,111,,,5 $ lmesh,111
lesize,112,,,5 $ lmesh,112
lesize,113,,,5 $ lmesh,113
esel,all 
cmsel,u,e_selected 
cm,Elem_Girder_2,elem 
esel,all 
cm,e_selected,elem 
allsel

! Girder_3
lesize,114,,,5 $ lmesh,114
lesize,115,,,5 $ lmesh,115
lesize,116,,,5 $ lmesh,116
lesize,117,,,5 $ lmesh,117
lesize,118,,,5 $ lmesh,118
lesize,119,,,5 $ lmesh,119
lesize,120,,,5 $ lmesh,120
lesize,121,,,5 $ lmesh,121
lesize,122,,,5 $ lmesh,122
lesize,123,,,5 $ lmesh,123
lesize,124,,,5 $ lmesh,124
lesize,125,,,5 $ lmesh,125
lesize,126,,,5 $ lmesh,126
lesize,127,,,5 $ lmesh,127
lesize,128,,,5 $ lmesh,128
lesize,129,,,5 $ lmesh,129
lesize,130,,,5 $ lmesh,130
lesize,131,,,5 $ lmesh,131
lesize,132,,,5 $ lmesh,132
lesize,133,,,5 $ lmesh,133
lesize,134,,,5 $ lmesh,134
esel,all 
cmsel,u,e_selected 
cm,Elem_Girder_3,elem 
esel,all 
cm,e_selected,elem 
allsel

! Girder_4
lesize,135,,,5 $ lmesh,135
lesize,136,,,5 $ lmesh,136
esel,all 
cmsel,u,e_selected 
cm,Elem_Girder_4,elem 
esel,all 
cm,e_selected,elem 
allsel

! Girder_5
lesize,137,,,5 $ lmesh,137
lesize,138,,,5 $ lmesh,138
esel,all 
cmsel,u,e_selected 
cm,Elem_Girder_5,elem 
esel,all 
cm,e_selected,elem 
allsel

! Tower_1
lesize,139,,,5 $ lmesh,139
lesize,140,,,5 $ lmesh,140
lesize,141,,,5 $ lmesh,141
lesize,142,,,5 $ lmesh,142
lesize,143,,,5 $ lmesh,143
lesize,144,,,5 $ lmesh,144
lesize,145,,,5 $ lmesh,145
lesize,146,,,5 $ lmesh,146
lesize,147,,,5 $ lmesh,147
lesize,148,,,5 $ lmesh,148
lesize,149,,,5 $ lmesh,149
lesize,150,,,5 $ lmesh,150
lesize,151,,,5 $ lmesh,151
lesize,152,,,5 $ lmesh,152
lesize,153,,,5 $ lmesh,153
lesize,154,,,5 $ lmesh,154
lesize,155,,,5 $ lmesh,155
lesize,156,,,5 $ lmesh,156
lesize,157,,,5 $ lmesh,157
lesize,158,,,5 $ lmesh,158
lesize,159,,,5 $ lmesh,159
lesize,160,,,5 $ lmesh,160
lesize,161,,,5 $ lmesh,161
lesize,162,,,5 $ lmesh,162
lesize,163,,,5 $ lmesh,163
esel,all 
cmsel,u,e_selected 
cm,Elem_Tower_1,elem 
esel,all 
cm,e_selected,elem 
allsel

! Tower_2
lesize,164,,,5 $ lmesh,164
lesize,165,,,5 $ lmesh,165
lesize,166,,,5 $ lmesh,166
lesize,167,,,5 $ lmesh,167
lesize,168,,,5 $ lmesh,168
lesize,169,,,5 $ lmesh,169
lesize,170,,,5 $ lmesh,170
lesize,171,,,5 $ lmesh,171
lesize,172,,,5 $ lmesh,172
lesize,173,,,5 $ lmesh,173
lesize,174,,,5 $ lmesh,174
lesize,175,,,5 $ lmesh,175
lesize,176,,,5 $ lmesh,176
lesize,177,,,5 $ lmesh,177
lesize,178,,,5 $ lmesh,178
lesize,179,,,5 $ lmesh,179
lesize,180,,,5 $ lmesh,180
lesize,181,,,5 $ lmesh,181
lesize,182,,,5 $ lmesh,182
lesize,183,,,5 $ lmesh,183
lesize,184,,,5 $ lmesh,184
lesize,185,,,5 $ lmesh,185
lesize,186,,,5 $ lmesh,186
lesize,187,,,5 $ lmesh,187
lesize,188,,,5 $ lmesh,188
esel,all 
cmsel,u,e_selected 
cm,Elem_Tower_2,elem 
esel,all 
cm,e_selected,elem 
allsel

! RigidBeam_1
lesize,189,,,1 $ lmesh,189
lesize,190,,,1 $ lmesh,190
lesize,191,,,1 $ lmesh,191
lesize,192,,,1 $ lmesh,192
lesize,193,,,1 $ lmesh,193
lesize,194,,,1 $ lmesh,194
lesize,195,,,1 $ lmesh,195
lesize,196,,,1 $ lmesh,196
lesize,197,,,1 $ lmesh,197
lesize,198,,,1 $ lmesh,198
lesize,199,,,1 $ lmesh,199
lesize,200,,,1 $ lmesh,200
lesize,201,,,1 $ lmesh,201
lesize,202,,,1 $ lmesh,202
lesize,203,,,1 $ lmesh,203
lesize,204,,,1 $ lmesh,204
lesize,205,,,1 $ lmesh,205
lesize,206,,,1 $ lmesh,206
lesize,207,,,1 $ lmesh,207
lesize,208,,,1 $ lmesh,208
lesize,209,,,1 $ lmesh,209
lesize,210,,,1 $ lmesh,210
esel,all 
cmsel,u,e_selected 
cm,Elem_RigidBeam_1,elem 
esel,all 
cm,e_selected,elem 
allsel

! RigidBeam_2
lesize,211,,,1 $ lmesh,211
lesize,212,,,1 $ lmesh,212
lesize,213,,,1 $ lmesh,213
lesize,214,,,1 $ lmesh,214
lesize,215,,,1 $ lmesh,215
lesize,216,,,1 $ lmesh,216
lesize,217,,,1 $ lmesh,217
lesize,218,,,1 $ lmesh,218
lesize,219,,,1 $ lmesh,219
lesize,220,,,1 $ lmesh,220
lesize,221,,,1 $ lmesh,221
lesize,222,,,1 $ lmesh,222
lesize,223,,,1 $ lmesh,223
lesize,224,,,1 $ lmesh,224
lesize,225,,,1 $ lmesh,225
lesize,226,,,1 $ lmesh,226
lesize,227,,,1 $ lmesh,227
lesize,228,,,1 $ lmesh,228
lesize,229,,,1 $ lmesh,229
lesize,230,,,1 $ lmesh,230
lesize,231,,,1 $ lmesh,231
lesize,232,,,1 $ lmesh,232
esel,all 
cmsel,u,e_selected 
cm,Elem_RigidBeam_2,elem 
esel,all 
cm,e_selected,elem 
allsel

! RigidBeam_3
lesize,233,,,1 $ lmesh,233
lesize,234,,,1 $ lmesh,234
lesize,235,,,1 $ lmesh,235
lesize,236,,,1 $ lmesh,236
lesize,237,,,1 $ lmesh,237
lesize,238,,,1 $ lmesh,238
lesize,239,,,1 $ lmesh,239
lesize,240,,,1 $ lmesh,240
lesize,241,,,1 $ lmesh,241
lesize,242,,,1 $ lmesh,242
lesize,243,,,1 $ lmesh,243
lesize,244,,,1 $ lmesh,244
lesize,245,,,1 $ lmesh,245
lesize,246,,,1 $ lmesh,246
esel,all 
cmsel,u,e_selected 
cm,Elem_RigidBeam_3,elem 
esel,all 
cm,e_selected,elem 
allsel

! RigidBeam_4
lesize,247,,,1 $ lmesh,247
lesize,248,,,1 $ lmesh,248
lesize,249,,,1 $ lmesh,249
lesize,250,,,1 $ lmesh,250
lesize,251,,,1 $ lmesh,251
lesize,252,,,1 $ lmesh,252
lesize,253,,,1 $ lmesh,253
lesize,254,,,1 $ lmesh,254
lesize,255,,,1 $ lmesh,255
lesize,256,,,1 $ lmesh,256
lesize,257,,,1 $ lmesh,257
lesize,258,,,1 $ lmesh,258
lesize,259,,,1 $ lmesh,259
lesize,260,,,1 $ lmesh,260
esel,all 
cmsel,u,e_selected 
cm,Elem_RigidBeam_4,elem 
esel,all 
cm,e_selected,elem 
allsel

! RigidBeam_5
lesize,261,,,1 $ lmesh,261
lesize,262,,,1 $ lmesh,262
lesize,263,,,1 $ lmesh,263
lesize,264,,,1 $ lmesh,264
lesize,265,,,1 $ lmesh,265
lesize,266,,,1 $ lmesh,266
lesize,267,,,1 $ lmesh,267
lesize,268,,,1 $ lmesh,268
lesize,269,,,1 $ lmesh,269
lesize,270,,,1 $ lmesh,270
lesize,271,,,1 $ lmesh,271
lesize,272,,,1 $ lmesh,272
lesize,273,,,1 $ lmesh,273
lesize,274,,,1 $ lmesh,274
esel,all 
cmsel,u,e_selected 
cm,Elem_RigidBeam_5,elem 
esel,all 
cm,e_selected,elem 
allsel

! RigidBeam_6
lesize,275,,,1 $ lmesh,275
lesize,276,,,1 $ lmesh,276
lesize,277,,,1 $ lmesh,277
lesize,278,,,1 $ lmesh,278
lesize,279,,,1 $ lmesh,279
lesize,280,,,1 $ lmesh,280
lesize,281,,,1 $ lmesh,281
lesize,282,,,1 $ lmesh,282
lesize,283,,,1 $ lmesh,283
lesize,284,,,1 $ lmesh,284
lesize,285,,,1 $ lmesh,285
lesize,286,,,1 $ lmesh,286
lesize,287,,,1 $ lmesh,287
lesize,288,,,1 $ lmesh,288
esel,all 
cmsel,u,e_selected 
cm,Elem_RigidBeam_6,elem 
esel,all 
cm,e_selected,elem 
allsel

! RigidBeam_7
lesize,289,,,1 $ lmesh,289
lesize,290,,,1 $ lmesh,290
lesize,291,,,1 $ lmesh,291
lesize,292,,,1 $ lmesh,292
lesize,293,,,1 $ lmesh,293
lesize,294,,,1 $ lmesh,294
lesize,295,,,1 $ lmesh,295
lesize,296,,,1 $ lmesh,296
lesize,297,,,1 $ lmesh,297
lesize,298,,,1 $ lmesh,298
lesize,299,,,1 $ lmesh,299
lesize,300,,,1 $ lmesh,300
lesize,301,,,1 $ lmesh,301
lesize,302,,,1 $ lmesh,302
esel,all 
cmsel,u,e_selected 
cm,Elem_RigidBeam_7,elem 
esel,all 
cm,e_selected,elem 
allsel

! RigidBeam_8
lesize,303,,,1 $ lmesh,303
lesize,304,,,1 $ lmesh,304
lesize,305,,,1 $ lmesh,305
lesize,306,,,1 $ lmesh,306
lesize,307,,,1 $ lmesh,307
lesize,308,,,1 $ lmesh,308
lesize,309,,,1 $ lmesh,309
lesize,310,,,1 $ lmesh,310
lesize,311,,,1 $ lmesh,311
lesize,312,,,1 $ lmesh,312
lesize,313,,,1 $ lmesh,313
lesize,314,,,1 $ lmesh,314
lesize,315,,,1 $ lmesh,315
lesize,316,,,1 $ lmesh,316
esel,all 
cmsel,u,e_selected 
cm,Elem_RigidBeam_8,elem 
esel,all 
cm,e_selected,elem 
allsel

! RigidBeam_9
lesize,317,,,1 $ lmesh,317
lesize,318,,,1 $ lmesh,318
lesize,319,,,1 $ lmesh,319
lesize,320,,,1 $ lmesh,320
lesize,321,,,1 $ lmesh,321
lesize,322,,,1 $ lmesh,322
lesize,323,,,1 $ lmesh,323
lesize,324,,,1 $ lmesh,324
lesize,325,,,1 $ lmesh,325
lesize,326,,,1 $ lmesh,326
lesize,327,,,1 $ lmesh,327
lesize,328,,,1 $ lmesh,328
lesize,329,,,1 $ lmesh,329
lesize,330,,,1 $ lmesh,330
esel,all 
cmsel,u,e_selected 
cm,Elem_RigidBeam_9,elem 
esel,all 
cm,e_selected,elem 
allsel

! RigidBeam_10
lesize,331,,,1 $ lmesh,331
lesize,332,,,1 $ lmesh,332
lesize,333,,,1 $ lmesh,333
lesize,334,,,1 $ lmesh,334
lesize,335,,,1 $ lmesh,335
lesize,336,,,1 $ lmesh,336
lesize,337,,,1 $ lmesh,337
lesize,338,,,1 $ lmesh,338
lesize,339,,,1 $ lmesh,339
lesize,340,,,1 $ lmesh,340
lesize,341,,,1 $ lmesh,341
lesize,342,,,1 $ lmesh,342
lesize,343,,,1 $ lmesh,343
lesize,344,,,1 $ lmesh,344
esel,all 
cmsel,u,e_selected 
cm,Elem_RigidBeam_10,elem 
esel,all 
cm,e_selected,elem 
allsel

! RigidBeam_11
lesize,345,,,1 $ lmesh,345
lesize,346,,,1 $ lmesh,346
lesize,347,,,1 $ lmesh,347
lesize,348,,,1 $ lmesh,348
lesize,349,,,1 $ lmesh,349
lesize,350,,,1 $ lmesh,350
lesize,351,,,1 $ lmesh,351
lesize,352,,,1 $ lmesh,352
lesize,353,,,1 $ lmesh,353
lesize,354,,,1 $ lmesh,354
lesize,355,,,1 $ lmesh,355
lesize,356,,,1 $ lmesh,356
lesize,357,,,1 $ lmesh,357
lesize,358,,,1 $ lmesh,358
esel,all 
cmsel,u,e_selected 
cm,Elem_RigidBeam_11,elem 
esel,all 
cm,e_selected,elem 
allsel

! RigidBeam_12
lesize,359,,,1 $ lmesh,359
lesize,360,,,1 $ lmesh,360
lesize,361,,,1 $ lmesh,361
lesize,362,,,1 $ lmesh,362
lesize,363,,,1 $ lmesh,363
lesize,364,,,1 $ lmesh,364
lesize,365,,,1 $ lmesh,365
lesize,366,,,1 $ lmesh,366
lesize,367,,,1 $ lmesh,367
lesize,368,,,1 $ lmesh,368
lesize,369,,,1 $ lmesh,369
lesize,370,,,1 $ lmesh,370
lesize,371,,,1 $ lmesh,371
lesize,372,,,1 $ lmesh,372
esel,all 
cmsel,u,e_selected 
cm,Elem_RigidBeam_12,elem 
esel,all 
cm,e_selected,elem 
allsel

! RigidBeam_13
lesize,373,,,1 $ lmesh,373
lesize,374,,,1 $ lmesh,374
lesize,375,,,1 $ lmesh,375
lesize,376,,,1 $ lmesh,376
lesize,377,,,1 $ lmesh,377
lesize,378,,,1 $ lmesh,378
lesize,379,,,1 $ lmesh,379
lesize,380,,,1 $ lmesh,380
lesize,381,,,1 $ lmesh,381
lesize,382,,,1 $ lmesh,382
lesize,383,,,1 $ lmesh,383
lesize,384,,,1 $ lmesh,384
lesize,385,,,1 $ lmesh,385
lesize,386,,,1 $ lmesh,386
esel,all 
cmsel,u,e_selected 
cm,Elem_RigidBeam_13,elem 
esel,all 
cm,e_selected,elem 
allsel

! RigidBeam_14
lesize,387,,,1 $ lmesh,387
lesize,388,,,1 $ lmesh,388
lesize,389,,,1 $ lmesh,389
lesize,390,,,1 $ lmesh,390
lesize,391,,,1 $ lmesh,391
lesize,392,,,1 $ lmesh,392
lesize,393,,,1 $ lmesh,393
lesize,394,,,1 $ lmesh,394
lesize,395,,,1 $ lmesh,395
lesize,396,,,1 $ lmesh,396
lesize,397,,,1 $ lmesh,397
lesize,398,,,1 $ lmesh,398
lesize,399,,,1 $ lmesh,399
lesize,400,,,1 $ lmesh,400
esel,all 
cmsel,u,e_selected 
cm,Elem_RigidBeam_14,elem 
esel,all 
cm,e_selected,elem 
allsel

! StayedCable_1
lesize,401,,,1 $ lmesh,401
lesize,402,,,1 $ lmesh,402
lesize,403,,,1 $ lmesh,403
lesize,404,,,1 $ lmesh,404
lesize,405,,,1 $ lmesh,405
lesize,406,,,1 $ lmesh,406
lesize,407,,,1 $ lmesh,407
lesize,408,,,1 $ lmesh,408
lesize,409,,,1 $ lmesh,409
lesize,410,,,1 $ lmesh,410
lesize,411,,,1 $ lmesh,411
lesize,412,,,1 $ lmesh,412
lesize,413,,,1 $ lmesh,413
lesize,414,,,1 $ lmesh,414
esel,all 
cmsel,u,e_selected 
cm,Elem_StayedCable_1,elem 
esel,all 
cm,e_selected,elem 
allsel

! StayedCable_2
lesize,415,,,1 $ lmesh,415
lesize,416,,,1 $ lmesh,416
lesize,417,,,1 $ lmesh,417
lesize,418,,,1 $ lmesh,418
lesize,419,,,1 $ lmesh,419
lesize,420,,,1 $ lmesh,420
lesize,421,,,1 $ lmesh,421
lesize,422,,,1 $ lmesh,422
lesize,423,,,1 $ lmesh,423
lesize,424,,,1 $ lmesh,424
lesize,425,,,1 $ lmesh,425
lesize,426,,,1 $ lmesh,426
lesize,427,,,1 $ lmesh,427
lesize,428,,,1 $ lmesh,428
esel,all 
cmsel,u,e_selected 
cm,Elem_StayedCable_2,elem 
esel,all 
cm,e_selected,elem 
allsel

! StayedCable_3
lesize,429,,,1 $ lmesh,429
lesize,430,,,1 $ lmesh,430
lesize,431,,,1 $ lmesh,431
lesize,432,,,1 $ lmesh,432
lesize,433,,,1 $ lmesh,433
lesize,434,,,1 $ lmesh,434
lesize,435,,,1 $ lmesh,435
lesize,436,,,1 $ lmesh,436
lesize,437,,,1 $ lmesh,437
lesize,438,,,1 $ lmesh,438
lesize,439,,,1 $ lmesh,439
lesize,440,,,1 $ lmesh,440
lesize,441,,,1 $ lmesh,441
lesize,442,,,1 $ lmesh,442
esel,all 
cmsel,u,e_selected 
cm,Elem_StayedCable_3,elem 
esel,all 
cm,e_selected,elem 
allsel

! StayedCable_4
lesize,443,,,1 $ lmesh,443
lesize,444,,,1 $ lmesh,444
lesize,445,,,1 $ lmesh,445
lesize,446,,,1 $ lmesh,446
lesize,447,,,1 $ lmesh,447
lesize,448,,,1 $ lmesh,448
lesize,449,,,1 $ lmesh,449
lesize,450,,,1 $ lmesh,450
lesize,451,,,1 $ lmesh,451
lesize,452,,,1 $ lmesh,452
lesize,453,,,1 $ lmesh,453
lesize,454,,,1 $ lmesh,454
lesize,455,,,1 $ lmesh,455
lesize,456,,,1 $ lmesh,456
esel,all 
cmsel,u,e_selected 
cm,Elem_StayedCable_4,elem 
esel,all 
cm,e_selected,elem 
allsel

! StayedCable_5
lesize,457,,,1 $ lmesh,457
lesize,458,,,1 $ lmesh,458
lesize,459,,,1 $ lmesh,459
lesize,460,,,1 $ lmesh,460
lesize,461,,,1 $ lmesh,461
lesize,462,,,1 $ lmesh,462
lesize,463,,,1 $ lmesh,463
lesize,464,,,1 $ lmesh,464
lesize,465,,,1 $ lmesh,465
lesize,466,,,1 $ lmesh,466
lesize,467,,,1 $ lmesh,467
lesize,468,,,1 $ lmesh,468
lesize,469,,,1 $ lmesh,469
lesize,470,,,1 $ lmesh,470
esel,all 
cmsel,u,e_selected 
cm,Elem_StayedCable_5,elem 
esel,all 
cm,e_selected,elem 
allsel

! StayedCable_6
lesize,471,,,1 $ lmesh,471
lesize,472,,,1 $ lmesh,472
lesize,473,,,1 $ lmesh,473
lesize,474,,,1 $ lmesh,474
lesize,475,,,1 $ lmesh,475
lesize,476,,,1 $ lmesh,476
lesize,477,,,1 $ lmesh,477
lesize,478,,,1 $ lmesh,478
lesize,479,,,1 $ lmesh,479
lesize,480,,,1 $ lmesh,480
lesize,481,,,1 $ lmesh,481
lesize,482,,,1 $ lmesh,482
lesize,483,,,1 $ lmesh,483
lesize,484,,,1 $ lmesh,484
esel,all 
cmsel,u,e_selected 
cm,Elem_StayedCable_6,elem 
esel,all 
cm,e_selected,elem 
allsel

! StayedCable_7
lesize,485,,,1 $ lmesh,485
lesize,486,,,1 $ lmesh,486
lesize,487,,,1 $ lmesh,487
lesize,488,,,1 $ lmesh,488
lesize,489,,,1 $ lmesh,489
lesize,490,,,1 $ lmesh,490
lesize,491,,,1 $ lmesh,491
lesize,492,,,1 $ lmesh,492
lesize,493,,,1 $ lmesh,493
lesize,494,,,1 $ lmesh,494
lesize,495,,,1 $ lmesh,495
lesize,496,,,1 $ lmesh,496
lesize,497,,,1 $ lmesh,497
lesize,498,,,1 $ lmesh,498
esel,all 
cmsel,u,e_selected 
cm,Elem_StayedCable_7,elem 
esel,all 
cm,e_selected,elem 
allsel

! StayedCable_8
lesize,499,,,1 $ lmesh,499
lesize,500,,,1 $ lmesh,500
lesize,501,,,1 $ lmesh,501
lesize,502,,,1 $ lmesh,502
lesize,503,,,1 $ lmesh,503
lesize,504,,,1 $ lmesh,504
lesize,505,,,1 $ lmesh,505
lesize,506,,,1 $ lmesh,506
lesize,507,,,1 $ lmesh,507
lesize,508,,,1 $ lmesh,508
lesize,509,,,1 $ lmesh,509
lesize,510,,,1 $ lmesh,510
lesize,511,,,1 $ lmesh,511
lesize,512,,,1 $ lmesh,512
esel,all 
cmsel,u,e_selected 
cm,Elem_StayedCable_8,elem 
esel,all 
cm,e_selected,elem 
allsel

! Cable_1
lesize,513,,,1 $ lmesh,513
lesize,514,,,1 $ lmesh,514
lesize,515,,,1 $ lmesh,515
lesize,516,,,1 $ lmesh,516
lesize,517,,,1 $ lmesh,517
lesize,518,,,1 $ lmesh,518
lesize,519,,,1 $ lmesh,519
lesize,520,,,1 $ lmesh,520
lesize,521,,,1 $ lmesh,521
lesize,522,,,1 $ lmesh,522
lesize,523,,,1 $ lmesh,523
lesize,524,,,1 $ lmesh,524
lesize,525,,,1 $ lmesh,525
lesize,526,,,1 $ lmesh,526
lesize,527,,,1 $ lmesh,527
lesize,528,,,1 $ lmesh,528
lesize,529,,,1 $ lmesh,529
lesize,530,,,1 $ lmesh,530
lesize,531,,,1 $ lmesh,531
lesize,532,,,1 $ lmesh,532
lesize,533,,,1 $ lmesh,533
lesize,534,,,1 $ lmesh,534
lesize,535,,,1 $ lmesh,535
lesize,536,,,1 $ lmesh,536
lesize,537,,,1 $ lmesh,537
lesize,538,,,1 $ lmesh,538
lesize,539,,,1 $ lmesh,539
lesize,540,,,1 $ lmesh,540
lesize,541,,,1 $ lmesh,541
lesize,542,,,1 $ lmesh,542
lesize,543,,,1 $ lmesh,543
lesize,544,,,1 $ lmesh,544
lesize,545,,,1 $ lmesh,545
lesize,546,,,1 $ lmesh,546
lesize,547,,,1 $ lmesh,547
lesize,548,,,1 $ lmesh,548
lesize,549,,,1 $ lmesh,549
lesize,550,,,1 $ lmesh,550
lesize,551,,,1 $ lmesh,551
lesize,552,,,1 $ lmesh,552
lesize,553,,,1 $ lmesh,553
lesize,554,,,1 $ lmesh,554
lesize,555,,,1 $ lmesh,555
lesize,556,,,1 $ lmesh,556
lesize,557,,,1 $ lmesh,557
lesize,558,,,1 $ lmesh,558
lesize,559,,,1 $ lmesh,559
lesize,560,,,1 $ lmesh,560
lesize,561,,,1 $ lmesh,561
lesize,562,,,1 $ lmesh,562
lesize,563,,,1 $ lmesh,563
lesize,564,,,1 $ lmesh,564
lesize,565,,,1 $ lmesh,565
lesize,566,,,1 $ lmesh,566
lesize,567,,,1 $ lmesh,567
lesize,568,,,1 $ lmesh,568
lesize,569,,,1 $ lmesh,569
lesize,570,,,1 $ lmesh,570
lesize,571,,,1 $ lmesh,571
lesize,572,,,1 $ lmesh,572
lesize,573,,,1 $ lmesh,573
lesize,574,,,1 $ lmesh,574
lesize,575,,,1 $ lmesh,575
lesize,576,,,1 $ lmesh,576
lesize,577,,,1 $ lmesh,577
lesize,578,,,1 $ lmesh,578
lesize,579,,,1 $ lmesh,579
lesize,580,,,1 $ lmesh,580
lesize,581,,,1 $ lmesh,581
lesize,582,,,1 $ lmesh,582
lesize,583,,,1 $ lmesh,583
lesize,584,,,1 $ lmesh,584
lesize,585,,,1 $ lmesh,585
lesize,586,,,1 $ lmesh,586
lesize,587,,,1 $ lmesh,587
lesize,588,,,1 $ lmesh,588
lesize,589,,,1 $ lmesh,589
lesize,590,,,1 $ lmesh,590
lesize,591,,,1 $ lmesh,591
lesize,592,,,1 $ lmesh,592
lesize,593,,,1 $ lmesh,593
lesize,594,,,1 $ lmesh,594
lesize,595,,,1 $ lmesh,595
lesize,596,,,1 $ lmesh,596
lesize,597,,,1 $ lmesh,597
lesize,598,,,1 $ lmesh,598
lesize,599,,,1 $ lmesh,599
lesize,600,,,1 $ lmesh,600
lesize,601,,,1 $ lmesh,601
lesize,602,,,1 $ lmesh,602
lesize,603,,,1 $ lmesh,603
lesize,604,,,1 $ lmesh,604
esel,all 
cmsel,u,e_selected 
cm,Elem_Cable_1,elem 
esel,all 
cm,e_selected,elem 
allsel

! Cable_2
lesize,605,,,1 $ lmesh,605
lesize,606,,,1 $ lmesh,606
lesize,607,,,1 $ lmesh,607
lesize,608,,,1 $ lmesh,608
lesize,609,,,1 $ lmesh,609
lesize,610,,,1 $ lmesh,610
lesize,611,,,1 $ lmesh,611
lesize,612,,,1 $ lmesh,612
lesize,613,,,1 $ lmesh,613
lesize,614,,,1 $ lmesh,614
lesize,615,,,1 $ lmesh,615
lesize,616,,,1 $ lmesh,616
lesize,617,,,1 $ lmesh,617
lesize,618,,,1 $ lmesh,618
lesize,619,,,1 $ lmesh,619
lesize,620,,,1 $ lmesh,620
lesize,621,,,1 $ lmesh,621
lesize,622,,,1 $ lmesh,622
lesize,623,,,1 $ lmesh,623
lesize,624,,,1 $ lmesh,624
lesize,625,,,1 $ lmesh,625
lesize,626,,,1 $ lmesh,626
lesize,627,,,1 $ lmesh,627
lesize,628,,,1 $ lmesh,628
lesize,629,,,1 $ lmesh,629
lesize,630,,,1 $ lmesh,630
lesize,631,,,1 $ lmesh,631
lesize,632,,,1 $ lmesh,632
lesize,633,,,1 $ lmesh,633
lesize,634,,,1 $ lmesh,634
lesize,635,,,1 $ lmesh,635
lesize,636,,,1 $ lmesh,636
lesize,637,,,1 $ lmesh,637
lesize,638,,,1 $ lmesh,638
lesize,639,,,1 $ lmesh,639
lesize,640,,,1 $ lmesh,640
lesize,641,,,1 $ lmesh,641
lesize,642,,,1 $ lmesh,642
lesize,643,,,1 $ lmesh,643
lesize,644,,,1 $ lmesh,644
lesize,645,,,1 $ lmesh,645
lesize,646,,,1 $ lmesh,646
lesize,647,,,1 $ lmesh,647
lesize,648,,,1 $ lmesh,648
lesize,649,,,1 $ lmesh,649
lesize,650,,,1 $ lmesh,650
lesize,651,,,1 $ lmesh,651
lesize,652,,,1 $ lmesh,652
lesize,653,,,1 $ lmesh,653
lesize,654,,,1 $ lmesh,654
lesize,655,,,1 $ lmesh,655
lesize,656,,,1 $ lmesh,656
lesize,657,,,1 $ lmesh,657
lesize,658,,,1 $ lmesh,658
lesize,659,,,1 $ lmesh,659
lesize,660,,,1 $ lmesh,660
lesize,661,,,1 $ lmesh,661
lesize,662,,,1 $ lmesh,662
lesize,663,,,1 $ lmesh,663
lesize,664,,,1 $ lmesh,664
lesize,665,,,1 $ lmesh,665
lesize,666,,,1 $ lmesh,666
lesize,667,,,1 $ lmesh,667
lesize,668,,,1 $ lmesh,668
lesize,669,,,1 $ lmesh,669
lesize,670,,,1 $ lmesh,670
lesize,671,,,1 $ lmesh,671
lesize,672,,,1 $ lmesh,672
lesize,673,,,1 $ lmesh,673
lesize,674,,,1 $ lmesh,674
lesize,675,,,1 $ lmesh,675
lesize,676,,,1 $ lmesh,676
lesize,677,,,1 $ lmesh,677
lesize,678,,,1 $ lmesh,678
lesize,679,,,1 $ lmesh,679
lesize,680,,,1 $ lmesh,680
lesize,681,,,1 $ lmesh,681
lesize,682,,,1 $ lmesh,682
lesize,683,,,1 $ lmesh,683
lesize,684,,,1 $ lmesh,684
lesize,685,,,1 $ lmesh,685
lesize,686,,,1 $ lmesh,686
lesize,687,,,1 $ lmesh,687
lesize,688,,,1 $ lmesh,688
lesize,689,,,1 $ lmesh,689
lesize,690,,,1 $ lmesh,690
lesize,691,,,1 $ lmesh,691
lesize,692,,,1 $ lmesh,692
lesize,693,,,1 $ lmesh,693
lesize,694,,,1 $ lmesh,694
lesize,695,,,1 $ lmesh,695
lesize,696,,,1 $ lmesh,696
esel,all 
cmsel,u,e_selected 
cm,Elem_Cable_2,elem 
esel,all 
cm,e_selected,elem 
allsel

! Cable_3
lesize,697,,,1 $ lmesh,697
lesize,698,,,1 $ lmesh,698
lesize,699,,,1 $ lmesh,699
lesize,700,,,1 $ lmesh,700
lesize,701,,,1 $ lmesh,701
lesize,702,,,1 $ lmesh,702
lesize,703,,,1 $ lmesh,703
lesize,704,,,1 $ lmesh,704
lesize,705,,,1 $ lmesh,705
lesize,706,,,1 $ lmesh,706
lesize,707,,,1 $ lmesh,707
lesize,708,,,1 $ lmesh,708
lesize,709,,,1 $ lmesh,709
lesize,710,,,1 $ lmesh,710
lesize,711,,,1 $ lmesh,711
lesize,712,,,1 $ lmesh,712
lesize,713,,,1 $ lmesh,713
lesize,714,,,1 $ lmesh,714
lesize,715,,,1 $ lmesh,715
lesize,716,,,1 $ lmesh,716
lesize,717,,,1 $ lmesh,717
lesize,718,,,1 $ lmesh,718
esel,all 
cmsel,u,e_selected 
cm,Elem_Cable_3,elem 
esel,all 
cm,e_selected,elem 
allsel

! Cable_4
lesize,719,,,1 $ lmesh,719
lesize,720,,,1 $ lmesh,720
lesize,721,,,1 $ lmesh,721
lesize,722,,,1 $ lmesh,722
lesize,723,,,1 $ lmesh,723
lesize,724,,,1 $ lmesh,724
lesize,725,,,1 $ lmesh,725
lesize,726,,,1 $ lmesh,726
lesize,727,,,1 $ lmesh,727
lesize,728,,,1 $ lmesh,728
lesize,729,,,1 $ lmesh,729
lesize,730,,,1 $ lmesh,730
lesize,731,,,1 $ lmesh,731
lesize,732,,,1 $ lmesh,732
lesize,733,,,1 $ lmesh,733
lesize,734,,,1 $ lmesh,734
lesize,735,,,1 $ lmesh,735
lesize,736,,,1 $ lmesh,736
lesize,737,,,1 $ lmesh,737
lesize,738,,,1 $ lmesh,738
lesize,739,,,1 $ lmesh,739
lesize,740,,,1 $ lmesh,740
esel,all 
cmsel,u,e_selected 
cm,Elem_Cable_4,elem 
esel,all 
cm,e_selected,elem 
allsel

! Cable_5
lesize,741,,,1 $ lmesh,741
lesize,742,,,1 $ lmesh,742
lesize,743,,,1 $ lmesh,743
lesize,744,,,1 $ lmesh,744
lesize,745,,,1 $ lmesh,745
lesize,746,,,1 $ lmesh,746
lesize,747,,,1 $ lmesh,747
lesize,748,,,1 $ lmesh,748
lesize,749,,,1 $ lmesh,749
lesize,750,,,1 $ lmesh,750
lesize,751,,,1 $ lmesh,751
lesize,752,,,1 $ lmesh,752
lesize,753,,,1 $ lmesh,753
lesize,754,,,1 $ lmesh,754
lesize,755,,,1 $ lmesh,755
lesize,756,,,1 $ lmesh,756
lesize,757,,,1 $ lmesh,757
lesize,758,,,1 $ lmesh,758
lesize,759,,,1 $ lmesh,759
lesize,760,,,1 $ lmesh,760
lesize,761,,,1 $ lmesh,761
lesize,762,,,1 $ lmesh,762
esel,all 
cmsel,u,e_selected 
cm,Elem_Cable_5,elem 
esel,all 
cm,e_selected,elem 
allsel

! Cable_6
lesize,763,,,1 $ lmesh,763
lesize,764,,,1 $ lmesh,764
lesize,765,,,1 $ lmesh,765
lesize,766,,,1 $ lmesh,766
lesize,767,,,1 $ lmesh,767
lesize,768,,,1 $ lmesh,768
lesize,769,,,1 $ lmesh,769
lesize,770,,,1 $ lmesh,770
lesize,771,,,1 $ lmesh,771
lesize,772,,,1 $ lmesh,772
lesize,773,,,1 $ lmesh,773
lesize,774,,,1 $ lmesh,774
lesize,775,,,1 $ lmesh,775
lesize,776,,,1 $ lmesh,776
lesize,777,,,1 $ lmesh,777
lesize,778,,,1 $ lmesh,778
lesize,779,,,1 $ lmesh,779
lesize,780,,,1 $ lmesh,780
lesize,781,,,1 $ lmesh,781
lesize,782,,,1 $ lmesh,782
lesize,783,,,1 $ lmesh,783
lesize,784,,,1 $ lmesh,784
esel,all 
cmsel,u,e_selected 
cm,Elem_Cable_6,elem 
esel,all 
cm,e_selected,elem 
allsel

! Hanger_1
lesize,785,,,1 $ lmesh,785
lesize,786,,,1 $ lmesh,786
lesize,787,,,1 $ lmesh,787
lesize,788,,,1 $ lmesh,788
lesize,789,,,1 $ lmesh,789
lesize,790,,,1 $ lmesh,790
lesize,791,,,1 $ lmesh,791
lesize,792,,,1 $ lmesh,792
lesize,793,,,1 $ lmesh,793
lesize,794,,,1 $ lmesh,794
lesize,795,,,1 $ lmesh,795
lesize,796,,,1 $ lmesh,796
lesize,797,,,1 $ lmesh,797
lesize,798,,,1 $ lmesh,798
lesize,799,,,1 $ lmesh,799
lesize,800,,,1 $ lmesh,800
lesize,801,,,1 $ lmesh,801
lesize,802,,,1 $ lmesh,802
lesize,803,,,1 $ lmesh,803
lesize,804,,,1 $ lmesh,804
lesize,805,,,1 $ lmesh,805
lesize,806,,,1 $ lmesh,806
esel,all 
cmsel,u,e_selected 
cm,Elem_Hanger_1,elem 
esel,all 
cm,e_selected,elem 
allsel

! Hanger_2
lesize,807,,,1 $ lmesh,807
lesize,808,,,1 $ lmesh,808
lesize,809,,,1 $ lmesh,809
lesize,810,,,1 $ lmesh,810
lesize,811,,,1 $ lmesh,811
lesize,812,,,1 $ lmesh,812
lesize,813,,,1 $ lmesh,813
lesize,814,,,1 $ lmesh,814
lesize,815,,,1 $ lmesh,815
lesize,816,,,1 $ lmesh,816
lesize,817,,,1 $ lmesh,817
lesize,818,,,1 $ lmesh,818
lesize,819,,,1 $ lmesh,819
lesize,820,,,1 $ lmesh,820
lesize,821,,,1 $ lmesh,821
lesize,822,,,1 $ lmesh,822
lesize,823,,,1 $ lmesh,823
lesize,824,,,1 $ lmesh,824
lesize,825,,,1 $ lmesh,825
lesize,826,,,1 $ lmesh,826
lesize,827,,,1 $ lmesh,827
lesize,828,,,1 $ lmesh,828
esel,all 
cmsel,u,e_selected 
cm,Elem_Hanger_2,elem 
esel,all 
cm,e_selected,elem 
allsel

